// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openbank/openbank/v1/entitlement/all.proto

package entitlement

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddEntitlementRequestForCurrentUserRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=RoleName,json=role_name,proto3" json:"RoleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEntitlementRequestForCurrentUserRequest) Reset() {
	*m = AddEntitlementRequestForCurrentUserRequest{}
}
func (m *AddEntitlementRequestForCurrentUserRequest) String() string {
	return proto.CompactTextString(m)
}
func (*AddEntitlementRequestForCurrentUserRequest) ProtoMessage() {}
func (*AddEntitlementRequestForCurrentUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{0}
}

func (m *AddEntitlementRequestForCurrentUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEntitlementRequestForCurrentUserRequest.Unmarshal(m, b)
}
func (m *AddEntitlementRequestForCurrentUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEntitlementRequestForCurrentUserRequest.Marshal(b, m, deterministic)
}
func (m *AddEntitlementRequestForCurrentUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEntitlementRequestForCurrentUserRequest.Merge(m, src)
}
func (m *AddEntitlementRequestForCurrentUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddEntitlementRequestForCurrentUserRequest.Size(m)
}
func (m *AddEntitlementRequestForCurrentUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEntitlementRequestForCurrentUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEntitlementRequestForCurrentUserRequest proto.InternalMessageInfo

func (m *AddEntitlementRequestForCurrentUserRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *AddEntitlementRequestForCurrentUserRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type EntitlementRequest struct {
	EntitlementRequestID string               `protobuf:"bytes,1,opt,name=EntitlementRequestID,json=entitlement_request_id,proto3" json:"EntitlementRequestID,omitempty"`
	User                 *User                `protobuf:"bytes,2,opt,name=User,json=user,proto3" json:"User,omitempty"`
	RoleName             string               `protobuf:"bytes,3,opt,name=RoleName,json=role_name,proto3" json:"RoleName,omitempty"`
	BankID               string               `protobuf:"bytes,4,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=Created,json=created,proto3" json:"Created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EntitlementRequest) Reset()         { *m = EntitlementRequest{} }
func (m *EntitlementRequest) String() string { return proto.CompactTextString(m) }
func (*EntitlementRequest) ProtoMessage()    {}
func (*EntitlementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{1}
}

func (m *EntitlementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntitlementRequest.Unmarshal(m, b)
}
func (m *EntitlementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntitlementRequest.Marshal(b, m, deterministic)
}
func (m *EntitlementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntitlementRequest.Merge(m, src)
}
func (m *EntitlementRequest) XXX_Size() int {
	return xxx_messageInfo_EntitlementRequest.Size(m)
}
func (m *EntitlementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntitlementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntitlementRequest proto.InternalMessageInfo

func (m *EntitlementRequest) GetEntitlementRequestID() string {
	if m != nil {
		return m.EntitlementRequestID
	}
	return ""
}

func (m *EntitlementRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EntitlementRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *EntitlementRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *EntitlementRequest) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type EntitlementRequests struct {
	EntitlementRequests  []*EntitlementRequest `protobuf:"bytes,1,rep,name=EntitlementRequests,json=entitlement_requests,proto3" json:"EntitlementRequests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EntitlementRequests) Reset()         { *m = EntitlementRequests{} }
func (m *EntitlementRequests) String() string { return proto.CompactTextString(m) }
func (*EntitlementRequests) ProtoMessage()    {}
func (*EntitlementRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{2}
}

func (m *EntitlementRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntitlementRequests.Unmarshal(m, b)
}
func (m *EntitlementRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntitlementRequests.Marshal(b, m, deterministic)
}
func (m *EntitlementRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntitlementRequests.Merge(m, src)
}
func (m *EntitlementRequests) XXX_Size() int {
	return xxx_messageInfo_EntitlementRequests.Size(m)
}
func (m *EntitlementRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_EntitlementRequests.DiscardUnknown(m)
}

var xxx_messageInfo_EntitlementRequests proto.InternalMessageInfo

func (m *EntitlementRequests) GetEntitlementRequests() []*EntitlementRequest {
	if m != nil {
		return m.EntitlementRequests
	}
	return nil
}

type List struct {
	EntitlementID        string   `protobuf:"bytes,1,opt,name=EntitlementID,json=entitlement_id,proto3" json:"EntitlementID,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=RoleName,json=role_name,proto3" json:"RoleName,omitempty"`
	BankID               string   `protobuf:"bytes,3,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{3}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetEntitlementID() string {
	if m != nil {
		return m.EntitlementID
	}
	return ""
}

func (m *List) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *List) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

type Entitlements struct {
	List                 []*List  `protobuf:"bytes,1,rep,name=List,json=list,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entitlements) Reset()         { *m = Entitlements{} }
func (m *Entitlements) String() string { return proto.CompactTextString(m) }
func (*Entitlements) ProtoMessage()    {}
func (*Entitlements) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{4}
}

func (m *Entitlements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entitlements.Unmarshal(m, b)
}
func (m *Entitlements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entitlements.Marshal(b, m, deterministic)
}
func (m *Entitlements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entitlements.Merge(m, src)
}
func (m *Entitlements) XXX_Size() int {
	return xxx_messageInfo_Entitlements.Size(m)
}
func (m *Entitlements) XXX_DiscardUnknown() {
	xxx_messageInfo_Entitlements.DiscardUnknown(m)
}

var xxx_messageInfo_Entitlements proto.InternalMessageInfo

func (m *Entitlements) GetList() []*List {
	if m != nil {
		return m.List
	}
	return nil
}

type User struct {
	UserID               string        `protobuf:"bytes,1,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	Email                string        `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	ProviderID           string        `protobuf:"bytes,3,opt,name=ProviderID,json=provider_id,proto3" json:"ProviderID,omitempty"`
	Provider             string        `protobuf:"bytes,4,opt,name=Provider,json=provider,proto3" json:"Provider,omitempty"`
	Username             string        `protobuf:"bytes,5,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	Entitlements         *Entitlements `protobuf:"bytes,6,opt,name=Entitlements,json=entitlements,proto3" json:"Entitlements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *User) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEntitlements() *Entitlements {
	if m != nil {
		return m.Entitlements
	}
	return nil
}

type AddEntitlementRequestForUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	BankID               string   `protobuf:"bytes,2,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=RoleName,json=role_name,proto3" json:"RoleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEntitlementRequestForUserRequest) Reset()         { *m = AddEntitlementRequestForUserRequest{} }
func (m *AddEntitlementRequestForUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddEntitlementRequestForUserRequest) ProtoMessage()    {}
func (*AddEntitlementRequestForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{6}
}

func (m *AddEntitlementRequestForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEntitlementRequestForUserRequest.Unmarshal(m, b)
}
func (m *AddEntitlementRequestForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEntitlementRequestForUserRequest.Marshal(b, m, deterministic)
}
func (m *AddEntitlementRequestForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEntitlementRequestForUserRequest.Merge(m, src)
}
func (m *AddEntitlementRequestForUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddEntitlementRequestForUserRequest.Size(m)
}
func (m *AddEntitlementRequestForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEntitlementRequestForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEntitlementRequestForUserRequest proto.InternalMessageInfo

func (m *AddEntitlementRequestForUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddEntitlementRequestForUserRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *AddEntitlementRequestForUserRequest) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type AddEntitlementRequestForUserResponse struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	EntitlementID        string   `protobuf:"bytes,2,opt,name=EntitlementID,json=entitlement_id,proto3" json:"EntitlementID,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=RoleName,json=role_name,proto3" json:"RoleName,omitempty"`
	BankID               string   `protobuf:"bytes,4,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEntitlementRequestForUserResponse) Reset()         { *m = AddEntitlementRequestForUserResponse{} }
func (m *AddEntitlementRequestForUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddEntitlementRequestForUserResponse) ProtoMessage()    {}
func (*AddEntitlementRequestForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{7}
}

func (m *AddEntitlementRequestForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEntitlementRequestForUserResponse.Unmarshal(m, b)
}
func (m *AddEntitlementRequestForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEntitlementRequestForUserResponse.Marshal(b, m, deterministic)
}
func (m *AddEntitlementRequestForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEntitlementRequestForUserResponse.Merge(m, src)
}
func (m *AddEntitlementRequestForUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddEntitlementRequestForUserResponse.Size(m)
}
func (m *AddEntitlementRequestForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEntitlementRequestForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddEntitlementRequestForUserResponse proto.InternalMessageInfo

func (m *AddEntitlementRequestForUserResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddEntitlementRequestForUserResponse) GetEntitlementID() string {
	if m != nil {
		return m.EntitlementID
	}
	return ""
}

func (m *AddEntitlementRequestForUserResponse) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *AddEntitlementRequestForUserResponse) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

type DeleteEntitlementRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	EntitlementID        string   `protobuf:"bytes,2,opt,name=EntitlementID,json=entitlement_id,proto3" json:"EntitlementID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntitlementRequest) Reset()         { *m = DeleteEntitlementRequest{} }
func (m *DeleteEntitlementRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEntitlementRequest) ProtoMessage()    {}
func (*DeleteEntitlementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{8}
}

func (m *DeleteEntitlementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntitlementRequest.Unmarshal(m, b)
}
func (m *DeleteEntitlementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntitlementRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEntitlementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntitlementRequest.Merge(m, src)
}
func (m *DeleteEntitlementRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEntitlementRequest.Size(m)
}
func (m *DeleteEntitlementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntitlementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntitlementRequest proto.InternalMessageInfo

func (m *DeleteEntitlementRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeleteEntitlementRequest) GetEntitlementID() string {
	if m != nil {
		return m.EntitlementID
	}
	return ""
}

type DeleteEntitlementRequestRequest struct {
	EntitlementRequestID string   `protobuf:"bytes,1,opt,name=EntitlementRequestID,json=entitlement_request_id,proto3" json:"EntitlementRequestID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntitlementRequestRequest) Reset()         { *m = DeleteEntitlementRequestRequest{} }
func (m *DeleteEntitlementRequestRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEntitlementRequestRequest) ProtoMessage()    {}
func (*DeleteEntitlementRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{9}
}

func (m *DeleteEntitlementRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntitlementRequestRequest.Unmarshal(m, b)
}
func (m *DeleteEntitlementRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntitlementRequestRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEntitlementRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntitlementRequestRequest.Merge(m, src)
}
func (m *DeleteEntitlementRequestRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEntitlementRequestRequest.Size(m)
}
func (m *DeleteEntitlementRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntitlementRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntitlementRequestRequest proto.InternalMessageInfo

func (m *DeleteEntitlementRequestRequest) GetEntitlementRequestID() string {
	if m != nil {
		return m.EntitlementRequestID
	}
	return ""
}

type GetEntitlementRequestForUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntitlementRequestForUserRequest) Reset()         { *m = GetEntitlementRequestForUserRequest{} }
func (m *GetEntitlementRequestForUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntitlementRequestForUserRequest) ProtoMessage()    {}
func (*GetEntitlementRequestForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{10}
}

func (m *GetEntitlementRequestForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitlementRequestForUserRequest.Unmarshal(m, b)
}
func (m *GetEntitlementRequestForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitlementRequestForUserRequest.Marshal(b, m, deterministic)
}
func (m *GetEntitlementRequestForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitlementRequestForUserRequest.Merge(m, src)
}
func (m *GetEntitlementRequestForUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntitlementRequestForUserRequest.Size(m)
}
func (m *GetEntitlementRequestForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitlementRequestForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitlementRequestForUserRequest proto.InternalMessageInfo

func (m *GetEntitlementRequestForUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetEntitlementRequestForUserResponse struct {
	EntitlementRequests  []*EntitlementRequest `protobuf:"bytes,1,rep,name=EntitlementRequests,json=entitlement_requests,proto3" json:"EntitlementRequests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetEntitlementRequestForUserResponse) Reset()         { *m = GetEntitlementRequestForUserResponse{} }
func (m *GetEntitlementRequestForUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntitlementRequestForUserResponse) ProtoMessage()    {}
func (*GetEntitlementRequestForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{11}
}

func (m *GetEntitlementRequestForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitlementRequestForUserResponse.Unmarshal(m, b)
}
func (m *GetEntitlementRequestForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitlementRequestForUserResponse.Marshal(b, m, deterministic)
}
func (m *GetEntitlementRequestForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitlementRequestForUserResponse.Merge(m, src)
}
func (m *GetEntitlementRequestForUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntitlementRequestForUserResponse.Size(m)
}
func (m *GetEntitlementRequestForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitlementRequestForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitlementRequestForUserResponse proto.InternalMessageInfo

func (m *GetEntitlementRequestForUserResponse) GetEntitlementRequests() []*EntitlementRequest {
	if m != nil {
		return m.EntitlementRequests
	}
	return nil
}

type GetEntitlementRequestForCurrentUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntitlementRequestForCurrentUserRequest) Reset() {
	*m = GetEntitlementRequestForCurrentUserRequest{}
}
func (m *GetEntitlementRequestForCurrentUserRequest) String() string {
	return proto.CompactTextString(m)
}
func (*GetEntitlementRequestForCurrentUserRequest) ProtoMessage() {}
func (*GetEntitlementRequestForCurrentUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{12}
}

func (m *GetEntitlementRequestForCurrentUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitlementRequestForCurrentUserRequest.Unmarshal(m, b)
}
func (m *GetEntitlementRequestForCurrentUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitlementRequestForCurrentUserRequest.Marshal(b, m, deterministic)
}
func (m *GetEntitlementRequestForCurrentUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitlementRequestForCurrentUserRequest.Merge(m, src)
}
func (m *GetEntitlementRequestForCurrentUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntitlementRequestForCurrentUserRequest.Size(m)
}
func (m *GetEntitlementRequestForCurrentUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitlementRequestForCurrentUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitlementRequestForCurrentUserRequest proto.InternalMessageInfo

type GetEntitlementRequestForCurrentUserResponse struct {
	EntitlementRequests  []*EntitlementRequest `protobuf:"bytes,1,rep,name=EntitlementRequests,json=entitlement_requests,proto3" json:"EntitlementRequests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetEntitlementRequestForCurrentUserResponse) Reset() {
	*m = GetEntitlementRequestForCurrentUserResponse{}
}
func (m *GetEntitlementRequestForCurrentUserResponse) String() string {
	return proto.CompactTextString(m)
}
func (*GetEntitlementRequestForCurrentUserResponse) ProtoMessage() {}
func (*GetEntitlementRequestForCurrentUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{13}
}

func (m *GetEntitlementRequestForCurrentUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitlementRequestForCurrentUserResponse.Unmarshal(m, b)
}
func (m *GetEntitlementRequestForCurrentUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitlementRequestForCurrentUserResponse.Marshal(b, m, deterministic)
}
func (m *GetEntitlementRequestForCurrentUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitlementRequestForCurrentUserResponse.Merge(m, src)
}
func (m *GetEntitlementRequestForCurrentUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntitlementRequestForCurrentUserResponse.Size(m)
}
func (m *GetEntitlementRequestForCurrentUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitlementRequestForCurrentUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitlementRequestForCurrentUserResponse proto.InternalMessageInfo

func (m *GetEntitlementRequestForCurrentUserResponse) GetEntitlementRequests() []*EntitlementRequest {
	if m != nil {
		return m.EntitlementRequests
	}
	return nil
}

type GetEntitlementForUserAtBankRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntitlementForUserAtBankRequest) Reset()         { *m = GetEntitlementForUserAtBankRequest{} }
func (m *GetEntitlementForUserAtBankRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntitlementForUserAtBankRequest) ProtoMessage()    {}
func (*GetEntitlementForUserAtBankRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{14}
}

func (m *GetEntitlementForUserAtBankRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitlementForUserAtBankRequest.Unmarshal(m, b)
}
func (m *GetEntitlementForUserAtBankRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitlementForUserAtBankRequest.Marshal(b, m, deterministic)
}
func (m *GetEntitlementForUserAtBankRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitlementForUserAtBankRequest.Merge(m, src)
}
func (m *GetEntitlementForUserAtBankRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntitlementForUserAtBankRequest.Size(m)
}
func (m *GetEntitlementForUserAtBankRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitlementForUserAtBankRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitlementForUserAtBankRequest proto.InternalMessageInfo

func (m *GetEntitlementForUserAtBankRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *GetEntitlementForUserAtBankRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetEntitlementForUserRequest struct {
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntitlementForUserRequest) Reset()         { *m = GetEntitlementForUserRequest{} }
func (m *GetEntitlementForUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntitlementForUserRequest) ProtoMessage()    {}
func (*GetEntitlementForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{15}
}

func (m *GetEntitlementForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitlementForUserRequest.Unmarshal(m, b)
}
func (m *GetEntitlementForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitlementForUserRequest.Marshal(b, m, deterministic)
}
func (m *GetEntitlementForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitlementForUserRequest.Merge(m, src)
}
func (m *GetEntitlementForUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntitlementForUserRequest.Size(m)
}
func (m *GetEntitlementForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitlementForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitlementForUserRequest proto.InternalMessageInfo

func (m *GetEntitlementForUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetEntitlementForCurrentUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntitlementForCurrentUserRequest) Reset()         { *m = GetEntitlementForCurrentUserRequest{} }
func (m *GetEntitlementForCurrentUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntitlementForCurrentUserRequest) ProtoMessage()    {}
func (*GetEntitlementForCurrentUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{16}
}

func (m *GetEntitlementForCurrentUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntitlementForCurrentUserRequest.Unmarshal(m, b)
}
func (m *GetEntitlementForCurrentUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntitlementForCurrentUserRequest.Marshal(b, m, deterministic)
}
func (m *GetEntitlementForCurrentUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntitlementForCurrentUserRequest.Merge(m, src)
}
func (m *GetEntitlementForCurrentUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntitlementForCurrentUserRequest.Size(m)
}
func (m *GetEntitlementForCurrentUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntitlementForCurrentUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntitlementForCurrentUserRequest proto.InternalMessageInfo

type GetAllEntitlementsRequest struct {
	NextStartingIndex    int32    `protobuf:"varint,1,opt,name=NextStartingIndex,json=next_starting_index,proto3" json:"NextStartingIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllEntitlementsRequest) Reset()         { *m = GetAllEntitlementsRequest{} }
func (m *GetAllEntitlementsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllEntitlementsRequest) ProtoMessage()    {}
func (*GetAllEntitlementsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{17}
}

func (m *GetAllEntitlementsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllEntitlementsRequest.Unmarshal(m, b)
}
func (m *GetAllEntitlementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllEntitlementsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllEntitlementsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllEntitlementsRequest.Merge(m, src)
}
func (m *GetAllEntitlementsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllEntitlementsRequest.Size(m)
}
func (m *GetAllEntitlementsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllEntitlementsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllEntitlementsRequest proto.InternalMessageInfo

func (m *GetAllEntitlementsRequest) GetNextStartingIndex() int32 {
	if m != nil {
		return m.NextStartingIndex
	}
	return 0
}

type GetAllEntitlementRequestRequest struct {
	NextStartingIndex    int32    `protobuf:"varint,1,opt,name=NextStartingIndex,json=next_starting_index,proto3" json:"NextStartingIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllEntitlementRequestRequest) Reset()         { *m = GetAllEntitlementRequestRequest{} }
func (m *GetAllEntitlementRequestRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllEntitlementRequestRequest) ProtoMessage()    {}
func (*GetAllEntitlementRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{18}
}

func (m *GetAllEntitlementRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllEntitlementRequestRequest.Unmarshal(m, b)
}
func (m *GetAllEntitlementRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllEntitlementRequestRequest.Marshal(b, m, deterministic)
}
func (m *GetAllEntitlementRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllEntitlementRequestRequest.Merge(m, src)
}
func (m *GetAllEntitlementRequestRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllEntitlementRequestRequest.Size(m)
}
func (m *GetAllEntitlementRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllEntitlementRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllEntitlementRequestRequest proto.InternalMessageInfo

func (m *GetAllEntitlementRequestRequest) GetNextStartingIndex() int32 {
	if m != nil {
		return m.NextStartingIndex
	}
	return 0
}

type GetRolesResponse struct {
	Roles                []*Roles `protobuf:"bytes,1,rep,name=Roles,json=roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesResponse) Reset()         { *m = GetRolesResponse{} }
func (m *GetRolesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesResponse) ProtoMessage()    {}
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{19}
}

func (m *GetRolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesResponse.Unmarshal(m, b)
}
func (m *GetRolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesResponse.Marshal(b, m, deterministic)
}
func (m *GetRolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesResponse.Merge(m, src)
}
func (m *GetRolesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesResponse.Size(m)
}
func (m *GetRolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesResponse proto.InternalMessageInfo

func (m *GetRolesResponse) GetRoles() []*Roles {
	if m != nil {
		return m.Roles
	}
	return nil
}

type Roles struct {
	Role                 string   `protobuf:"bytes,1,opt,name=Role,json=role,proto3" json:"Role,omitempty"`
	RequiresBankID       bool     `protobuf:"varint,2,opt,name=RequiresBankID,json=requires_bank_id,proto3" json:"RequiresBankID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Roles) Reset()         { *m = Roles{} }
func (m *Roles) String() string { return proto.CompactTextString(m) }
func (*Roles) ProtoMessage()    {}
func (*Roles) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{20}
}

func (m *Roles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Roles.Unmarshal(m, b)
}
func (m *Roles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Roles.Marshal(b, m, deterministic)
}
func (m *Roles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Roles.Merge(m, src)
}
func (m *Roles) XXX_Size() int {
	return xxx_messageInfo_Roles.Size(m)
}
func (m *Roles) XXX_DiscardUnknown() {
	xxx_messageInfo_Roles.DiscardUnknown(m)
}

var xxx_messageInfo_Roles proto.InternalMessageInfo

func (m *Roles) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Roles) GetRequiresBankID() bool {
	if m != nil {
		return m.RequiresBankID
	}
	return false
}

type GetRolesRequest struct {
	NextStartingIndex    int32    `protobuf:"varint,1,opt,name=NextStartingIndex,json=next_starting_index,proto3" json:"NextStartingIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesRequest) Reset()         { *m = GetRolesRequest{} }
func (m *GetRolesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRolesRequest) ProtoMessage()    {}
func (*GetRolesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f4165e77126d0f, []int{21}
}

func (m *GetRolesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesRequest.Unmarshal(m, b)
}
func (m *GetRolesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesRequest.Marshal(b, m, deterministic)
}
func (m *GetRolesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesRequest.Merge(m, src)
}
func (m *GetRolesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRolesRequest.Size(m)
}
func (m *GetRolesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesRequest proto.InternalMessageInfo

func (m *GetRolesRequest) GetNextStartingIndex() int32 {
	if m != nil {
		return m.NextStartingIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*AddEntitlementRequestForCurrentUserRequest)(nil), "entitlement.AddEntitlementRequestForCurrentUserRequest")
	proto.RegisterType((*EntitlementRequest)(nil), "entitlement.EntitlementRequest")
	proto.RegisterType((*EntitlementRequests)(nil), "entitlement.EntitlementRequests")
	proto.RegisterType((*List)(nil), "entitlement.List")
	proto.RegisterType((*Entitlements)(nil), "entitlement.Entitlements")
	proto.RegisterType((*User)(nil), "entitlement.User")
	proto.RegisterType((*AddEntitlementRequestForUserRequest)(nil), "entitlement.AddEntitlementRequestForUserRequest")
	proto.RegisterType((*AddEntitlementRequestForUserResponse)(nil), "entitlement.AddEntitlementRequestForUserResponse")
	proto.RegisterType((*DeleteEntitlementRequest)(nil), "entitlement.DeleteEntitlementRequest")
	proto.RegisterType((*DeleteEntitlementRequestRequest)(nil), "entitlement.DeleteEntitlementRequestRequest")
	proto.RegisterType((*GetEntitlementRequestForUserRequest)(nil), "entitlement.GetEntitlementRequestForUserRequest")
	proto.RegisterType((*GetEntitlementRequestForUserResponse)(nil), "entitlement.GetEntitlementRequestForUserResponse")
	proto.RegisterType((*GetEntitlementRequestForCurrentUserRequest)(nil), "entitlement.GetEntitlementRequestForCurrentUserRequest")
	proto.RegisterType((*GetEntitlementRequestForCurrentUserResponse)(nil), "entitlement.GetEntitlementRequestForCurrentUserResponse")
	proto.RegisterType((*GetEntitlementForUserAtBankRequest)(nil), "entitlement.GetEntitlementForUserAtBankRequest")
	proto.RegisterType((*GetEntitlementForUserRequest)(nil), "entitlement.GetEntitlementForUserRequest")
	proto.RegisterType((*GetEntitlementForCurrentUserRequest)(nil), "entitlement.GetEntitlementForCurrentUserRequest")
	proto.RegisterType((*GetAllEntitlementsRequest)(nil), "entitlement.GetAllEntitlementsRequest")
	proto.RegisterType((*GetAllEntitlementRequestRequest)(nil), "entitlement.GetAllEntitlementRequestRequest")
	proto.RegisterType((*GetRolesResponse)(nil), "entitlement.GetRolesResponse")
	proto.RegisterType((*Roles)(nil), "entitlement.Roles")
	proto.RegisterType((*GetRolesRequest)(nil), "entitlement.GetRolesRequest")
}

func init() {
	proto.RegisterFile("github.com/openbank/openbank/v1/entitlement/all.proto", fileDescriptor_59f4165e77126d0f)
}

var fileDescriptor_59f4165e77126d0f = []byte{
	// 2135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x5a, 0x4d, 0x6c, 0xdc, 0xc6,
	0xf5, 0x5f, 0x72, 0x25, 0x59, 0x1e, 0xe5, 0x9f, 0xc8, 0xe3, 0x24, 0x50, 0x18, 0xc5, 0x9a, 0xac,
	0x1c, 0x5b, 0x1f, 0x16, 0x77, 0xb5, 0x51, 0xf0, 0x2f, 0x04, 0x04, 0x09, 0x2d, 0xc9, 0x8a, 0x64,
	0x37, 0x11, 0x36, 0x76, 0xd0, 0xe6, 0x10, 0x85, 0x4b, 0x8e, 0x56, 0xb4, 0xb9, 0x1c, 0x66, 0x66,
	0x56, 0x92, 0x63, 0x18, 0x28, 0x02, 0x14, 0x70, 0x2f, 0xb5, 0xbb, 0x41, 0x93, 0x53, 0x01, 0x1b,
	0xe8, 0xa9, 0xd7, 0x1e, 0xda, 0x63, 0x7a, 0x69, 0x81, 0x9e, 0x0a, 0xb4, 0x40, 0x7b, 0xc9, 0xa1,
	0x68, 0x0f, 0x05, 0x9a, 0x83, 0x81, 0x16, 0x68, 0xd0, 0x53, 0x31, 0x24, 0x97, 0xcb, 0xcf, 0xfd,
	0x70, 0x14, 0xc3, 0x27, 0xc9, 0x9c, 0x37, 0xef, 0xbd, 0xf9, 0xfd, 0x7e, 0xef, 0xcd, 0x87, 0x0c,
	0x5e, 0x6b, 0x58, 0x7c, 0xbf, 0x55, 0x57, 0x0d, 0xd2, 0x2c, 0x13, 0x17, 0x3b, 0x75, 0xdd, 0xb9,
	0xd1, 0xfd, 0xe5, 0x60, 0xb9, 0x8c, 0x1d, 0x6e, 0x71, 0x1b, 0x37, 0xb1, 0xc3, 0xcb, 0xba, 0x6d,
	0xab, 0x2e, 0x25, 0x9c, 0xc0, 0x89, 0xc8, 0x67, 0x65, 0xa6, 0x41, 0x48, 0xc3, 0xc6, 0x65, 0x6f,
	0xa8, 0xde, 0xda, 0x2b, 0x73, 0xab, 0x89, 0x19, 0xd7, 0x9b, 0xae, 0x6f, 0xad, 0x4c, 0x07, 0x06,
	0xba, 0x6b, 0x95, 0x75, 0xc7, 0x21, 0x5c, 0xe7, 0x16, 0x71, 0x58, 0x30, 0x7a, 0xc1, 0xfb, 0x61,
	0x2c, 0x35, 0xb0, 0xb3, 0xc4, 0x0e, 0xf5, 0x46, 0x03, 0xd3, 0x32, 0x71, 0x3d, 0x8b, 0x0c, 0xeb,
	0x17, 0x93, 0xc1, 0x70, 0xd3, 0xe5, 0x37, 0xfd, 0xc1, 0xd2, 0x27, 0x12, 0x58, 0xd0, 0x4c, 0x73,
	0xa3, 0x9b, 0x5c, 0x0d, 0x7f, 0xd4, 0xc2, 0x8c, 0x5f, 0x22, 0x74, 0xad, 0x45, 0x29, 0x76, 0xf8,
	0x35, 0x86, 0x69, 0xf0, 0x11, 0xce, 0x82, 0xb1, 0x8b, 0xba, 0x73, 0x63, 0x6b, 0x7d, 0x4a, 0x42,
	0xd2, 0xdc, 0xc9, 0x8b, 0x60, 0xbc, 0x30, 0x55, 0x98, 0x2b, 0x54, 0x0a, 0x3b, 0x85, 0xda, 0x09,
	0x01, 0xc0, 0xae, 0x65, 0xc2, 0xf3, 0x60, 0xbc, 0x46, 0x6c, 0xfc, 0xb6, 0xde, 0xc4, 0x53, 0x72,
	0xca, 0xec, 0x24, 0x25, 0x36, 0xde, 0x75, 0xf4, 0x26, 0x5e, 0x1d, 0x1b, 0x2f, 0x4c, 0x16, 0xa6,
	0x0a, 0xa5, 0x07, 0x32, 0x80, 0xe9, 0x0c, 0xe0, 0x9b, 0xe0, 0xd9, 0xf4, 0xd7, 0xcc, 0xd0, 0xcf,
	0x47, 0xc0, 0xdd, 0xa5, 0xbe, 0xa1, 0xc8, 0x64, 0x19, 0x8c, 0x88, 0xec, 0xbd, 0x2c, 0x26, 0xaa,
	0xa7, 0xd4, 0x88, 0x99, 0x2a, 0x06, 0x62, 0x4e, 0x46, 0x5a, 0x0c, 0xd3, 0x58, 0xf2, 0xc5, 0x1e,
	0xc9, 0x47, 0xa0, 0x18, 0xc9, 0x87, 0xe2, 0x4d, 0x70, 0x62, 0x8d, 0x62, 0x9d, 0x63, 0x73, 0x6a,
	0xd4, 0xcb, 0x41, 0x51, 0x7d, 0x36, 0xd4, 0x0e, 0x1b, 0xea, 0xd5, 0x0e, 0xf5, 0x71, 0x0f, 0x86,
	0x3f, 0x2d, 0xc4, 0xe8, 0x36, 0x38, 0x9d, 0x06, 0x83, 0xc1, 0x0f, 0x32, 0x3f, 0x4f, 0x49, 0xa8,
	0x38, 0x37, 0x51, 0x9d, 0x89, 0x2d, 0x38, 0x6d, 0x17, 0x8b, 0xf8, 0x6c, 0x06, 0x86, 0x2c, 0x0c,
	0x7f, 0x57, 0x02, 0x23, 0x57, 0x2c, 0xc6, 0xe1, 0x32, 0xf8, 0xbf, 0x88, 0xa3, 0x4c, 0x36, 0x9e,
	0x8e, 0x7a, 0x1a, 0x42, 0x0f, 0x11, 0x48, 0x8b, 0xb9, 0x90, 0x86, 0x19, 0x6d, 0x81, 0xa7, 0x22,
	0x89, 0x30, 0xc1, 0xb5, 0x48, 0x30, 0x58, 0x7a, 0x9c, 0x6b, 0x31, 0x10, 0xe7, 0xda, 0xb6, 0x18,
	0x0f, 0x5d, 0xfd, 0x4c, 0xf6, 0x75, 0x22, 0x12, 0x10, 0x3f, 0xb3, 0xe5, 0x2d, 0xe4, 0x21, 0x96,
	0x83, 0xc0, 0xe8, 0x46, 0x53, 0xb7, 0xec, 0x8c, 0xb5, 0x8c, 0x62, 0x31, 0x00, 0x17, 0x01, 0xd8,
	0xa1, 0xe4, 0xc0, 0x32, 0x3d, 0x57, 0xe9, 0xb5, 0x4c, 0xb8, 0xc1, 0xa8, 0x70, 0x77, 0x0e, 0x8c,
	0x77, 0x8c, 0x33, 0x94, 0x34, 0xde, 0x31, 0x15, 0x76, 0x22, 0x37, 0x01, 0x94, 0xa7, 0xa5, 0x84,
	0x5d, 0x2b, 0x18, 0x83, 0x09, 0x5c, 0xa6, 0xc6, 0x3c, 0xdd, 0xbd, 0x90, 0x27, 0x05, 0x16, 0x73,
	0xf3, 0x54, 0xc4, 0xaa, 0x4b, 0xfe, 0x7d, 0x09, 0xcc, 0xe6, 0x35, 0x89, 0x44, 0x77, 0xe8, 0x0f,
	0x5f, 0x97, 0x64, 0x79, 0xb0, 0x16, 0x52, 0x1c, 0xa4, 0x85, 0xfc, 0x49, 0x02, 0x67, 0x7b, 0xa7,
	0xc8, 0x5c, 0xe2, 0x30, 0x3c, 0x58, 0x8e, 0x29, 0x91, 0xcb, 0x43, 0x89, 0xfc, 0x1b, 0xf7, 0x8d,
	0x70, 0x59, 0x1f, 0x83, 0xa9, 0x75, 0x6c, 0x63, 0x8e, 0x33, 0xda, 0xe3, 0xb7, 0xb4, 0x92, 0x30,
	0xf6, 0x0d, 0x30, 0x93, 0x17, 0xfb, 0xd8, 0x3a, 0x74, 0x18, 0xac, 0x06, 0x66, 0x37, 0x31, 0x3f,
	0x16, 0x85, 0x85, 0x3e, 0x7f, 0x2c, 0x81, 0xb3, 0xbd, 0x9d, 0x06, 0x9a, 0x78, 0x5c, 0x4d, 0x74,
	0x05, 0x2c, 0xe4, 0xe5, 0x93, 0xde, 0x6b, 0xc3, 0x59, 0x3f, 0x95, 0xc0, 0xe2, 0x40, 0xd3, 0x1e,
	0xf3, 0x6a, 0x0e, 0x40, 0x29, 0x9e, 0x56, 0x00, 0xab, 0xc6, 0x85, 0xbe, 0x87, 0x3a, 0x31, 0x74,
	0x69, 0x95, 0xfb, 0xd3, 0x7a, 0x19, 0x4c, 0x67, 0xc6, 0x4d, 0x6b, 0x64, 0x00, 0x67, 0x4b, 0x49,
	0xdd, 0xf5, 0xe6, 0x62, 0x17, 0xbc, 0xb0, 0x89, 0xb9, 0x66, 0xdb, 0xd1, 0x0e, 0xda, 0x09, 0xbc,
	0x0a, 0x4e, 0xbd, 0x8d, 0x8f, 0xf8, 0xbb, 0x5c, 0xa7, 0xdc, 0x72, 0x1a, 0x5b, 0x8e, 0x89, 0x8f,
	0xbc, 0x55, 0x8f, 0xc6, 0x72, 0x38, 0xed, 0xe0, 0x23, 0xbe, 0xcb, 0x02, 0xab, 0x5d, 0x4b, 0x98,
	0x85, 0x01, 0x30, 0x98, 0x49, 0x05, 0x48, 0x14, 0xdd, 0x71, 0x84, 0xd9, 0x01, 0x93, 0x9b, 0x98,
	0x8b, 0x86, 0xc5, 0x42, 0xdd, 0xac, 0x80, 0x51, 0xef, 0x43, 0xa0, 0x14, 0x18, 0x53, 0x8a, 0x37,
	0x12, 0xdf, 0xeb, 0x44, 0x4b, 0x63, 0x91, 0xc4, 0xfd, 0xd9, 0xf0, 0x0c, 0x18, 0x11, 0xbf, 0x64,
	0xd0, 0x3d, 0x22, 0x66, 0xc0, 0x15, 0xf0, 0xb4, 0x58, 0x89, 0x45, 0x31, 0x8b, 0xec, 0x03, 0xe3,
	0x31, 0xcb, 0x49, 0x1a, 0x58, 0xec, 0x26, 0x1b, 0xe2, 0x35, 0xf0, 0x4c, 0x37, 0xf1, 0x63, 0xc3,
	0xa3, 0xfa, 0xaf, 0x73, 0xb1, 0x13, 0xe8, 0xbb, 0x98, 0x1e, 0x58, 0x06, 0x86, 0x9f, 0x15, 0xf3,
	0x37, 0xbe, 0x88, 0x4a, 0xe0, 0xff, 0xc7, 0xb0, 0x1a, 0xfc, 0x3c, 0xad, 0xf4, 0x2b, 0xc7, 0xd2,
	0x3d, 0xb9, 0xad, 0xfd, 0x4d, 0x02, 0x13, 0x91, 0x21, 0xb8, 0xa8, 0x99, 0x26, 0xd2, 0x1d, 0x14,
	0x99, 0x8a, 0x82, 0xea, 0x44, 0x7b, 0x84, 0x22, 0xc3, 0x8f, 0x83, 0x84, 0xd6, 0x95, 0x61, 0x8c,
	0xb7, 0x31, 0x28, 0x56, 0x2b, 0xcb, 0xf0, 0x03, 0x30, 0xcc, 0x2c, 0x58, 0x06, 0x4b, 0xca, 0xe2,
	0x6c, 0xd9, 0xc4, 0x7b, 0x96, 0x63, 0xf9, 0xb7, 0x90, 0xc8, 0xbc, 0xf4, 0xa2, 0xea, 0xa7, 0xc1,
	0x29, 0x30, 0xf6, 0x8e, 0xd6, 0xe2, 0xfb, 0x55, 0x78, 0x02, 0x8c, 0x1e, 0x52, 0x8b, 0xe3, 0x4f,
	0xfe, 0xf8, 0xf7, 0x4f, 0xe5, 0x97, 0x56, 0xa5, 0x85, 0xd2, 0x54, 0xe2, 0x12, 0xb5, 0xd4, 0xe9,
	0x3c, 0x77, 0xe4, 0xc2, 0x3d, 0xd9, 0xa3, 0x13, 0xfe, 0xa2, 0x08, 0xa6, 0x7b, 0x6d, 0xf7, 0xb0,
	0x32, 0x10, 0x23, 0x51, 0x2a, 0x96, 0x87, 0x98, 0xe1, 0x57, 0x4c, 0xe9, 0xbe, 0xdc, 0xd6, 0xbe,
	0x4a, 0x90, 0x23, 0x4e, 0x21, 0x88, 0xef, 0xe3, 0x5c, 0xe8, 0x3c, 0x56, 0x2a, 0x59, 0x56, 0xbd,
	0x66, 0x6c, 0xbb, 0x3e, 0x35, 0x16, 0x18, 0x28, 0x00, 0xd4, 0xc0, 0x1b, 0xca, 0xeb, 0xb9, 0x9c,
	0x0c, 0xb2, 0xba, 0x7c, 0x96, 0xce, 0x0a, 0x96, 0x66, 0x04, 0x4b, 0x22, 0x14, 0x2b, 0xdf, 0xf2,
	0xdb, 0xed, 0xed, 0x68, 0x84, 0x28, 0x59, 0x0f, 0x64, 0x70, 0x2a, 0x75, 0x92, 0x80, 0xaf, 0xc4,
	0xf0, 0xce, 0x3b, 0x69, 0x28, 0xcf, 0xa7, 0x2e, 0x4c, 0x1b, 0xe2, 0xfa, 0x5a, 0xfa, 0xbd, 0xd4,
	0xd6, 0x7e, 0x94, 0xc0, 0xfe, 0x39, 0xdf, 0x4b, 0x42, 0xb8, 0x4a, 0x69, 0x07, 0xd3, 0xa6, 0xee,
	0x60, 0x87, 0xdb, 0x37, 0x91, 0x99, 0x65, 0xa2, 0x6e, 0x2f, 0x08, 0x78, 0x57, 0xe0, 0x2c, 0x78,
	0x39, 0xe2, 0x10, 0xb1, 0x96, 0x61, 0x60, 0xc6, 0xf6, 0x5a, 0x76, 0x38, 0xd3, 0x54, 0xf3, 0x81,
	0x59, 0x5e, 0x28, 0xf7, 0x41, 0xa5, 0x7c, 0x2b, 0x76, 0x1a, 0xbb, 0xdd, 0x41, 0x09, 0xfe, 0x56,
	0xee, 0x71, 0xd2, 0xbb, 0x30, 0x10, 0x54, 0xfd, 0x10, 0xfb, 0xab, 0xd4, 0xd6, 0xee, 0x27, 0x10,
	0x9b, 0xee, 0x20, 0x96, 0xa5, 0x26, 0x65, 0xa1, 0x2f, 0x70, 0x1d, 0x53, 0x75, 0xbb, 0xea, 0x03,
	0xb8, 0x08, 0xe6, 0x37, 0x32, 0x74, 0xf9, 0x68, 0x40, 0x66, 0x35, 0x81, 0x18, 0x82, 0xe1, 0x89,
	0xb3, 0x0b, 0xe4, 0x7f, 0x8b, 0xc9, 0xe3, 0x41, 0xcf, 0xce, 0x30, 0xc0, 0xa1, 0x33, 0xd1, 0x19,
	0x06, 0x39, 0x51, 0x96, 0x1e, 0xca, 0x6d, 0xed, 0x57, 0x72, 0x1c, 0xeb, 0xb9, 0x1a, 0xe6, 0xd4,
	0xc2, 0x07, 0xd9, 0x95, 0x6b, 0x39, 0x7b, 0x84, 0x36, 0xbd, 0x87, 0x1b, 0xe5, 0x72, 0x68, 0x19,
	0xf9, 0x8a, 0xf4, 0x3a, 0x69, 0xf1, 0xdc, 0xca, 0x67, 0x2e, 0x36, 0xac, 0x3d, 0x0b, 0x9b, 0xa8,
	0x7e, 0xd3, 0x33, 0x12, 0xf9, 0xa0, 0xad, 0xf5, 0xed, 0xeb, 0x82, 0x98, 0x0a, 0x34, 0xc0, 0x99,
	0x20, 0x57, 0x84, 0x8f, 0xb0, 0xd1, 0xe2, 0xd8, 0x8c, 0xb1, 0xa2, 0xf6, 0x69, 0x19, 0x83, 0x2c,
	0x7b, 0x7b, 0x19, 0x14, 0x57, 0x2a, 0x2b, 0x70, 0x01, 0x88, 0xb5, 0xb6, 0xa8, 0x83, 0x4d, 0x74,
	0xb8, 0x8f, 0x1d, 0x2f, 0x1f, 0x8a, 0x19, 0x69, 0x51, 0x03, 0x23, 0x8b, 0x21, 0x87, 0x88, 0x56,
	0xd5, 0x72, 0x4c, 0xb5, 0x0e, 0xc1, 0x64, 0xa8, 0x81, 0x31, 0x30, 0x42, 0xb1, 0x6e, 0x7a, 0x12,
	0x98, 0x87, 0xe7, 0x7b, 0xd7, 0x52, 0xd6, 0xb6, 0xf0, 0xf9, 0x48, 0xfe, 0x35, 0x22, 0x7f, 0xbf,
	0x1e, 0xfc, 0x4c, 0xae, 0x7c, 0x67, 0xf8, 0x89, 0x81, 0x22, 0xbe, 0x96, 0xdb, 0xda, 0x17, 0x8f,
	0xac, 0x88, 0xef, 0x7e, 0x23, 0x45, 0xa4, 0xf6, 0xf9, 0x8f, 0x7c, 0x4d, 0x5c, 0xef, 0xab, 0x89,
	0xb7, 0xc0, 0x25, 0x65, 0x7d, 0x68, 0x4d, 0x64, 0xac, 0xff, 0x38, 0xa5, 0x31, 0x07, 0xcf, 0x75,
	0xa5, 0x11, 0xac, 0xab, 0x9f, 0x32, 0x7e, 0x5e, 0x04, 0xcf, 0x65, 0xde, 0x1a, 0xe0, 0x7c, 0x0f,
	0x4a, 0x13, 0x8d, 0x20, 0xff, 0x11, 0xa5, 0xf4, 0x85, 0xdc, 0xd6, 0xee, 0x26, 0xe8, 0x45, 0x99,
	0xf4, 0x46, 0x69, 0x5d, 0x1b, 0x82, 0xd6, 0xdc, 0x02, 0x1f, 0x1e, 0xd9, 0xed, 0x9a, 0xcf, 0xff,
	0xe5, 0xbe, 0xfc, 0xcf, 0x83, 0xf3, 0xca, 0x2b, 0x83, 0x1c, 0xed, 0x58, 0x2e, 0x5b, 0x2f, 0xc3,
	0x21, 0x8e, 0x0a, 0xbf, 0x2c, 0x66, 0x5c, 0xee, 0xa2, 0x95, 0x5b, 0xe9, 0xcd, 0x56, 0x46, 0xc9,
	0xf6, 0x20, 0xed, 0x37, 0x72, 0x5b, 0xfb, 0xc9, 0xd0, 0xa4, 0x6d, 0x3c, 0x12, 0x69, 0xa9, 0x1a,
	0xfc, 0x16, 0x38, 0x38, 0xce, 0x22, 0x43, 0xf0, 0x4c, 0xcf, 0x22, 0x8b, 0xb2, 0xf6, 0xbb, 0x22,
	0x78, 0xb1, 0xc7, 0x53, 0x00, 0x2c, 0xf7, 0x2f, 0xb1, 0xd8, 0xa3, 0x41, 0x2f, 0xce, 0xfe, 0x2c,
	0xb7, 0xb5, 0xcf, 0x87, 0xe6, 0xec, 0xf2, 0x31, 0x14, 0x1a, 0xd2, 0x39, 0x12, 0xd7, 0xd1, 0x27,
	0xbd, 0xe0, 0x2a, 0x50, 0x15, 0xcc, 0x89, 0x54, 0x59, 0xf9, 0x96, 0x7f, 0xc7, 0xbe, 0x3d, 0x60,
	0xfd, 0x7d, 0x5a, 0xcc, 0x78, 0xe0, 0x08, 0xff, 0xd8, 0x70, 0x21, 0xc9, 0x63, 0xaf, 0x77, 0x0a,
	0x05, 0xf5, 0xb9, 0xdb, 0xb2, 0xd2, 0x03, 0xb9, 0xad, 0xfd, 0x27, 0x79, 0x86, 0xbf, 0x62, 0x31,
	0x8e, 0x74, 0xdb, 0x8e, 0x72, 0xc2, 0x94, 0xba, 0x0f, 0x35, 0x43, 0x3a, 0xb2, 0x85, 0x81, 0x41,
	0x1c, 0xae, 0x5b, 0x8e, 0xe5, 0x34, 0x50, 0xcb, 0x45, 0x9c, 0xa0, 0x6a, 0x25, 0x36, 0x41, 0x45,
	0x1f, 0x66, 0xdc, 0xf7, 0x3f, 0x44, 0x86, 0xee, 0xa0, 0x3a, 0x16, 0x15, 0xe8, 0x97, 0xa4, 0xab,
	0x37, 0x2c, 0xc7, 0x53, 0x83, 0xba, 0xfd, 0x7d, 0x9f, 0xa4, 0x5a, 0x5f, 0x92, 0x2a, 0x40, 0x55,
	0x2e, 0x0c, 0x71, 0xe1, 0xcd, 0xe7, 0x4a, 0x81, 0x83, 0xdc, 0x76, 0x1f, 0xca, 0x00, 0xa6, 0x9f,
	0x9d, 0xe0, 0xb9, 0xde, 0x74, 0xb0, 0x01, 0xaa, 0xa9, 0x2d, 0xb7, 0xb5, 0x87, 0x4f, 0x0e, 0x03,
	0x8f, 0xb3, 0x4c, 0x20, 0x9c, 0x4c, 0x40, 0x1f, 0x85, 0xfc, 0x4b, 0x19, 0x8c, 0x77, 0x1e, 0x9a,
	0xe0, 0x74, 0x12, 0xe8, 0xe8, 0xfb, 0x93, 0xf2, 0x52, 0xce, 0x68, 0x70, 0xf0, 0xbb, 0x2b, 0xb7,
	0xb5, 0x7f, 0x3f, 0x39, 0x10, 0xbf, 0xe7, 0x43, 0xfc, 0x4e, 0x5f, 0x88, 0x97, 0xc0, 0xa2, 0x32,
	0xdf, 0xeb, 0xe8, 0x17, 0x5b, 0x66, 0x2e, 0xcc, 0x13, 0xf0, 0xa4, 0x80, 0xd9, 0x7b, 0x2c, 0xec,
	0xe2, 0xab, 0x14, 0xef, 0xc8, 0x85, 0x8b, 0x9f, 0x8d, 0xb5, 0xb5, 0xaf, 0x46, 0x41, 0xb1, 0xaa,
	0x56, 0xe0, 0x55, 0xf0, 0x4c, 0xf4, 0xe2, 0xa8, 0xed, 0x6c, 0xc1, 0xd5, 0xe0, 0xef, 0x62, 0x0c,
	0xad, 0xd5, 0xae, 0xad, 0x23, 0xe2, 0x62, 0xea, 0xff, 0x61, 0x1b, 0x11, 0x27, 0xd5, 0xb5, 0x5d,
	0x9d, 0xf2, 0xb0, 0xfb, 0xaa, 0xd5, 0xd1, 0x65, 0xb5, 0xa2, 0x56, 0x16, 0x24, 0xb9, 0x3a, 0xa9,
	0xbb, 0xae, 0x6d, 0x19, 0xde, 0xcc, 0xf2, 0x75, 0x46, 0x9c, 0xd5, 0xd4, 0x97, 0xda, 0xf0, 0x1d,
	0xbd, 0x76, 0x09, 0x14, 0x5f, 0xab, 0x54, 0xe0, 0x1b, 0xe0, 0xf5, 0xf8, 0x14, 0xdd, 0x41, 0x2d,
	0x07, 0x1f, 0xb9, 0xd8, 0x10, 0x90, 0x62, 0x4a, 0x09, 0x45, 0xc4, 0x30, 0x5a, 0x14, 0x9b, 0x9d,
	0xb4, 0x19, 0xa6, 0x07, 0x98, 0x22, 0x66, 0x99, 0x58, 0xad, 0xed, 0x8a, 0xd0, 0x15, 0xf8, 0x3d,
	0xf0, 0x5e, 0x56, 0x68, 0x9f, 0xa1, 0x3a, 0x31, 0x6f, 0x8a, 0xf0, 0x4d, 0xdd, 0xf6, 0x37, 0x2f,
	0xe1, 0x9a, 0x50, 0x64, 0x12, 0xec, 0xe7, 0xd4, 0xd4, 0xb9, 0xb1, 0xef, 0x43, 0xd2, 0x89, 0xdc,
	0xb9, 0x98, 0xd7, 0xae, 0x88, 0x00, 0xcb, 0x70, 0x03, 0xac, 0xe5, 0x07, 0x08, 0x1d, 0x05, 0x8a,
	0x63, 0xde, 0xa8, 0xd8, 0x32, 0xce, 0x33, 0x64, 0x50, 0x6c, 0x0a, 0xa4, 0x75, 0x9b, 0xa9, 0xb5,
	0x1d, 0xe1, 0xed, 0x55, 0xb8, 0x05, 0x36, 0xd3, 0xde, 0x84, 0x7d, 0xd7, 0xd5, 0xbe, 0x7e, 0x80,
	0x91, 0x8b, 0x69, 0xd3, 0x62, 0x4c, 0x6c, 0xb6, 0x9c, 0x20, 0xdd, 0xd3, 0x57, 0x0c, 0x55, 0xf5,
	0xfd, 0x7f, 0x4a, 0xe0, 0x1f, 0x52, 0x28, 0x9d, 0x2f, 0xa5, 0xf1, 0x22, 0xfc, 0xa1, 0xa4, 0x05,
	0x96, 0x24, 0x71, 0xb3, 0xf1, 0x27, 0x31, 0x01, 0x06, 0xc5, 0x8c, 0x53, 0xcb, 0x5b, 0xab, 0x70,
	0xdd, 0xe2, 0xfb, 0xc2, 0xd4, 0xd0, 0xc5, 0x07, 0x6f, 0xb3, 0x53, 0xd1, 0xd5, 0x7d, 0x1c, 0x1d,
	0x10, 0x59, 0xb8, 0x94, 0x78, 0x9e, 0xf7, 0x88, 0x6d, 0x93, 0x43, 0x3f, 0x17, 0x11, 0x99, 0x50,
	0xeb, 0x63, 0xdf, 0x62, 0x8d, 0x98, 0x18, 0xed, 0xd9, 0xe4, 0x50, 0x9d, 0x1b, 0xa9, 0x8e, 0x0b,
	0xed, 0x0a, 0x17, 0xab, 0x9e, 0x8a, 0x39, 0xb9, 0x81, 0x9d, 0x8b, 0xab, 0x40, 0xf1, 0x05, 0x0e,
	0xe1, 0x26, 0xd5, 0x1d, 0x2e, 0x72, 0xd1, 0xcd, 0x60, 0x75, 0x60, 0x3a, 0x78, 0xc8, 0x80, 0xa7,
	0x83, 0x41, 0xef, 0x5f, 0xc1, 0xe8, 0x5b, 0xd2, 0x4e, 0xe1, 0xfd, 0xe8, 0x7f, 0x05, 0xf9, 0x81,
	0x54, 0xb8, 0x23, 0x15, 0xee, 0x49, 0x85, 0x5f, 0x4b, 0x85, 0xbf, 0x48, 0x85, 0xaf, 0xa5, 0xc2,
	0x1f, 0xe4, 0x42, 0x7d, 0xcc, 0x7b, 0xba, 0x79, 0xf5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07,
	0x4c, 0xf1, 0x79, 0x6c, 0x22, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EntitlementServiceClient is the client API for EntitlementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntitlementServiceClient interface {
	// AddEntitlementRequestForCurrentUser sends the entitlement request for current user
	AddEntitlementRequestForCurrentUser(ctx context.Context, in *AddEntitlementRequestForCurrentUserRequest, opts ...grpc.CallOption) (*EntitlementRequest, error)
	// AddEntitlementRequestForUser sends the entitlement request for user
	AddEntitlementRequestForUser(ctx context.Context, in *AddEntitlementRequestForUserRequest, opts ...grpc.CallOption) (*AddEntitlementRequestForUserResponse, error)
	// DeleteEntitlement deletes an entitlement for user.
	DeleteEntitlement(ctx context.Context, in *DeleteEntitlementRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// DeleteEntitlementRequest deletes a entitlement request.
	DeleteEntitlementRequest(ctx context.Context, in *DeleteEntitlementRequestRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// GetEntitlementRequestForUser retrieves the details of a specific entitlement request for userid.
	GetEntitlementRequestForUser(ctx context.Context, in *GetEntitlementRequestForUserRequest, opts ...grpc.CallOption) (*GetEntitlementRequestForUserResponse, error)
	// GetEntitlementRequestForCurrentUser retrieves the details of a specific entitlement request for current user.
	GetEntitlementRequestForCurrentUser(ctx context.Context, in *GetEntitlementRequestForCurrentUserRequest, opts ...grpc.CallOption) (*GetEntitlementRequestForCurrentUserResponse, error)
	// GetEntitlementForUser retrieves the details of a specific entitlement for userid.
	GetEntitlementForUser(ctx context.Context, in *GetEntitlementForUserRequest, opts ...grpc.CallOption) (*Entitlements, error)
	// GetEntitlementForCurrentUser retrieves the details of a specific entitlement for current user.
	GetEntitlementForCurrentUser(ctx context.Context, in *GetEntitlementForCurrentUserRequest, opts ...grpc.CallOption) (*Entitlements, error)
	// GetEntitlementForUserAtBank retrieves the details of a specific entitlement for userid at bank
	GetEntitlementForUserAtBank(ctx context.Context, in *GetEntitlementForUserAtBankRequest, opts ...grpc.CallOption) (*Entitlements, error)
	// GetAllEntitlementRequests returns a list containing up to 20 entitlement requests.
	GetAllEntitlementRequests(ctx context.Context, in *GetAllEntitlementRequestRequest, opts ...grpc.CallOption) (*EntitlementRequests, error)
	// GetAllEntitlements returns a list containing up to 20 entitlements.
	GetAllEntitlements(ctx context.Context, in *GetAllEntitlementsRequest, opts ...grpc.CallOption) (*Entitlements, error)
	// GetRoles returns a list containing up to 20 roles.
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error)
}

type entitlementServiceClient struct {
	cc *grpc.ClientConn
}

func NewEntitlementServiceClient(cc *grpc.ClientConn) EntitlementServiceClient {
	return &entitlementServiceClient{cc}
}

func (c *entitlementServiceClient) AddEntitlementRequestForCurrentUser(ctx context.Context, in *AddEntitlementRequestForCurrentUserRequest, opts ...grpc.CallOption) (*EntitlementRequest, error) {
	out := new(EntitlementRequest)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/AddEntitlementRequestForCurrentUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) AddEntitlementRequestForUser(ctx context.Context, in *AddEntitlementRequestForUserRequest, opts ...grpc.CallOption) (*AddEntitlementRequestForUserResponse, error) {
	out := new(AddEntitlementRequestForUserResponse)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/AddEntitlementRequestForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) DeleteEntitlement(ctx context.Context, in *DeleteEntitlementRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/DeleteEntitlement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) DeleteEntitlementRequest(ctx context.Context, in *DeleteEntitlementRequestRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/DeleteEntitlementRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetEntitlementRequestForUser(ctx context.Context, in *GetEntitlementRequestForUserRequest, opts ...grpc.CallOption) (*GetEntitlementRequestForUserResponse, error) {
	out := new(GetEntitlementRequestForUserResponse)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetEntitlementRequestForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetEntitlementRequestForCurrentUser(ctx context.Context, in *GetEntitlementRequestForCurrentUserRequest, opts ...grpc.CallOption) (*GetEntitlementRequestForCurrentUserResponse, error) {
	out := new(GetEntitlementRequestForCurrentUserResponse)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetEntitlementRequestForCurrentUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetEntitlementForUser(ctx context.Context, in *GetEntitlementForUserRequest, opts ...grpc.CallOption) (*Entitlements, error) {
	out := new(Entitlements)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetEntitlementForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetEntitlementForCurrentUser(ctx context.Context, in *GetEntitlementForCurrentUserRequest, opts ...grpc.CallOption) (*Entitlements, error) {
	out := new(Entitlements)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetEntitlementForCurrentUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetEntitlementForUserAtBank(ctx context.Context, in *GetEntitlementForUserAtBankRequest, opts ...grpc.CallOption) (*Entitlements, error) {
	out := new(Entitlements)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetEntitlementForUserAtBank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetAllEntitlementRequests(ctx context.Context, in *GetAllEntitlementRequestRequest, opts ...grpc.CallOption) (*EntitlementRequests, error) {
	out := new(EntitlementRequests)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetAllEntitlementRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetAllEntitlements(ctx context.Context, in *GetAllEntitlementsRequest, opts ...grpc.CallOption) (*Entitlements, error) {
	out := new(Entitlements)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetAllEntitlements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementServiceClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error) {
	out := new(GetRolesResponse)
	err := c.cc.Invoke(ctx, "/entitlement.EntitlementService/GetRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntitlementServiceServer is the server API for EntitlementService service.
type EntitlementServiceServer interface {
	// AddEntitlementRequestForCurrentUser sends the entitlement request for current user
	AddEntitlementRequestForCurrentUser(context.Context, *AddEntitlementRequestForCurrentUserRequest) (*EntitlementRequest, error)
	// AddEntitlementRequestForUser sends the entitlement request for user
	AddEntitlementRequestForUser(context.Context, *AddEntitlementRequestForUserRequest) (*AddEntitlementRequestForUserResponse, error)
	// DeleteEntitlement deletes an entitlement for user.
	DeleteEntitlement(context.Context, *DeleteEntitlementRequest) (*empty.Empty, error)
	// DeleteEntitlementRequest deletes a entitlement request.
	DeleteEntitlementRequest(context.Context, *DeleteEntitlementRequestRequest) (*empty.Empty, error)
	// GetEntitlementRequestForUser retrieves the details of a specific entitlement request for userid.
	GetEntitlementRequestForUser(context.Context, *GetEntitlementRequestForUserRequest) (*GetEntitlementRequestForUserResponse, error)
	// GetEntitlementRequestForCurrentUser retrieves the details of a specific entitlement request for current user.
	GetEntitlementRequestForCurrentUser(context.Context, *GetEntitlementRequestForCurrentUserRequest) (*GetEntitlementRequestForCurrentUserResponse, error)
	// GetEntitlementForUser retrieves the details of a specific entitlement for userid.
	GetEntitlementForUser(context.Context, *GetEntitlementForUserRequest) (*Entitlements, error)
	// GetEntitlementForCurrentUser retrieves the details of a specific entitlement for current user.
	GetEntitlementForCurrentUser(context.Context, *GetEntitlementForCurrentUserRequest) (*Entitlements, error)
	// GetEntitlementForUserAtBank retrieves the details of a specific entitlement for userid at bank
	GetEntitlementForUserAtBank(context.Context, *GetEntitlementForUserAtBankRequest) (*Entitlements, error)
	// GetAllEntitlementRequests returns a list containing up to 20 entitlement requests.
	GetAllEntitlementRequests(context.Context, *GetAllEntitlementRequestRequest) (*EntitlementRequests, error)
	// GetAllEntitlements returns a list containing up to 20 entitlements.
	GetAllEntitlements(context.Context, *GetAllEntitlementsRequest) (*Entitlements, error)
	// GetRoles returns a list containing up to 20 roles.
	GetRoles(context.Context, *GetRolesRequest) (*GetRolesResponse, error)
}

// UnimplementedEntitlementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEntitlementServiceServer struct {
}

func (*UnimplementedEntitlementServiceServer) AddEntitlementRequestForCurrentUser(ctx context.Context, req *AddEntitlementRequestForCurrentUserRequest) (*EntitlementRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEntitlementRequestForCurrentUser not implemented")
}
func (*UnimplementedEntitlementServiceServer) AddEntitlementRequestForUser(ctx context.Context, req *AddEntitlementRequestForUserRequest) (*AddEntitlementRequestForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEntitlementRequestForUser not implemented")
}
func (*UnimplementedEntitlementServiceServer) DeleteEntitlement(ctx context.Context, req *DeleteEntitlementRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntitlement not implemented")
}
func (*UnimplementedEntitlementServiceServer) DeleteEntitlementRequest(ctx context.Context, req *DeleteEntitlementRequestRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntitlementRequest not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetEntitlementRequestForUser(ctx context.Context, req *GetEntitlementRequestForUserRequest) (*GetEntitlementRequestForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntitlementRequestForUser not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetEntitlementRequestForCurrentUser(ctx context.Context, req *GetEntitlementRequestForCurrentUserRequest) (*GetEntitlementRequestForCurrentUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntitlementRequestForCurrentUser not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetEntitlementForUser(ctx context.Context, req *GetEntitlementForUserRequest) (*Entitlements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntitlementForUser not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetEntitlementForCurrentUser(ctx context.Context, req *GetEntitlementForCurrentUserRequest) (*Entitlements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntitlementForCurrentUser not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetEntitlementForUserAtBank(ctx context.Context, req *GetEntitlementForUserAtBankRequest) (*Entitlements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntitlementForUserAtBank not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetAllEntitlementRequests(ctx context.Context, req *GetAllEntitlementRequestRequest) (*EntitlementRequests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllEntitlementRequests not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetAllEntitlements(ctx context.Context, req *GetAllEntitlementsRequest) (*Entitlements, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllEntitlements not implemented")
}
func (*UnimplementedEntitlementServiceServer) GetRoles(ctx context.Context, req *GetRolesRequest) (*GetRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoles not implemented")
}

func RegisterEntitlementServiceServer(s *grpc.Server, srv EntitlementServiceServer) {
	s.RegisterService(&_EntitlementService_serviceDesc, srv)
}

func _EntitlementService_AddEntitlementRequestForCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEntitlementRequestForCurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).AddEntitlementRequestForCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/AddEntitlementRequestForCurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).AddEntitlementRequestForCurrentUser(ctx, req.(*AddEntitlementRequestForCurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_AddEntitlementRequestForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEntitlementRequestForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).AddEntitlementRequestForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/AddEntitlementRequestForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).AddEntitlementRequestForUser(ctx, req.(*AddEntitlementRequestForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_DeleteEntitlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntitlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).DeleteEntitlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/DeleteEntitlement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).DeleteEntitlement(ctx, req.(*DeleteEntitlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_DeleteEntitlementRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntitlementRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).DeleteEntitlementRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/DeleteEntitlementRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).DeleteEntitlementRequest(ctx, req.(*DeleteEntitlementRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetEntitlementRequestForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntitlementRequestForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetEntitlementRequestForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetEntitlementRequestForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetEntitlementRequestForUser(ctx, req.(*GetEntitlementRequestForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetEntitlementRequestForCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntitlementRequestForCurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetEntitlementRequestForCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetEntitlementRequestForCurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetEntitlementRequestForCurrentUser(ctx, req.(*GetEntitlementRequestForCurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetEntitlementForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntitlementForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetEntitlementForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetEntitlementForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetEntitlementForUser(ctx, req.(*GetEntitlementForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetEntitlementForCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntitlementForCurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetEntitlementForCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetEntitlementForCurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetEntitlementForCurrentUser(ctx, req.(*GetEntitlementForCurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetEntitlementForUserAtBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntitlementForUserAtBankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetEntitlementForUserAtBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetEntitlementForUserAtBank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetEntitlementForUserAtBank(ctx, req.(*GetEntitlementForUserAtBankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetAllEntitlementRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllEntitlementRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetAllEntitlementRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetAllEntitlementRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetAllEntitlementRequests(ctx, req.(*GetAllEntitlementRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetAllEntitlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllEntitlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetAllEntitlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetAllEntitlements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetAllEntitlements(ctx, req.(*GetAllEntitlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntitlementService_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementServiceServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entitlement.EntitlementService/GetRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementServiceServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntitlementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entitlement.EntitlementService",
	HandlerType: (*EntitlementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEntitlementRequestForCurrentUser",
			Handler:    _EntitlementService_AddEntitlementRequestForCurrentUser_Handler,
		},
		{
			MethodName: "AddEntitlementRequestForUser",
			Handler:    _EntitlementService_AddEntitlementRequestForUser_Handler,
		},
		{
			MethodName: "DeleteEntitlement",
			Handler:    _EntitlementService_DeleteEntitlement_Handler,
		},
		{
			MethodName: "DeleteEntitlementRequest",
			Handler:    _EntitlementService_DeleteEntitlementRequest_Handler,
		},
		{
			MethodName: "GetEntitlementRequestForUser",
			Handler:    _EntitlementService_GetEntitlementRequestForUser_Handler,
		},
		{
			MethodName: "GetEntitlementRequestForCurrentUser",
			Handler:    _EntitlementService_GetEntitlementRequestForCurrentUser_Handler,
		},
		{
			MethodName: "GetEntitlementForUser",
			Handler:    _EntitlementService_GetEntitlementForUser_Handler,
		},
		{
			MethodName: "GetEntitlementForCurrentUser",
			Handler:    _EntitlementService_GetEntitlementForCurrentUser_Handler,
		},
		{
			MethodName: "GetEntitlementForUserAtBank",
			Handler:    _EntitlementService_GetEntitlementForUserAtBank_Handler,
		},
		{
			MethodName: "GetAllEntitlementRequests",
			Handler:    _EntitlementService_GetAllEntitlementRequests_Handler,
		},
		{
			MethodName: "GetAllEntitlements",
			Handler:    _EntitlementService_GetAllEntitlements_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _EntitlementService_GetRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openbank/openbank/v1/entitlement/all.proto",
}
