// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openbank/openbank/v1/accountapplications/all.proto

package accountapplications

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	types "github.com/openbank/openbank/v1/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Entity type defines the type of account application
type AccountApplicationStatus int32

const (
	AccountApplicationStatus_UnknownApplicationStatus AccountApplicationStatus = 0
	// Account application is created
	AccountApplicationStatus_Requested AccountApplicationStatus = 1
	// Account application is accepted
	AccountApplicationStatus_Accepted AccountApplicationStatus = 2
)

var AccountApplicationStatus_name = map[int32]string{
	0: "UnknownApplicationStatus",
	1: "Requested",
	2: "Accepted",
}

var AccountApplicationStatus_value = map[string]int32{
	"UnknownApplicationStatus": 0,
	"Requested":                1,
	"Accepted":                 2,
}

func (x AccountApplicationStatus) String() string {
	return proto.EnumName(AccountApplicationStatus_name, int32(x))
}

func (AccountApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{0}
}

// Structure of user information
type User struct {
	// User identifier used to login
	ID string `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	// Email of the user
	Email string `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	// Display name of the user
	Username             string   `protobuf:"bytes,3,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// / AccountApplication is a structure of account application
type AccountApplication struct {
	ID                   string                   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	ProductCode          string                   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	UserID               string                   `protobuf:"bytes,3,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	CustomerProfileID    string                   `protobuf:"bytes,4,opt,name=CustomerProfileID,json=customer_profile_id,proto3" json:"CustomerProfileID,omitempty"`
	DateOfApplication    *timestamp.Timestamp     `protobuf:"bytes,5,opt,name=DateOfApplication,json=date_of_application,proto3" json:"DateOfApplication,omitempty"`
	Status               AccountApplicationStatus `protobuf:"varint,6,opt,name=Status,json=status,proto3,enum=accountapplications.AccountApplicationStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AccountApplication) Reset()         { *m = AccountApplication{} }
func (m *AccountApplication) String() string { return proto.CompactTextString(m) }
func (*AccountApplication) ProtoMessage()    {}
func (*AccountApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{1}
}

func (m *AccountApplication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountApplication.Unmarshal(m, b)
}
func (m *AccountApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountApplication.Marshal(b, m, deterministic)
}
func (m *AccountApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountApplication.Merge(m, src)
}
func (m *AccountApplication) XXX_Size() int {
	return xxx_messageInfo_AccountApplication.Size(m)
}
func (m *AccountApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountApplication.DiscardUnknown(m)
}

var xxx_messageInfo_AccountApplication proto.InternalMessageInfo

func (m *AccountApplication) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountApplication) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *AccountApplication) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AccountApplication) GetCustomerProfileID() string {
	if m != nil {
		return m.CustomerProfileID
	}
	return ""
}

func (m *AccountApplication) GetDateOfApplication() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfApplication
	}
	return nil
}

func (m *AccountApplication) GetStatus() AccountApplicationStatus {
	if m != nil {
		return m.Status
	}
	return AccountApplicationStatus_UnknownApplicationStatus
}

// CreateAccountApplicationRequest is a request mesasge to create account application
type CreateAccountApplicationRequest struct {
	ProductCode          string   `protobuf:"bytes,1,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	ProfileID            string   `protobuf:"bytes,3,opt,name=ProfileID,json=profile_id,proto3" json:"ProfileID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountApplicationRequest) Reset()         { *m = CreateAccountApplicationRequest{} }
func (m *CreateAccountApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountApplicationRequest) ProtoMessage()    {}
func (*CreateAccountApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{2}
}

func (m *CreateAccountApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountApplicationRequest.Unmarshal(m, b)
}
func (m *CreateAccountApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountApplicationRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountApplicationRequest.Merge(m, src)
}
func (m *CreateAccountApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountApplicationRequest.Size(m)
}
func (m *CreateAccountApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountApplicationRequest proto.InternalMessageInfo

func (m *CreateAccountApplicationRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *CreateAccountApplicationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateAccountApplicationRequest) GetProfileID() string {
	if m != nil {
		return m.ProfileID
	}
	return ""
}

// CreateAccountApplicationResponse is a response message for create account application
type CreateAccountApplicationResponse struct {
	ID                   string                   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	ProductCode          string                   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	User                 *User                    `protobuf:"bytes,3,opt,name=User,json=user,proto3" json:"User,omitempty"`
	CustomerProfile      *types.Profile           `protobuf:"bytes,4,opt,name=CustomerProfile,json=customer_profile,proto3" json:"CustomerProfile,omitempty"`
	DateOfApplication    *timestamp.Timestamp     `protobuf:"bytes,5,opt,name=DateOfApplication,json=date_of_application,proto3" json:"DateOfApplication,omitempty"`
	Status               AccountApplicationStatus `protobuf:"varint,6,opt,name=Status,json=status,proto3,enum=accountapplications.AccountApplicationStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateAccountApplicationResponse) Reset()         { *m = CreateAccountApplicationResponse{} }
func (m *CreateAccountApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountApplicationResponse) ProtoMessage()    {}
func (*CreateAccountApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{3}
}

func (m *CreateAccountApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountApplicationResponse.Unmarshal(m, b)
}
func (m *CreateAccountApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountApplicationResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountApplicationResponse.Merge(m, src)
}
func (m *CreateAccountApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountApplicationResponse.Size(m)
}
func (m *CreateAccountApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountApplicationResponse proto.InternalMessageInfo

func (m *CreateAccountApplicationResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreateAccountApplicationResponse) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *CreateAccountApplicationResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAccountApplicationResponse) GetCustomerProfile() *types.Profile {
	if m != nil {
		return m.CustomerProfile
	}
	return nil
}

func (m *CreateAccountApplicationResponse) GetDateOfApplication() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfApplication
	}
	return nil
}

func (m *CreateAccountApplicationResponse) GetStatus() AccountApplicationStatus {
	if m != nil {
		return m.Status
	}
	return AccountApplicationStatus_UnknownApplicationStatus
}

// Structure of credit rating information
type CreditRating struct {
	// Rating about the applicant credit history
	Rating string `protobuf:"bytes,1,opt,name=Rating,json=rating,proto3" json:"Rating,omitempty"`
	// The company who provided the credit history
	Source               string   `protobuf:"bytes,2,opt,name=Source,json=source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditRating) Reset()         { *m = CreditRating{} }
func (m *CreditRating) String() string { return proto.CompactTextString(m) }
func (*CreditRating) ProtoMessage()    {}
func (*CreditRating) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{4}
}

func (m *CreditRating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditRating.Unmarshal(m, b)
}
func (m *CreditRating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditRating.Marshal(b, m, deterministic)
}
func (m *CreditRating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditRating.Merge(m, src)
}
func (m *CreditRating) XXX_Size() int {
	return xxx_messageInfo_CreditRating.Size(m)
}
func (m *CreditRating) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditRating.DiscardUnknown(m)
}

var xxx_messageInfo_CreditRating proto.InternalMessageInfo

func (m *CreditRating) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

func (m *CreditRating) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

// GetAccountApplicationpRequest is the request envelope to get an account application by its identifier.
type GetAccountApplicationRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountApplicationRequest) Reset()         { *m = GetAccountApplicationRequest{} }
func (m *GetAccountApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountApplicationRequest) ProtoMessage()    {}
func (*GetAccountApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{5}
}

func (m *GetAccountApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountApplicationRequest.Unmarshal(m, b)
}
func (m *GetAccountApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountApplicationRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountApplicationRequest.Merge(m, src)
}
func (m *GetAccountApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountApplicationRequest.Size(m)
}
func (m *GetAccountApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountApplicationRequest proto.InternalMessageInfo

func (m *GetAccountApplicationRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// GetAccountApplicationsRequest is the request envelope to get a list of filtered account applications.
type GetAccountApplicationsRequest struct {
	// NextStartingIndex is a cursor for pagination.
	NextStartingIndex    string   `protobuf:"bytes,1,opt,name=NextStartingIndex,json=next_starting_index,proto3" json:"NextStartingIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountApplicationsRequest) Reset()         { *m = GetAccountApplicationsRequest{} }
func (m *GetAccountApplicationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountApplicationsRequest) ProtoMessage()    {}
func (*GetAccountApplicationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{6}
}

func (m *GetAccountApplicationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountApplicationsRequest.Unmarshal(m, b)
}
func (m *GetAccountApplicationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountApplicationsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountApplicationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountApplicationsRequest.Merge(m, src)
}
func (m *GetAccountApplicationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountApplicationsRequest.Size(m)
}
func (m *GetAccountApplicationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountApplicationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountApplicationsRequest proto.InternalMessageInfo

func (m *GetAccountApplicationsRequest) GetNextStartingIndex() string {
	if m != nil {
		return m.NextStartingIndex
	}
	return ""
}

// GetAccountApplicationsResponse wraps the list of account applications.
type GetAccountApplicationsResponse struct {
	// Result is a list containing up to 20 Accounts.
	Result []*AccountApplication `protobuf:"bytes,1,rep,name=Result,json=result,proto3" json:"Result,omitempty"`
	// HasMore indicates if there are more accounts available.
	HasMore              bool     `protobuf:"varint,2,opt,name=HasMore,json=has_more,proto3" json:"HasMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountApplicationsResponse) Reset()         { *m = GetAccountApplicationsResponse{} }
func (m *GetAccountApplicationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountApplicationsResponse) ProtoMessage()    {}
func (*GetAccountApplicationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{7}
}

func (m *GetAccountApplicationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountApplicationsResponse.Unmarshal(m, b)
}
func (m *GetAccountApplicationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountApplicationsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountApplicationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountApplicationsResponse.Merge(m, src)
}
func (m *GetAccountApplicationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountApplicationsResponse.Size(m)
}
func (m *GetAccountApplicationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountApplicationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountApplicationsResponse proto.InternalMessageInfo

func (m *GetAccountApplicationsResponse) GetResult() []*AccountApplication {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAccountApplicationsResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// UpdateAccountApplicationStatusRequest is the request envelope to update an account application status.
type UpdateAccountApplicationStatusRequest struct {
	// ID is the unique identifier of the account application to update.
	ID string `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	// Status of the account application
	Status               AccountApplicationStatus `protobuf:"varint,2,opt,name=Status,json=status,proto3,enum=accountapplications.AccountApplicationStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UpdateAccountApplicationStatusRequest) Reset()         { *m = UpdateAccountApplicationStatusRequest{} }
func (m *UpdateAccountApplicationStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountApplicationStatusRequest) ProtoMessage()    {}
func (*UpdateAccountApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a69271d88e859e2b, []int{8}
}

func (m *UpdateAccountApplicationStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountApplicationStatusRequest.Unmarshal(m, b)
}
func (m *UpdateAccountApplicationStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountApplicationStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountApplicationStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountApplicationStatusRequest.Merge(m, src)
}
func (m *UpdateAccountApplicationStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountApplicationStatusRequest.Size(m)
}
func (m *UpdateAccountApplicationStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountApplicationStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountApplicationStatusRequest proto.InternalMessageInfo

func (m *UpdateAccountApplicationStatusRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateAccountApplicationStatusRequest) GetStatus() AccountApplicationStatus {
	if m != nil {
		return m.Status
	}
	return AccountApplicationStatus_UnknownApplicationStatus
}

func init() {
	proto.RegisterEnum("accountapplications.AccountApplicationStatus", AccountApplicationStatus_name, AccountApplicationStatus_value)
	proto.RegisterType((*User)(nil), "accountapplications.User")
	proto.RegisterType((*AccountApplication)(nil), "accountapplications.AccountApplication")
	proto.RegisterType((*CreateAccountApplicationRequest)(nil), "accountapplications.CreateAccountApplicationRequest")
	proto.RegisterType((*CreateAccountApplicationResponse)(nil), "accountapplications.CreateAccountApplicationResponse")
	proto.RegisterType((*CreditRating)(nil), "accountapplications.CreditRating")
	proto.RegisterType((*GetAccountApplicationRequest)(nil), "accountapplications.GetAccountApplicationRequest")
	proto.RegisterType((*GetAccountApplicationsRequest)(nil), "accountapplications.GetAccountApplicationsRequest")
	proto.RegisterType((*GetAccountApplicationsResponse)(nil), "accountapplications.GetAccountApplicationsResponse")
	proto.RegisterType((*UpdateAccountApplicationStatusRequest)(nil), "accountapplications.UpdateAccountApplicationStatusRequest")
}

func init() {
	proto.RegisterFile("github.com/openbank/openbank/v1/accountapplications/all.proto", fileDescriptor_a69271d88e859e2b)
}

var fileDescriptor_a69271d88e859e2b = []byte{
	// 1614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcd, 0x6f, 0x1b, 0x5b,
	0x15, 0x9f, 0x19, 0x27, 0x8e, 0x73, 0xf3, 0x78, 0x24, 0x37, 0xe2, 0xe1, 0x37, 0x34, 0xcd, 0xc5,
	0x4f, 0x8f, 0x97, 0x17, 0x91, 0xb1, 0xe3, 0xa4, 0x42, 0xb5, 0x54, 0x55, 0xce, 0x07, 0x6d, 0x42,
	0xa1, 0xc1, 0xfd, 0x10, 0x74, 0x51, 0xf7, 0x7a, 0xe6, 0xd8, 0x9e, 0x76, 0x7c, 0xef, 0x70, 0xef,
	0x9d, 0x38, 0x01, 0x21, 0x21, 0x56, 0x15, 0x48, 0xa8, 0x0a, 0x2c, 0x11, 0x8b, 0xae, 0xf8, 0x03,
	0xba, 0x40, 0x08, 0xfe, 0x03, 0x16, 0x48, 0x6c, 0xd8, 0xb0, 0xe2, 0x6b, 0xc3, 0x06, 0xc1, 0x82,
	0x25, 0xba, 0x33, 0x13, 0xc7, 0x89, 0xc7, 0x89, 0x2b, 0x75, 0xf3, 0x56, 0x71, 0xee, 0x39, 0xe7,
	0x77, 0xce, 0xfd, 0xfd, 0xce, 0x39, 0x33, 0x36, 0xba, 0xd5, 0xf1, 0x55, 0x37, 0x6a, 0x39, 0x2e,
	0xef, 0x95, 0x79, 0x08, 0xac, 0x45, 0xd9, 0x8b, 0xb3, 0x0f, 0x87, 0xeb, 0x65, 0xea, 0xba, 0x3c,
	0x62, 0x8a, 0x86, 0x61, 0xe0, 0xbb, 0x54, 0xf9, 0x9c, 0xc9, 0x32, 0x0d, 0x02, 0x27, 0x14, 0x5c,
	0x71, 0xbc, 0x98, 0x61, 0xb6, 0x97, 0x3b, 0x9c, 0x77, 0x02, 0x28, 0xc7, 0x2e, 0xad, 0xa8, 0x5d,
	0x56, 0x7e, 0x0f, 0xa4, 0xa2, 0xbd, 0x30, 0x89, 0xb2, 0xaf, 0xa5, 0x0e, 0x34, 0xf4, 0xcb, 0x94,
	0x31, 0xae, 0x92, 0xc0, 0xd4, 0xfa, 0xd5, 0xf8, 0x8f, 0xbb, 0xd6, 0x01, 0xb6, 0x26, 0xfb, 0xb4,
	0xd3, 0x01, 0x51, 0xe6, 0x61, 0x9a, 0x79, 0xc4, 0xfb, 0x4b, 0x17, 0x93, 0x41, 0x2f, 0x54, 0xc7,
	0xa9, 0xb1, 0x7c, 0xd5, 0xed, 0xd4, 0x71, 0x08, 0x43, 0xf7, 0x29, 0x29, 0x34, 0xf5, 0x48, 0x82,
	0xc0, 0x36, 0xb2, 0xf6, 0x76, 0x8a, 0x26, 0x31, 0x57, 0x66, 0xb7, 0x50, 0xc1, 0x28, 0x1a, 0x2b,
	0x46, 0xc5, 0x38, 0x30, 0x1a, 0x96, 0xef, 0x61, 0x82, 0xa6, 0x77, 0x7b, 0xd4, 0x0f, 0x8a, 0xd6,
	0x88, 0x79, 0x1a, 0xb4, 0x01, 0x7f, 0x05, 0x15, 0x34, 0x0a, 0xa3, 0x3d, 0x28, 0xe6, 0x46, 0x9c,
	0x0a, 0x51, 0x6a, 0xab, 0xe5, 0x0b, 0xc6, 0xbc, 0x51, 0x34, 0x4a, 0xff, 0xb1, 0x10, 0xae, 0x27,
	0x44, 0xd6, 0xcf, 0x88, 0xbc, 0xb4, 0x88, 0x35, 0x34, 0x77, 0x20, 0xb8, 0x17, 0xb9, 0x6a, 0x9b,
	0x7b, 0x90, 0x51, 0xca, 0x7b, 0x61, 0x62, 0x6e, 0xba, 0xdc, 0x03, 0xfc, 0x11, 0xca, 0xeb, 0x8a,
	0xf6, 0x76, 0x32, 0xea, 0x99, 0xd1, 0xf5, 0x34, 0x7d, 0x0f, 0xd7, 0xd0, 0xc2, 0x76, 0x24, 0x15,
	0xef, 0x81, 0x38, 0x10, 0xbc, 0xed, 0x07, 0xb0, 0xb7, 0x53, 0x9c, 0x1a, 0xf1, 0x5f, 0x74, 0x53,
	0xa7, 0x66, 0x98, 0x78, 0xe9, 0xd8, 0xc7, 0x68, 0x61, 0x87, 0x2a, 0xb8, 0xdf, 0x1e, 0xba, 0x40,
	0x71, 0x9a, 0x98, 0x2b, 0x73, 0x55, 0xdb, 0x49, 0x24, 0x72, 0x4e, 0x25, 0x72, 0x1e, 0x9e, 0xf6,
	0xc3, 0x79, 0x5c, 0x8f, 0x2a, 0x68, 0xf2, 0x76, 0x73, 0xa8, 0x99, 0xf0, 0xb7, 0x51, 0xfe, 0x81,
	0xa2, 0x2a, 0x92, 0xc5, 0x3c, 0x31, 0x57, 0xde, 0xaf, 0xae, 0x39, 0x19, 0x1d, 0xe7, 0x8c, 0x92,
	0x97, 0x04, 0x9d, 0xc3, 0xcf, 0xcb, 0xf8, 0x6c, 0xc0, 0xfa, 0xaf, 0x4d, 0xb4, 0xbc, 0x2d, 0x80,
	0x2a, 0x18, 0x0d, 0x6f, 0xc0, 0xf7, 0x22, 0x90, 0xea, 0x22, 0xcd, 0xe6, 0xc4, 0x34, 0x5b, 0xe3,
	0x69, 0xfe, 0x14, 0xcd, 0x9e, 0xd1, 0x3b, 0x2a, 0x07, 0x3a, 0x63, 0x75, 0x50, 0xea, 0xeb, 0x1c,
	0x22, 0xe3, 0x4b, 0x95, 0x21, 0x67, 0x12, 0xde, 0x65, 0xbb, 0xdc, 0x4c, 0xc6, 0x20, 0xae, 0x6e,
	0xae, 0xfa, 0x61, 0x26, 0xe7, 0xda, 0xe1, 0x1c, 0xc4, 0x94, 0xbe, 0x20, 0xde, 0x45, 0x9f, 0xbf,
	0xd0, 0x44, 0x71, 0x0b, 0xcd, 0x55, 0xdf, 0x77, 0xe2, 0x61, 0x73, 0xd2, 0xd3, 0x73, 0xa1, 0xf3,
	0x17, 0x5b, 0xea, 0xb3, 0xd8, 0x4f, 0x4f, 0xd1, 0x7b, 0xdb, 0x02, 0x3c, 0x5f, 0x35, 0xa8, 0xf2,
	0x59, 0x07, 0x97, 0x50, 0x3e, 0xf9, 0x94, 0xa1, 0x49, 0x5e, 0x0c, 0x7c, 0x1e, 0xf0, 0x48, 0xb8,
	0x59, 0x92, 0xe4, 0x65, 0x6c, 0x19, 0xe0, 0x6f, 0xa1, 0x6b, 0x77, 0x40, 0x8d, 0xef, 0xd5, 0x4b,
	0xf4, 0x1f, 0x60, 0xb8, 0x68, 0x29, 0x13, 0x43, 0x9e, 0x82, 0xd4, 0xd0, 0xc2, 0xb7, 0xe0, 0x48,
	0x3d, 0x50, 0x54, 0xe8, 0x02, 0xf7, 0x98, 0x07, 0x47, 0x19, 0x98, 0x8b, 0x0c, 0x8e, 0x54, 0x53,
	0xa6, 0x5e, 0x4d, 0x5f, 0xbb, 0x0d, 0x92, 0xfc, 0xd2, 0x44, 0xd7, 0xc7, 0x65, 0x49, 0x7b, 0xf5,
	0x1b, 0x28, 0xdf, 0x00, 0x19, 0x05, 0xaa, 0x68, 0x92, 0xdc, 0xca, 0x5c, 0xf5, 0x93, 0x09, 0x65,
	0xb8, 0x40, 0x62, 0x0c, 0x81, 0x3f, 0x46, 0x33, 0x77, 0xa9, 0xfc, 0x26, 0x17, 0x09, 0x8b, 0x85,
	0xf3, 0xdb, 0xb6, 0x4b, 0x65, 0xb3, 0xc7, 0xc5, 0x19, 0x8f, 0xbf, 0x32, 0xd1, 0xc7, 0x8f, 0x42,
	0x2f, 0x73, 0x98, 0x12, 0x99, 0x27, 0x60, 0x74, 0xa8, 0x91, 0xac, 0x77, 0xdc, 0x48, 0xab, 0x80,
	0x8a, 0xe3, 0xe2, 0x30, 0x41, 0xc5, 0x47, 0xec, 0x05, 0xe3, 0x7d, 0x36, 0x62, 0x9b, 0x37, 0x6c,
	0xab, 0x60, 0xe0, 0x05, 0x34, 0x9b, 0xd6, 0x0f, 0xde, 0xbc, 0x19, 0x1f, 0xcd, 0xa3, 0x42, 0xdd,
	0x75, 0x21, 0xd4, 0x27, 0x96, 0x3e, 0xb1, 0xad, 0xa2, 0x51, 0xfd, 0xc3, 0xe7, 0xd0, 0x87, 0x19,
	0x79, 0x40, 0x1c, 0xfa, 0x2e, 0xe0, 0xd7, 0x39, 0x54, 0x1c, 0xb7, 0x72, 0xf0, 0x66, 0xe6, 0x65,
	0xaf, 0x58, 0xa6, 0xf6, 0x8d, 0xb7, 0x8c, 0x4a, 0x7a, 0xa5, 0xf4, 0x0b, 0xeb, 0xa4, 0xfe, 0x4f,
	0x13, 0x2d, 0xa6, 0x2e, 0x64, 0xb8, 0x90, 0xa5, 0x24, 0x9a, 0x50, 0x46, 0x52, 0x6c, 0x32, 0x04,
	0x6e, 0x7f, 0x39, 0x31, 0x4b, 0x42, 0x09, 0x83, 0x7e, 0x96, 0xcb, 0xfe, 0x31, 0xca, 0x55, 0x2b,
	0xeb, 0x58, 0xa0, 0x4f, 0xeb, 0xa3, 0x56, 0xe2, 0xc6, 0xf1, 0x1e, 0x91, 0x91, 0xeb, 0x82, 0x94,
	0xed, 0x28, 0x08, 0x8e, 0x1d, 0xbc, 0x8b, 0xb6, 0xed, 0xfa, 0x47, 0x65, 0x0f, 0xda, 0x3e, 0xf3,
	0xd3, 0x17, 0x93, 0xd1, 0x9b, 0x5d, 0x75, 0xb1, 0xd6, 0x22, 0x5a, 0x40, 0xf9, 0xfb, 0xf5, 0x48,
	0x75, 0xab, 0x78, 0x06, 0x4d, 0xf7, 0x85, 0xaf, 0xe0, 0xc7, 0x7f, 0xfa, 0xdb, 0xcf, 0xad, 0xa5,
	0x9a, 0xb9, 0x5a, 0x2a, 0x0e, 0xbd, 0x7d, 0xad, 0x0d, 0xe3, 0xbe, 0xb4, 0x8c, 0x57, 0x56, 0xdc,
	0x3b, 0xf8, 0x2f, 0x39, 0xf4, 0x85, 0xcc, 0x49, 0xc3, 0xeb, 0x99, 0x5c, 0x5f, 0xb6, 0x3f, 0xec,
	0x49, 0x67, 0xb0, 0xf4, 0x57, 0xeb, 0xa4, 0xfe, 0xc6, 0x42, 0x33, 0xa9, 0x09, 0x2f, 0x37, 0x40,
	0x09, 0x1f, 0x0e, 0xc7, 0xca, 0xd0, 0x3c, 0x75, 0x90, 0x84, 0x06, 0x01, 0xf1, 0xa8, 0xa2, 0xa4,
	0x2d, 0x78, 0x6f, 0x8c, 0x3f, 0x91, 0x10, 0x80, 0xab, 0x69, 0x6f, 0x1d, 0x13, 0xd5, 0x05, 0x22,
	0x23, 0x6d, 0x04, 0xef, 0xd4, 0x79, 0x78, 0xa3, 0x37, 0x7d, 0xcf, 0xd9, 0x7f, 0xa6, 0x45, 0xac,
	0xe0, 0xef, 0xa2, 0xeb, 0xe9, 0x65, 0x08, 0x1c, 0x81, 0x1b, 0x8d, 0x2a, 0xf7, 0x35, 0x74, 0xc3,
	0xde, 0xb8, 0x52, 0xb9, 0xd1, 0x3b, 0xef, 0xaf, 0xa3, 0xdc, 0x66, 0x65, 0x13, 0xaf, 0xa2, 0x95,
	0x06, 0xa8, 0x48, 0x30, 0xf0, 0x48, 0xbf, 0x0b, 0x2c, 0x2e, 0x4f, 0x40, 0xb2, 0xa9, 0x89, 0x2f,
	0x09, 0xe3, 0x8a, 0xb4, 0x79, 0xc4, 0x3c, 0xa7, 0x85, 0xd1, 0xfc, 0x40, 0xde, 0x3c, 0x9a, 0x12,
	0x40, 0xbd, 0x58, 0xdd, 0x65, 0xbc, 0x34, 0x4e, 0xda, 0xf2, 0x0f, 0xf6, 0x76, 0x7e, 0x38, 0xa4,
	0xef, 0xef, 0x72, 0xe8, 0x83, 0xec, 0x4d, 0x8a, 0xab, 0x93, 0x0b, 0x7c, 0xba, 0xcf, 0xec, 0x8d,
	0xb7, 0x8a, 0x49, 0xc7, 0xef, 0x8d, 0x75, 0x52, 0xff, 0x89, 0x95, 0x3d, 0x7e, 0x0b, 0xf7, 0x7c,
	0xa9, 0x62, 0x4d, 0x53, 0x60, 0x69, 0x3f, 0x4d, 0xf8, 0xd1, 0x23, 0x17, 0x68, 0xa3, 0xcb, 0x99,
	0xa2, 0x3e, 0xf3, 0x59, 0x87, 0x44, 0x21, 0x51, 0x9c, 0x54, 0x2b, 0x03, 0x67, 0x87, 0x3c, 0xcb,
	0x78, 0x8e, 0x3c, 0x23, 0x2e, 0x65, 0xa4, 0x05, 0x24, 0x92, 0xe0, 0x91, 0x36, 0x17, 0x24, 0xa4,
	0x1d, 0x9f, 0xc5, 0x19, 0x9d, 0xfd, 0x20, 0x91, 0x1a, 0xae, 0x94, 0x7a, 0x1b, 0xd5, 0xed, 0xdb,
	0x57, 0x4a, 0x7d, 0xf9, 0xe5, 0xc7, 0x6a, 0x68, 0xe3, 0x49, 0xc6, 0xf3, 0xef, 0x16, 0xba, 0x7e,
	0xf9, 0x93, 0x06, 0xd7, 0xb2, 0xdf, 0xad, 0x26, 0x79, 0x3c, 0xd9, 0x1f, 0x8c, 0xbc, 0x08, 0xed,
	0xea, 0xef, 0x3e, 0xa5, 0x7f, 0x99, 0x27, 0xf5, 0xdf, 0x8e, 0x5b, 0x98, 0x09, 0xf4, 0xb8, 0x49,
	0xdd, 0x4c, 0xcc, 0x72, 0xdc, 0x64, 0xf6, 0x7d, 0xd5, 0x8d, 0x7b, 0xbe, 0xe3, 0x1f, 0x02, 0x23,
	0xc9, 0x83, 0x6b, 0xff, 0xa6, 0xd6, 0x64, 0x13, 0x57, 0x51, 0x25, 0x23, 0x65, 0xea, 0x44, 0xa2,
	0x18, 0xf9, 0x82, 0x4a, 0xe3, 0x77, 0x60, 0xa9, 0x66, 0xae, 0xda, 0x93, 0x0d, 0x8a, 0x9d, 0x7b,
	0x69, 0x19, 0x5b, 0xbf, 0xcf, 0x9f, 0xd4, 0x7f, 0x9a, 0x47, 0xb9, 0xaa, 0x53, 0xc1, 0xcf, 0xd1,
	0x17, 0xb3, 0x2a, 0xa9, 0x1f, 0xec, 0xe1, 0xbb, 0x07, 0x82, 0x1f, 0xfa, 0x1e, 0xc8, 0x74, 0xb7,
	0x13, 0xca, 0x3c, 0xa2, 0x75, 0x25, 0x3c, 0x04, 0x91, 0xa0, 0x13, 0x9e, 0x0c, 0x76, 0x16, 0x03,
	0xa7, 0xc3, 0xee, 0x54, 0xa7, 0xd7, 0x9d, 0x8a, 0x53, 0x59, 0x35, 0xad, 0xea, 0xfc, 0x90, 0x43,
	0xf9, 0xb9, 0xe4, 0xac, 0x36, 0x72, 0xd2, 0x68, 0xea, 0x05, 0x52, 0xc1, 0xdf, 0x41, 0x8f, 0xb3,
	0x16, 0x48, 0xd2, 0xc9, 0x2d, 0xee, 0x1d, 0xeb, 0x25, 0xd2, 0xa3, 0x41, 0x9b, 0x8b, 0x1e, 0x55,
	0x9a, 0x2f, 0x2e, 0x88, 0xc7, 0x21, 0xd9, 0x2c, 0x3d, 0xaa, 0xdc, 0x84, 0x7f, 0x38, 0x0a, 0x93,
	0x15, 0x99, 0xc6, 0x3a, 0x8d, 0x7b, 0x3a, 0xc1, 0xba, 0x7e, 0x36, 0x8d, 0x4f, 0x30, 0x00, 0x4a,
	0xa7, 0x52, 0xc6, 0x56, 0xfd, 0xde, 0xfe, 0x49, 0xcc, 0x87, 0x07, 0x4c, 0xf9, 0x34, 0x90, 0x4e,
	0xe3, 0x40, 0xa3, 0x6d, 0xe0, 0x3d, 0x74, 0x67, 0x14, 0x4d, 0xfb, 0x9f, 0x41, 0x75, 0xe9, 0x21,
	0x90, 0x10, 0x44, 0xcf, 0x97, 0x52, 0x13, 0xa4, 0xb8, 0xe6, 0x0d, 0xa4, 0x3c, 0xb7, 0x1b, 0x9d,
	0xc6, 0xdb, 0x6f, 0xd0, 0xc6, 0xd7, 0x51, 0xee, 0x46, 0xa5, 0x82, 0x6f, 0xa3, 0x5b, 0xe7, 0x43,
	0x28, 0x23, 0x11, 0x1b, 0x30, 0x00, 0x42, 0x70, 0x41, 0xb8, 0xeb, 0x46, 0x42, 0xd3, 0x95, 0x20,
	0x4a, 0x10, 0x87, 0x20, 0x88, 0xf4, 0x3d, 0x70, 0x9e, 0xfc, 0xd7, 0x44, 0xff, 0x36, 0x07, 0x6d,
	0xf6, 0x0f, 0xb3, 0x90, 0xc3, 0x3f, 0x33, 0xeb, 0x69, 0x91, 0x3c, 0x4b, 0x66, 0x39, 0x28, 0x49,
	0xea, 0x9a, 0x04, 0x48, 0x25, 0xfc, 0x38, 0x9b, 0xf6, 0x8f, 0x54, 0x57, 0x13, 0xe5, 0xc6, 0xfd,
	0xac, 0xd9, 0x90, 0x0e, 0x79, 0xa8, 0xfb, 0xe5, 0xcc, 0xa0, 0x99, 0x08, 0x05, 0x8f, 0x53, 0xb4,
	0x79, 0x10, 0xf0, 0x7e, 0xc2, 0x87, 0x2e, 0x81, 0x0b, 0xff, 0xfb, 0x89, 0x87, 0xfe, 0x32, 0x46,
	0xda, 0x01, 0xef, 0x3b, 0x2b, 0x53, 0xd5, 0x42, 0xdc, 0xec, 0x91, 0xea, 0xd6, 0x66, 0xe3, 0x9f,
	0x26, 0xf8, 0x0b, 0x60, 0x5b, 0x35, 0x74, 0x2d, 0x9d, 0x0a, 0xbc, 0x78, 0x47, 0x50, 0xa6, 0x24,
	0x89, 0xff, 0x4b, 0x39, 0x46, 0x76, 0xb2, 0x94, 0x30, 0x4e, 0x8d, 0x71, 0x27, 0x27, 0xb6, 0xbb,
	0xe6, 0x81, 0xf1, 0x24, 0xeb, 0x07, 0x9a, 0x1f, 0x99, 0xc6, 0x4b, 0xd3, 0x78, 0x65, 0x1a, 0xbf,
	0x31, 0x8d, 0x3f, 0x9b, 0xc6, 0xff, 0x4c, 0xe3, 0x8f, 0x96, 0xd1, 0xca, 0xc7, 0x5b, 0x64, 0xe3,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x9c, 0xb3, 0xfd, 0x12, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountApplicationServiceClient is the client API for AccountApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountApplicationServiceClient interface {
	// CreateAccountApplication creates a new account application
	CreateAccountApplication(ctx context.Context, in *CreateAccountApplicationRequest, opts ...grpc.CallOption) (*CreateAccountApplicationResponse, error)
	// GetAccountApplication retrieves the details of an account application, selected by its id.
	GetAccountApplication(ctx context.Context, in *GetAccountApplicationRequest, opts ...grpc.CallOption) (*AccountApplication, error)
	// GetAccountApplications returns a list containing up to 20 accounts.
	GetAccountApplications(ctx context.Context, in *GetAccountApplicationsRequest, opts ...grpc.CallOption) (*GetAccountApplicationsResponse, error)
	// UpdateAccountApplication status updates the status.
	UpdateAccountApplicationStatus(ctx context.Context, in *UpdateAccountApplicationStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type accountApplicationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountApplicationServiceClient(cc *grpc.ClientConn) AccountApplicationServiceClient {
	return &accountApplicationServiceClient{cc}
}

func (c *accountApplicationServiceClient) CreateAccountApplication(ctx context.Context, in *CreateAccountApplicationRequest, opts ...grpc.CallOption) (*CreateAccountApplicationResponse, error) {
	out := new(CreateAccountApplicationResponse)
	err := c.cc.Invoke(ctx, "/accountapplications.AccountApplicationService/CreateAccountApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApplicationServiceClient) GetAccountApplication(ctx context.Context, in *GetAccountApplicationRequest, opts ...grpc.CallOption) (*AccountApplication, error) {
	out := new(AccountApplication)
	err := c.cc.Invoke(ctx, "/accountapplications.AccountApplicationService/GetAccountApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApplicationServiceClient) GetAccountApplications(ctx context.Context, in *GetAccountApplicationsRequest, opts ...grpc.CallOption) (*GetAccountApplicationsResponse, error) {
	out := new(GetAccountApplicationsResponse)
	err := c.cc.Invoke(ctx, "/accountapplications.AccountApplicationService/GetAccountApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApplicationServiceClient) UpdateAccountApplicationStatus(ctx context.Context, in *UpdateAccountApplicationStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/accountapplications.AccountApplicationService/UpdateAccountApplicationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountApplicationServiceServer is the server API for AccountApplicationService service.
type AccountApplicationServiceServer interface {
	// CreateAccountApplication creates a new account application
	CreateAccountApplication(context.Context, *CreateAccountApplicationRequest) (*CreateAccountApplicationResponse, error)
	// GetAccountApplication retrieves the details of an account application, selected by its id.
	GetAccountApplication(context.Context, *GetAccountApplicationRequest) (*AccountApplication, error)
	// GetAccountApplications returns a list containing up to 20 accounts.
	GetAccountApplications(context.Context, *GetAccountApplicationsRequest) (*GetAccountApplicationsResponse, error)
	// UpdateAccountApplication status updates the status.
	UpdateAccountApplicationStatus(context.Context, *UpdateAccountApplicationStatusRequest) (*empty.Empty, error)
}

// UnimplementedAccountApplicationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountApplicationServiceServer struct {
}

func (*UnimplementedAccountApplicationServiceServer) CreateAccountApplication(ctx context.Context, req *CreateAccountApplicationRequest) (*CreateAccountApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountApplication not implemented")
}
func (*UnimplementedAccountApplicationServiceServer) GetAccountApplication(ctx context.Context, req *GetAccountApplicationRequest) (*AccountApplication, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountApplication not implemented")
}
func (*UnimplementedAccountApplicationServiceServer) GetAccountApplications(ctx context.Context, req *GetAccountApplicationsRequest) (*GetAccountApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountApplications not implemented")
}
func (*UnimplementedAccountApplicationServiceServer) UpdateAccountApplicationStatus(ctx context.Context, req *UpdateAccountApplicationStatusRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountApplicationStatus not implemented")
}

func RegisterAccountApplicationServiceServer(s *grpc.Server, srv AccountApplicationServiceServer) {
	s.RegisterService(&_AccountApplicationService_serviceDesc, srv)
}

func _AccountApplicationService_CreateAccountApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApplicationServiceServer).CreateAccountApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountapplications.AccountApplicationService/CreateAccountApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApplicationServiceServer).CreateAccountApplication(ctx, req.(*CreateAccountApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApplicationService_GetAccountApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApplicationServiceServer).GetAccountApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountapplications.AccountApplicationService/GetAccountApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApplicationServiceServer).GetAccountApplication(ctx, req.(*GetAccountApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApplicationService_GetAccountApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApplicationServiceServer).GetAccountApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountapplications.AccountApplicationService/GetAccountApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApplicationServiceServer).GetAccountApplications(ctx, req.(*GetAccountApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountApplicationService_UpdateAccountApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountApplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountApplicationServiceServer).UpdateAccountApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accountapplications.AccountApplicationService/UpdateAccountApplicationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountApplicationServiceServer).UpdateAccountApplicationStatus(ctx, req.(*UpdateAccountApplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountApplicationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accountapplications.AccountApplicationService",
	HandlerType: (*AccountApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountApplication",
			Handler:    _AccountApplicationService_CreateAccountApplication_Handler,
		},
		{
			MethodName: "GetAccountApplication",
			Handler:    _AccountApplicationService_GetAccountApplication_Handler,
		},
		{
			MethodName: "GetAccountApplications",
			Handler:    _AccountApplicationService_GetAccountApplications_Handler,
		},
		{
			MethodName: "UpdateAccountApplicationStatus",
			Handler:    _AccountApplicationService_UpdateAccountApplicationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openbank/openbank/v1/accountapplications/all.proto",
}
