// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openbank/openbank/v1/card/all.proto

package card

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	types "github.com/openbank/openbank/v1/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Card holds all details about a card.
type Card struct {
	// ID is a unique identifier of a card.
	ID string `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	// Account is the ID of the account associated with the card.
	Account string `protobuf:"bytes,2,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	// OwnerName is the name of the card owner.
	OwnerName string `protobuf:"bytes,3,opt,name=OwnerName,json=owner_name,proto3" json:"OwnerName,omitempty"`
	// ContactNumber is the contact number of the card owner.
	ContactNumber string `protobuf:"bytes,4,opt,name=ContactNumber,json=contact_number,proto3" json:"ContactNumber,omitempty"`
	// FirstName is the first name of card owner.
	FirstName string `protobuf:"bytes,5,opt,name=FirstName,json=first_name,proto3" json:"FirstName,omitempty"`
	// LastName is the last name of the card owner.
	LastName string `protobuf:"bytes,6,opt,name=LastName,json=last_name,proto3" json:"LastName,omitempty"`
	// Expiry is an expiry date of the card.
	Expiry *timestamp.Timestamp `protobuf:"bytes,7,opt,name=Expiry,json=expiry,proto3" json:"Expiry,omitempty"`
	// Status is the status of the card.
	Status types.CardStatus `protobuf:"varint,8,opt,name=Status,json=status,proto3,enum=types.CardStatus" json:"Status,omitempty"`
	// AccessStatus is the access status of the card.
	AccessStatus         types.CardAccessStatus `protobuf:"varint,9,opt,name=AccessStatus,json=access_status,proto3,enum=types.CardAccessStatus" json:"AccessStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{0}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Card) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Card) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *Card) GetContactNumber() string {
	if m != nil {
		return m.ContactNumber
	}
	return ""
}

func (m *Card) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Card) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Card) GetExpiry() *timestamp.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *Card) GetStatus() types.CardStatus {
	if m != nil {
		return m.Status
	}
	return types.CardStatus_UnknownCardStatus
}

func (m *Card) GetAccessStatus() types.CardAccessStatus {
	if m != nil {
		return m.AccessStatus
	}
	return types.CardAccessStatus_UnknownCardAccessStatus
}

// CardAttribute hold all detail about card attribute
type CardAttribute struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	CardID               string   `protobuf:"bytes,2,opt,name=CardID,json=card_id,proto3" json:"CardID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CardAttribute) Reset()         { *m = CardAttribute{} }
func (m *CardAttribute) String() string { return proto.CompactTextString(m) }
func (*CardAttribute) ProtoMessage()    {}
func (*CardAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{1}
}

func (m *CardAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardAttribute.Unmarshal(m, b)
}
func (m *CardAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardAttribute.Marshal(b, m, deterministic)
}
func (m *CardAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardAttribute.Merge(m, src)
}
func (m *CardAttribute) XXX_Size() int {
	return xxx_messageInfo_CardAttribute.Size(m)
}
func (m *CardAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_CardAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_CardAttribute proto.InternalMessageInfo

func (m *CardAttribute) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CardAttribute) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *CardAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CardAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CardAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// GetCardRequest is the request envelope to retrieve card information.
type GetCardRequest struct {
	// CardToken is the identifier to get the card information.
	CardToken            string   `protobuf:"bytes,1,opt,name=CardToken,json=card_token,proto3" json:"CardToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCardRequest) Reset()         { *m = GetCardRequest{} }
func (m *GetCardRequest) String() string { return proto.CompactTextString(m) }
func (*GetCardRequest) ProtoMessage()    {}
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{2}
}

func (m *GetCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCardRequest.Unmarshal(m, b)
}
func (m *GetCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCardRequest.Marshal(b, m, deterministic)
}
func (m *GetCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCardRequest.Merge(m, src)
}
func (m *GetCardRequest) XXX_Size() int {
	return xxx_messageInfo_GetCardRequest.Size(m)
}
func (m *GetCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCardRequest proto.InternalMessageInfo

func (m *GetCardRequest) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

// UpdateCardStatusRequest is the request envelope to update card status.
type UpdateCardStatusRequest struct {
	// CardToken is the identifier to get the card information.
	CardToken string `protobuf:"bytes,1,opt,name=CardToken,json=card_token,proto3" json:"CardToken,omitempty"`
	// Status is the new card status.
	Status               types.CardStatus `protobuf:"varint,2,opt,name=Status,json=status,proto3,enum=types.CardStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateCardStatusRequest) Reset()         { *m = UpdateCardStatusRequest{} }
func (m *UpdateCardStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCardStatusRequest) ProtoMessage()    {}
func (*UpdateCardStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{3}
}

func (m *UpdateCardStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCardStatusRequest.Unmarshal(m, b)
}
func (m *UpdateCardStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCardStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCardStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCardStatusRequest.Merge(m, src)
}
func (m *UpdateCardStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCardStatusRequest.Size(m)
}
func (m *UpdateCardStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCardStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCardStatusRequest proto.InternalMessageInfo

func (m *UpdateCardStatusRequest) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

func (m *UpdateCardStatusRequest) GetStatus() types.CardStatus {
	if m != nil {
		return m.Status
	}
	return types.CardStatus_UnknownCardStatus
}

// UpdateCardAccessStatusRequest is the request envelope to update card access status.
type UpdateCardAccessStatusRequest struct {
	// CardToken is the identifier to get the card information.
	CardToken string `protobuf:"bytes,1,opt,name=CardToken,json=card_token,proto3" json:"CardToken,omitempty"`
	// AccessStatus is the new card access status.
	AccessStatus         types.CardAccessStatus `protobuf:"varint,2,opt,name=AccessStatus,json=access_status,proto3,enum=types.CardAccessStatus" json:"AccessStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateCardAccessStatusRequest) Reset()         { *m = UpdateCardAccessStatusRequest{} }
func (m *UpdateCardAccessStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCardAccessStatusRequest) ProtoMessage()    {}
func (*UpdateCardAccessStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{4}
}

func (m *UpdateCardAccessStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCardAccessStatusRequest.Unmarshal(m, b)
}
func (m *UpdateCardAccessStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCardAccessStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCardAccessStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCardAccessStatusRequest.Merge(m, src)
}
func (m *UpdateCardAccessStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCardAccessStatusRequest.Size(m)
}
func (m *UpdateCardAccessStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCardAccessStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCardAccessStatusRequest proto.InternalMessageInfo

func (m *UpdateCardAccessStatusRequest) GetCardToken() string {
	if m != nil {
		return m.CardToken
	}
	return ""
}

func (m *UpdateCardAccessStatusRequest) GetAccessStatus() types.CardAccessStatus {
	if m != nil {
		return m.AccessStatus
	}
	return types.CardAccessStatus_UnknownCardAccessStatus
}

// Result is result of the update operation.
type Result struct {
	// Success is a boolean indicating the success of the operation.
	Success bool `protobuf:"varint,1,opt,name=Success,json=success,proto3" json:"Success,omitempty"`
	// ErrorCode is the code of the error.
	ErrorCode string `protobuf:"bytes,2,opt,name=ErrorCode,json=error_code,proto3" json:"ErrorCode,omitempty"`
	// ErrorMessage is the message of the error.
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=ErrorMessage,json=error_message,proto3" json:"ErrorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{5}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Result) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *Result) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// CreateCardRequest is the request data to create new card
type CreateCardRequest struct {
	// Account is the ID of the account associated with the card.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// ContactNumber is the contact number of the card owner.
	ContactNumber string `protobuf:"bytes,2,opt,name=ContactNumber,json=contact_number,proto3" json:"ContactNumber,omitempty"`
	// FirstName is the first name of card owner.
	FirstName string `protobuf:"bytes,3,opt,name=FirstName,json=first_name,proto3" json:"FirstName,omitempty"`
	// LastName is the last name of the card owner.
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,json=last_name,proto3" json:"LastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardRequest) Reset()         { *m = CreateCardRequest{} }
func (m *CreateCardRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCardRequest) ProtoMessage()    {}
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{6}
}

func (m *CreateCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardRequest.Unmarshal(m, b)
}
func (m *CreateCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardRequest.Marshal(b, m, deterministic)
}
func (m *CreateCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardRequest.Merge(m, src)
}
func (m *CreateCardRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCardRequest.Size(m)
}
func (m *CreateCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardRequest proto.InternalMessageInfo

func (m *CreateCardRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateCardRequest) GetContactNumber() string {
	if m != nil {
		return m.ContactNumber
	}
	return ""
}

func (m *CreateCardRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateCardRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

// CreateCardResponse is the response for CreateCardRequest
type CreateCardResponse struct {
	CardID               string   `protobuf:"bytes,1,opt,name=CardID,json=card_id,proto3" json:"CardID,omitempty"`
	Expiry               string   `protobuf:"bytes,2,opt,name=Expiry,json=expiry,proto3" json:"Expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardResponse) Reset()         { *m = CreateCardResponse{} }
func (m *CreateCardResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCardResponse) ProtoMessage()    {}
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{7}
}

func (m *CreateCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardResponse.Unmarshal(m, b)
}
func (m *CreateCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardResponse.Marshal(b, m, deterministic)
}
func (m *CreateCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardResponse.Merge(m, src)
}
func (m *CreateCardResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCardResponse.Size(m)
}
func (m *CreateCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardResponse proto.InternalMessageInfo

func (m *CreateCardResponse) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *CreateCardResponse) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

type CreateCardAttributeRequest struct {
	CardID               string   `protobuf:"bytes,1,opt,name=CardID,json=card_id,proto3" json:"CardID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardAttributeRequest) Reset()         { *m = CreateCardAttributeRequest{} }
func (m *CreateCardAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCardAttributeRequest) ProtoMessage()    {}
func (*CreateCardAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{8}
}

func (m *CreateCardAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardAttributeRequest.Unmarshal(m, b)
}
func (m *CreateCardAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardAttributeRequest.Marshal(b, m, deterministic)
}
func (m *CreateCardAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardAttributeRequest.Merge(m, src)
}
func (m *CreateCardAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCardAttributeRequest.Size(m)
}
func (m *CreateCardAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardAttributeRequest proto.InternalMessageInfo

func (m *CreateCardAttributeRequest) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

func (m *CreateCardAttributeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCardAttributeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateCardAttributeRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateCardAttributeResponse struct {
	AttributeID          string   `protobuf:"bytes,1,opt,name=AttributeID,json=attribute_id,proto3" json:"AttributeID,omitempty"`
	CardID               string   `protobuf:"bytes,2,opt,name=CardID,json=card_id,proto3" json:"CardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCardAttributeResponse) Reset()         { *m = CreateCardAttributeResponse{} }
func (m *CreateCardAttributeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCardAttributeResponse) ProtoMessage()    {}
func (*CreateCardAttributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{9}
}

func (m *CreateCardAttributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCardAttributeResponse.Unmarshal(m, b)
}
func (m *CreateCardAttributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCardAttributeResponse.Marshal(b, m, deterministic)
}
func (m *CreateCardAttributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCardAttributeResponse.Merge(m, src)
}
func (m *CreateCardAttributeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCardAttributeResponse.Size(m)
}
func (m *CreateCardAttributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCardAttributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCardAttributeResponse proto.InternalMessageInfo

func (m *CreateCardAttributeResponse) GetAttributeID() string {
	if m != nil {
		return m.AttributeID
	}
	return ""
}

func (m *CreateCardAttributeResponse) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

type DeleteCardRequest struct {
	CardID               string   `protobuf:"bytes,1,opt,name=CardID,json=card_id,proto3" json:"CardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCardRequest) Reset()         { *m = DeleteCardRequest{} }
func (m *DeleteCardRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCardRequest) ProtoMessage()    {}
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{10}
}

func (m *DeleteCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCardRequest.Unmarshal(m, b)
}
func (m *DeleteCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCardRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCardRequest.Merge(m, src)
}
func (m *DeleteCardRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCardRequest.Size(m)
}
func (m *DeleteCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCardRequest proto.InternalMessageInfo

func (m *DeleteCardRequest) GetCardID() string {
	if m != nil {
		return m.CardID
	}
	return ""
}

type GetUserCardsRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserCardsRequest) Reset()         { *m = GetUserCardsRequest{} }
func (m *GetUserCardsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserCardsRequest) ProtoMessage()    {}
func (*GetUserCardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{11}
}

func (m *GetUserCardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserCardsRequest.Unmarshal(m, b)
}
func (m *GetUserCardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserCardsRequest.Marshal(b, m, deterministic)
}
func (m *GetUserCardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserCardsRequest.Merge(m, src)
}
func (m *GetUserCardsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserCardsRequest.Size(m)
}
func (m *GetUserCardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserCardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserCardsRequest proto.InternalMessageInfo

func (m *GetUserCardsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserCardsResponse struct {
	Result               []*Card  `protobuf:"bytes,1,rep,name=Result,json=result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserCardsResponse) Reset()         { *m = GetUserCardsResponse{} }
func (m *GetUserCardsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserCardsResponse) ProtoMessage()    {}
func (*GetUserCardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d7396a66589e9e, []int{12}
}

func (m *GetUserCardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserCardsResponse.Unmarshal(m, b)
}
func (m *GetUserCardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserCardsResponse.Marshal(b, m, deterministic)
}
func (m *GetUserCardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserCardsResponse.Merge(m, src)
}
func (m *GetUserCardsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserCardsResponse.Size(m)
}
func (m *GetUserCardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserCardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserCardsResponse proto.InternalMessageInfo

func (m *GetUserCardsResponse) GetResult() []*Card {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Card)(nil), "card.Card")
	proto.RegisterType((*CardAttribute)(nil), "card.CardAttribute")
	proto.RegisterType((*GetCardRequest)(nil), "card.GetCardRequest")
	proto.RegisterType((*UpdateCardStatusRequest)(nil), "card.UpdateCardStatusRequest")
	proto.RegisterType((*UpdateCardAccessStatusRequest)(nil), "card.UpdateCardAccessStatusRequest")
	proto.RegisterType((*Result)(nil), "card.Result")
	proto.RegisterType((*CreateCardRequest)(nil), "card.CreateCardRequest")
	proto.RegisterType((*CreateCardResponse)(nil), "card.CreateCardResponse")
	proto.RegisterType((*CreateCardAttributeRequest)(nil), "card.CreateCardAttributeRequest")
	proto.RegisterType((*CreateCardAttributeResponse)(nil), "card.CreateCardAttributeResponse")
	proto.RegisterType((*DeleteCardRequest)(nil), "card.DeleteCardRequest")
	proto.RegisterType((*GetUserCardsRequest)(nil), "card.GetUserCardsRequest")
	proto.RegisterType((*GetUserCardsResponse)(nil), "card.GetUserCardsResponse")
}

func init() {
	proto.RegisterFile("github.com/openbank/openbank/v1/card/all.proto", fileDescriptor_41d7396a66589e9e)
}

var fileDescriptor_41d7396a66589e9e = []byte{
	// 1843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xcf, 0x6f, 0x1c, 0x49,
	0x15, 0xee, 0xee, 0x99, 0x4c, 0xec, 0x8a, 0x1d, 0x92, 0x4a, 0xe4, 0xcc, 0x76, 0x36, 0xd9, 0x62,
	0xb2, 0xda, 0xcc, 0x9a, 0xa4, 0x67, 0x3c, 0x9b, 0x95, 0xc0, 0x82, 0x5d, 0x26, 0x8e, 0x37, 0x89,
	0xc9, 0x66, 0xad, 0x49, 0x36, 0x42, 0x7b, 0xb1, 0x6a, 0xba, 0x6b, 0x3c, 0x4d, 0x7a, 0xba, 0x9a,
	0xaa, 0x6a, 0x3b, 0xc3, 0x0a, 0xb4, 0x02, 0xa4, 0x8d, 0x04, 0x42, 0xd1, 0x70, 0x80, 0x03, 0xdc,
	0x90, 0x90, 0xe0, 0x8a, 0x10, 0xe2, 0xc0, 0x05, 0x89, 0x13, 0x2b, 0x21, 0x71, 0x80, 0x3f, 0x00,
	0x10, 0x9c, 0xb8, 0x22, 0x4e, 0xa8, 0xaa, 0xba, 0x7b, 0x7a, 0xa6, 0xdb, 0x76, 0x62, 0x24, 0x24,
	0x4e, 0x89, 0xeb, 0xbd, 0xf7, 0xd5, 0x7b, 0xdf, 0xfb, 0x51, 0xaf, 0x07, 0x38, 0xbb, 0xbe, 0x18,
	0xc6, 0x7d, 0xc7, 0xa5, 0xa3, 0x16, 0x8d, 0x48, 0xd8, 0xc7, 0xe1, 0xe3, 0xe9, 0x7f, 0xf6, 0xd6,
	0x5a, 0x2e, 0x66, 0x5e, 0x0b, 0x07, 0x81, 0x13, 0x31, 0x2a, 0x28, 0xac, 0xca, 0xbf, 0xed, 0x57,
	0x76, 0x29, 0xdd, 0x0d, 0x48, 0x4b, 0x9d, 0xf5, 0xe3, 0x41, 0x4b, 0xf8, 0x23, 0xc2, 0x05, 0x1e,
	0x45, 0x5a, 0xcd, 0x7e, 0x39, 0x51, 0xc0, 0x91, 0xdf, 0xc2, 0x61, 0x48, 0x05, 0x16, 0x3e, 0x0d,
	0x79, 0x22, 0xbd, 0xa6, 0xfe, 0x71, 0xaf, 0xef, 0x92, 0xf0, 0x3a, 0xdf, 0xc7, 0xbb, 0xbb, 0x84,
	0xb5, 0x68, 0xa4, 0x34, 0x4a, 0xb4, 0x2f, 0xce, 0x5f, 0x46, 0x46, 0x91, 0x18, 0x27, 0xc2, 0xd6,
	0x51, 0xfe, 0x8b, 0x71, 0x44, 0xf8, 0x34, 0x80, 0xc6, 0x6f, 0x2b, 0xa0, 0xba, 0x81, 0x99, 0x07,
	0x6d, 0x60, 0xdd, 0xbd, 0x55, 0x37, 0x91, 0xd9, 0x5c, 0xbc, 0x09, 0x16, 0x8c, 0xba, 0xd1, 0x34,
	0xda, 0xc6, 0xb6, 0xd1, 0xb3, 0x7c, 0x0f, 0xbe, 0x0a, 0x4e, 0x76, 0x5d, 0x97, 0xc6, 0xa1, 0xa8,
	0x5b, 0x05, 0x85, 0x93, 0x58, 0x8b, 0xe0, 0xeb, 0x60, 0xf1, 0xbd, 0xfd, 0x90, 0xb0, 0xfb, 0x78,
	0x44, 0xea, 0x95, 0x82, 0x1e, 0xa0, 0x52, 0xb8, 0x13, 0xe2, 0x11, 0x81, 0x6b, 0x60, 0x79, 0x83,
	0x86, 0x02, 0xbb, 0xe2, 0x7e, 0x3c, 0xea, 0x13, 0x56, 0xaf, 0x16, 0xd4, 0x4f, 0xbb, 0x5a, 0x61,
	0x27, 0x54, 0x1a, 0x12, 0xfd, 0x1d, 0x9f, 0x71, 0xa1, 0xd0, 0x4f, 0x14, 0xd1, 0x07, 0x52, 0xa8,
	0xd1, 0xaf, 0x82, 0x85, 0x7b, 0x38, 0xd1, 0xac, 0x15, 0x34, 0x17, 0x03, 0x9c, 0x2a, 0xbe, 0x05,
	0x6a, 0x9b, 0x4f, 0x22, 0x9f, 0x8d, 0xeb, 0x27, 0x91, 0xd9, 0x3c, 0xd5, 0xb1, 0x1d, 0xcd, 0xad,
	0x93, 0x72, 0xeb, 0x3c, 0x4c, 0x13, 0x39, 0x03, 0x51, 0x23, 0xca, 0x0a, 0xbe, 0x09, 0x6a, 0x0f,
	0x04, 0x16, 0x31, 0xaf, 0x2f, 0x20, 0xb3, 0x79, 0xba, 0x73, 0xd6, 0x51, 0xf4, 0x3a, 0x92, 0x50,
	0x2d, 0x98, 0x35, 0xe3, 0xea, 0x0c, 0xde, 0x01, 0x4b, 0x5d, 0xd7, 0x25, 0x9c, 0x27, 0xc6, 0x8b,
	0xca, 0xf8, 0x42, 0xce, 0x38, 0x2f, 0x9e, 0x81, 0x58, 0xc6, 0x4a, 0xb2, 0xa3, 0x91, 0xd6, 0x6b,
	0x0b, 0xc6, 0x19, 0xa3, 0x6e, 0x34, 0x7e, 0x6d, 0x82, 0x65, 0x65, 0x27, 0x04, 0xf3, 0xfb, 0xb1,
	0x20, 0x87, 0xa6, 0xf3, 0x0a, 0xa8, 0x49, 0xe5, 0xbb, 0xb7, 0xca, 0xb2, 0x29, 0x0b, 0x7a, 0xc7,
	0xf7, 0xe0, 0x65, 0x50, 0x3d, 0x20, 0x91, 0x55, 0xc5, 0xdd, 0x65, 0x50, 0x7d, 0x38, 0x8e, 0x48,
	0x49, 0xe6, 0xaa, 0x32, 0x0e, 0x88, 0xc0, 0x89, 0x47, 0x38, 0x88, 0xcb, 0x72, 0x75, 0x62, 0x4f,
	0x0a, 0x32, 0xe7, 0x37, 0xc0, 0xe9, 0xdb, 0x44, 0x48, 0x8f, 0x7a, 0xe4, 0xab, 0x31, 0xe1, 0xaa,
	0x92, 0xe4, 0x9f, 0x0f, 0xe9, 0x63, 0x12, 0x96, 0xc4, 0x00, 0x94, 0x8f, 0x42, 0x4a, 0x33, 0x90,
	0x6f, 0x99, 0xe0, 0xc2, 0xfb, 0x91, 0x87, 0x05, 0x99, 0x92, 0xff, 0xe2, 0x70, 0xb9, 0x8c, 0x5a,
	0x2f, 0x90, 0xd1, 0xcc, 0x8b, 0x1f, 0x99, 0xe0, 0xd2, 0xd4, 0x8b, 0x7c, 0x16, 0x8f, 0xe1, 0xcb,
	0x7c, 0x99, 0x58, 0xff, 0x75, 0x99, 0x4c, 0x4c, 0x50, 0xeb, 0x11, 0x1e, 0x07, 0x42, 0xb6, 0xf4,
	0x83, 0x58, 0x29, 0x29, 0x2f, 0x16, 0x66, 0x8b, 0x80, 0x6b, 0x91, 0xf4, 0x76, 0x93, 0x31, 0xca,
	0x36, 0xa8, 0x47, 0x4a, 0x8a, 0x05, 0x10, 0x29, 0xdc, 0x71, 0xa9, 0x47, 0x60, 0x0b, 0x2c, 0x29,
	0xd5, 0x77, 0x09, 0xe7, 0x78, 0xb7, 0xac, 0x6e, 0x96, 0xb5, 0xf6, 0x48, 0x2b, 0x64, 0x4e, 0x7d,
	0x62, 0x82, 0xb3, 0x1b, 0x8c, 0x24, 0x9c, 0xe5, 0x78, 0x4a, 0x46, 0x4e, 0x69, 0x19, 0x83, 0x64,
	0xe8, 0xc8, 0x4a, 0x2d, 0x0c, 0x13, 0xeb, 0xc5, 0x86, 0x49, 0xe5, 0xb9, 0x87, 0x49, 0xf5, 0x90,
	0x61, 0x92, 0xc5, 0x43, 0x00, 0xcc, 0x87, 0xc3, 0x23, 0x1a, 0x72, 0x92, 0xeb, 0x39, 0xf3, 0xe0,
	0x9e, 0x6b, 0x64, 0xf3, 0xa8, 0x18, 0x42, 0x32, 0x73, 0xb2, 0x6b, 0x7e, 0x6e, 0x02, 0x7b, 0x7a,
	0x4f, 0xd6, 0xf8, 0x29, 0x7f, 0xcf, 0x75, 0x5f, 0xda, 0xe3, 0xd6, 0x11, 0x3d, 0x5e, 0x39, 0xaa,
	0xc7, 0xab, 0x47, 0xf5, 0xf8, 0x18, 0x5c, 0x2c, 0x75, 0x36, 0x61, 0xe7, 0x3a, 0x38, 0x95, 0x1d,
	0x96, 0xba, 0xbc, 0x84, 0x53, 0xf1, 0xce, 0x73, 0x0e, 0xb0, 0xec, 0xea, 0x2f, 0x82, 0xb3, 0xb7,
	0x48, 0x40, 0x66, 0xcb, 0xeb, 0x79, 0xe8, 0xc9, 0x10, 0x6e, 0x82, 0x73, 0xb7, 0x89, 0x78, 0x9f,
	0x13, 0x26, 0x6d, 0x78, 0x0e, 0x43, 0x9e, 0x95, 0x63, 0xc4, 0x9c, 0xb0, 0x3c, 0xc6, 0x7d, 0x70,
	0x7e, 0x16, 0x23, 0x89, 0xdc, 0x49, 0x3b, 0xb2, 0x6e, 0xa2, 0x4a, 0xf3, 0x54, 0x07, 0x38, 0xf2,
	0x76, 0xd5, 0xdd, 0xb3, 0xe9, 0x67, 0x4a, 0x2b, 0xc5, 0xeb, 0x7c, 0x17, 0x82, 0x53, 0x6a, 0x28,
	0x11, 0xb6, 0xe7, 0xbb, 0x04, 0xfe, 0xdb, 0x04, 0x60, 0xca, 0x30, 0xbc, 0x90, 0xc0, 0xcc, 0xf7,
	0x95, 0x5d, 0x2f, 0x0a, 0xb4, 0x27, 0x8d, 0x5f, 0x98, 0x93, 0xee, 0x0f, 0xcc, 0x64, 0x1b, 0xf8,
	0x94, 0x56, 0x40, 0x21, 0xd9, 0x47, 0x6a, 0xc5, 0x99, 0x3f, 0xd8, 0x7a, 0x1b, 0x54, 0x3a, 0xed,
	0x35, 0xf8, 0x59, 0xb0, 0x24, 0x0d, 0x90, 0x16, 0x7b, 0xb0, 0x09, 0x5e, 0xb3, 0x5f, 0xbd, 0xd2,
	0xf2, 0xc8, 0xc0, 0x0f, 0x7d, 0xbd, 0xc2, 0x48, 0xf5, 0xe2, 0x7d, 0xfd, 0x6b, 0x60, 0x15, 0xd4,
	0xde, 0xeb, 0xc6, 0x62, 0xd8, 0x81, 0x08, 0x5c, 0x1e, 0x0a, 0x11, 0xf1, 0xf5, 0x56, 0x0b, 0xc7,
	0x62, 0xe8, 0xf4, 0xc3, 0xc7, 0x8e, 0xa0, 0xca, 0xd2, 0xd9, 0x67, 0xbe, 0x20, 0xdf, 0xfc, 0xe3,
	0x5f, 0xbe, 0x6f, 0x2d, 0xaf, 0x9b, 0xab, 0x8d, 0x85, 0x74, 0x0b, 0x7b, 0x6a, 0x19, 0xcf, 0x2c,
	0x45, 0x0f, 0xfc, 0x9d, 0x05, 0xce, 0x95, 0x94, 0x17, 0x44, 0xf3, 0xc1, 0xce, 0xb7, 0x89, 0xfd,
	0xe9, 0x43, 0x34, 0x12, 0x5e, 0xfe, 0x6a, 0x4e, 0xba, 0xbf, 0x49, 0x79, 0x79, 0x69, 0x8e, 0x06,
	0x94, 0xd5, 0xa5, 0x7d, 0xb0, 0x68, 0xab, 0xa7, 0xb9, 0xfa, 0x12, 0x58, 0x51, 0x5c, 0x65, 0x77,
	0x64, 0xac, 0xad, 0x81, 0x96, 0x7d, 0xfd, 0x30, 0xd6, 0x0a, 0x6e, 0x1d, 0x83, 0xbe, 0x0b, 0x92,
	0x3e, 0x38, 0x5d, 0x62, 0x53, 0xc8, 0x1c, 0x91, 0x7f, 0xb7, 0xc0, 0xc9, 0xe4, 0x2d, 0x86, 0xe7,
	0x35, 0x35, 0xb3, 0x4f, 0xb3, 0x9d, 0xab, 0xcf, 0xc6, 0x2f, 0xad, 0x49, 0xf7, 0x99, 0x95, 0x32,
	0xd3, 0x23, 0x82, 0xf9, 0x64, 0x8f, 0xe8, 0xe0, 0xfd, 0x70, 0x40, 0xd9, 0x48, 0x2d, 0xae, 0xf6,
	0x9d, 0x54, 0xc4, 0x11, 0x0e, 0x02, 0xe4, 0x61, 0x81, 0xd1, 0x80, 0xd1, 0x11, 0xc2, 0x4a, 0xf7,
	0x1a, 0xe2, 0x24, 0x20, 0xae, 0x20, 0x1e, 0xea, 0x8f, 0x91, 0x18, 0x6a, 0x04, 0xfd, 0x08, 0xa2,
	0x31, 0x8d, 0x11, 0x8f, 0xa3, 0x28, 0xf0, 0x89, 0xe7, 0x6c, 0x6d, 0x48, 0x22, 0xdb, 0xf0, 0xf3,
	0xe0, 0x72, 0xe2, 0x0f, 0x22, 0x4f, 0x88, 0x1b, 0x4b, 0xd3, 0xe4, 0xc9, 0x1a, 0xc4, 0x41, 0x30,
	0x76, 0xa0, 0x0d, 0xea, 0xf6, 0x4a, 0x09, 0xa1, 0xb2, 0x72, 0xd7, 0x40, 0xe5, 0x46, 0xfb, 0x06,
	0x5c, 0x05, 0xcd, 0x1e, 0x11, 0x31, 0x0b, 0x89, 0x87, 0xf6, 0x87, 0x24, 0x54, 0x37, 0x33, 0xc2,
	0x69, 0xcc, 0x5c, 0x82, 0x7c, 0x8e, 0x42, 0x2a, 0xd0, 0x80, 0xc6, 0xa1, 0xe7, 0xf4, 0x3f, 0x03,
	0x5e, 0xcf, 0xc8, 0x7e, 0x05, 0x5c, 0x3a, 0x90, 0x6c, 0x46, 0xb0, 0xa7, 0xb8, 0x5e, 0x81, 0xe7,
	0x33, 0xa2, 0x3f, 0xcc, 0x1e, 0xfc, 0xaf, 0xe7, 0xa8, 0xfe, 0x61, 0x05, 0x2c, 0xe5, 0x27, 0x02,
	0x7c, 0x29, 0xe3, 0x7b, 0x7e, 0xd2, 0xd8, 0x76, 0x99, 0x28, 0x29, 0xcf, 0xdf, 0x5b, 0x93, 0xee,
	0x4f, 0xd2, 0x24, 0x5c, 0x9a, 0x65, 0x1a, 0xef, 0x61, 0x3f, 0xc0, 0xfd, 0x40, 0x33, 0xca, 0xe7,
	0x13, 0x31, 0x27, 0x46, 0x03, 0xca, 0x10, 0x8f, 0x88, 0xeb, 0x0f, 0x7c, 0x17, 0xc9, 0x01, 0x56,
	0xcc, 0x4c, 0x32, 0xd6, 0xb6, 0x1e, 0xe8, 0x44, 0xdc, 0x3b, 0x32, 0x11, 0xab, 0xa0, 0x69, 0xbf,
	0x56, 0x4c, 0x44, 0x59, 0x28, 0xff, 0x93, 0xc4, 0xd4, 0xe1, 0x4a, 0x96, 0x18, 0x19, 0x4c, 0xeb,
	0x43, 0x3d, 0xc3, 0xf3, 0xa9, 0xf9, 0xc4, 0x02, 0x67, 0xe6, 0x77, 0x49, 0x78, 0x49, 0xe7, 0xe0,
	0x80, 0x1d, 0xd3, 0x5e, 0xd2, 0x62, 0x3d, 0xcb, 0x1b, 0x1f, 0x5b, 0x93, 0xee, 0x9f, 0xd2, 0x99,
	0x01, 0xb5, 0x8d, 0xee, 0x0b, 0xbd, 0x91, 0xd9, 0xe7, 0x92, 0xb3, 0x8d, 0xe9, 0x99, 0x73, 0x8c,
	0xf8, 0xb7, 0x36, 0x75, 0x1e, 0xde, 0x3a, 0x32, 0x0f, 0x2f, 0x03, 0xdb, 0xae, 0x17, 0xf3, 0xa0,
	0xfd, 0x3d, 0xc6, 0x30, 0x41, 0xeb, 0xe6, 0xaa, 0x7d, 0x31, 0xa3, 0x52, 0x87, 0x70, 0x40, 0xa9,
	0xff, 0xd3, 0x02, 0x2b, 0xe5, 0x5b, 0x31, 0xbc, 0x32, 0xcf, 0x6a, 0xc9, 0xce, 0x3c, 0xc7, 0xed,
	0x8f, 0xad, 0x49, 0xf7, 0x6f, 0x29, 0xb7, 0x76, 0x9e, 0x5b, 0xbd, 0xf4, 0xa6, 0x74, 0xda, 0x87,
	0xc8, 0xfe, 0xaf, 0xa8, 0xbe, 0x2a, 0xa9, 0x6e, 0x4c, 0xe7, 0x76, 0x7e, 0xb5, 0x3f, 0x80, 0xf1,
	0x7f, 0x98, 0x00, 0x4c, 0x97, 0x9e, 0x74, 0x1b, 0x28, 0xac, 0x41, 0xf6, 0x4a, 0xe1, 0x83, 0x77,
	0x73, 0x14, 0x89, 0x71, 0xe3, 0xa7, 0xe6, 0xa4, 0xfb, 0xed, 0x94, 0xe3, 0x65, 0x6d, 0x97, 0x4c,
	0x6b, 0xdb, 0xde, 0x26, 0x6c, 0x84, 0x43, 0x12, 0x8a, 0x60, 0x8c, 0xbc, 0xbc, 0xc8, 0xd9, 0xba,
	0x22, 0x39, 0xba, 0x21, 0x19, 0xd0, 0x85, 0x9d, 0xe3, 0x25, 0x51, 0xf5, 0x9c, 0x63, 0x30, 0x70,
	0x6e, 0xf5, 0xec, 0xec, 0x34, 0xcd, 0xf5, 0xab, 0x5d, 0x79, 0x6a, 0x19, 0x37, 0x7f, 0x56, 0x9b,
	0x74, 0x3f, 0xae, 0x81, 0x4a, 0xc7, 0x91, 0x43, 0x69, 0x41, 0x3f, 0xb3, 0xdb, 0x77, 0xe1, 0xe7,
	0xb6, 0x19, 0xdd, 0xf3, 0x3d, 0xc2, 0x91, 0xab, 0x5f, 0x67, 0x1c, 0x7a, 0x48, 0x0e, 0x03, 0x44,
	0x23, 0xc2, 0xf4, 0xef, 0x2a, 0x88, 0x86, 0xd9, 0xab, 0x93, 0x25, 0xdf, 0xe9, 0x9c, 0x58, 0x73,
	0xda, 0x4e, 0x7b, 0xd5, 0xb4, 0x3a, 0x67, 0xb0, 0x7c, 0x7f, 0x5c, 0xa5, 0xdd, 0xfa, 0x0a, 0xa7,
	0xe1, 0x7a, 0xe1, 0xa4, 0xb7, 0x23, 0x0b, 0xaa, 0x0d, 0xbf, 0x0c, 0x1e, 0x95, 0x15, 0x94, 0xae,
	0x97, 0x3e, 0xf5, 0xc6, 0xb2, 0xa8, 0x46, 0x38, 0xd0, 0x8f, 0xa3, 0xac, 0x1d, 0xca, 0x90, 0x47,
	0x89, 0xae, 0xb4, 0x11, 0x16, 0xee, 0x50, 0x99, 0x90, 0x27, 0x91, 0x9e, 0xbb, 0x89, 0xad, 0xd3,
	0xbb, 0x27, 0x2f, 0x58, 0x83, 0x9b, 0x60, 0xe3, 0xe0, 0x0b, 0x32, 0x20, 0xf5, 0xb9, 0xe3, 0x87,
	0x3c, 0x9b, 0xd9, 0x57, 0x15, 0x01, 0x1e, 0x09, 0x85, 0x8f, 0x03, 0xee, 0xf4, 0xb6, 0x25, 0xda,
	0x1b, 0xf0, 0x2e, 0xb8, 0x5d, 0x44, 0x93, 0xfa, 0x53, 0xa8, 0x21, 0xde, 0x23, 0x28, 0x22, 0x6c,
	0xe4, 0x73, 0xee, 0x4b, 0xa6, 0x68, 0xda, 0x4b, 0xf9, 0x5e, 0x71, 0x7a, 0x2f, 0xde, 0x51, 0xbd,
	0x77, 0x40, 0xe5, 0xcd, 0x76, 0x1b, 0xbe, 0x0d, 0xbe, 0x30, 0x6b, 0x82, 0x43, 0x14, 0x87, 0x19,
	0x03, 0xea, 0xab, 0x11, 0x51, 0xd7, 0x8d, 0x99, 0xa4, 0x4b, 0x23, 0x72, 0xc2, 0xf6, 0x08, 0x43,
	0xdc, 0xf7, 0x88, 0xf3, 0xc1, 0xf7, 0x2c, 0xf0, 0x1d, 0x2b, 0x2b, 0xa9, 0x8f, 0xac, 0x85, 0x0a,
	0xfc, 0x46, 0x37, 0xf1, 0x91, 0xce, 0xa6, 0x95, 0x4b, 0x17, 0x18, 0xe1, 0x82, 0xf9, 0x0a, 0x5c,
	0x46, 0x13, 0x8b, 0xa1, 0xe4, 0xc5, 0x95, 0x9b, 0x98, 0x0a, 0x9e, 0x3b, 0xe8, 0xe1, 0x90, 0xe4,
	0x05, 0x32, 0xf0, 0x88, 0x51, 0x05, 0x39, 0xa0, 0x41, 0x40, 0xf7, 0x75, 0xf8, 0xf2, 0x46, 0xca,
	0xfc, 0xaf, 0x69, 0x0d, 0xf9, 0x95, 0x8c, 0x06, 0x01, 0xdd, 0x77, 0x9a, 0xd5, 0x8e, 0xda, 0x53,
	0x25, 0xc4, 0xfa, 0xa2, 0xfa, 0xdd, 0x4d, 0xb6, 0xe8, 0x4d, 0x02, 0x5a, 0x47, 0x3c, 0x52, 0xf0,
	0xf4, 0x23, 0x3f, 0x5d, 0x20, 0xe5, 0xa2, 0x04, 0x3a, 0x47, 0x75, 0x08, 0x3c, 0xf3, 0x2e, 0x0e,
	0xf1, 0x2e, 0x99, 0xda, 0xdc, 0x31, 0xb7, 0x8d, 0x0f, 0xd4, 0x2f, 0x93, 0x1f, 0x99, 0xc6, 0x53,
	0xd3, 0x78, 0x66, 0x1a, 0xbf, 0x32, 0x8d, 0x3f, 0x9b, 0xc6, 0xbf, 0x4c, 0xe3, 0x0f, 0x96, 0xd1,
	0xaf, 0xa9, 0x6e, 0x7f, 0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0xcc, 0x0e, 0xd7, 0xed,
	0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CardServiceClient is the client API for CardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardServiceClient interface {
	// CreateCard create card by information supplied from the user
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error)
	// CreateCardAttribute create card attribute for the card. Each Card Attribute is linked to its Card by CARD_ID
	CreateCardAttribute(ctx context.Context, in *CreateCardAttributeRequest, opts ...grpc.CallOption) (*CreateCardAttributeResponse, error)
	// GetCard retrieves the detail of a card information, selected by its token.
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*Card, error)
	// GetUserCards retrieves the detail of a cards information for the specific user, selected by user_id.
	GetUserCards(ctx context.Context, in *GetUserCardsRequest, opts ...grpc.CallOption) (*GetUserCardsResponse, error)
	// UpdateCardStatus update the card status.
	UpdateCardStatus(ctx context.Context, in *UpdateCardStatusRequest, opts ...grpc.CallOption) (*Result, error)
	// UpdateCardAccessStatus update the card access status.
	UpdateCardAccessStatus(ctx context.Context, in *UpdateCardAccessStatusRequest, opts ...grpc.CallOption) (*Result, error)
	// DeleteCard deletes a card
	DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type cardServiceClient struct {
	cc *grpc.ClientConn
}

func NewCardServiceClient(cc *grpc.ClientConn) CardServiceClient {
	return &cardServiceClient{cc}
}

func (c *cardServiceClient) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error) {
	out := new(CreateCardResponse)
	err := c.cc.Invoke(ctx, "/card.CardService/CreateCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) CreateCardAttribute(ctx context.Context, in *CreateCardAttributeRequest, opts ...grpc.CallOption) (*CreateCardAttributeResponse, error) {
	out := new(CreateCardAttributeResponse)
	err := c.cc.Invoke(ctx, "/card.CardService/CreateCardAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*Card, error) {
	out := new(Card)
	err := c.cc.Invoke(ctx, "/card.CardService/GetCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) GetUserCards(ctx context.Context, in *GetUserCardsRequest, opts ...grpc.CallOption) (*GetUserCardsResponse, error) {
	out := new(GetUserCardsResponse)
	err := c.cc.Invoke(ctx, "/card.CardService/GetUserCards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) UpdateCardStatus(ctx context.Context, in *UpdateCardStatusRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/card.CardService/UpdateCardStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) UpdateCardAccessStatus(ctx context.Context, in *UpdateCardAccessStatusRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/card.CardService/UpdateCardAccessStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardServiceClient) DeleteCard(ctx context.Context, in *DeleteCardRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/card.CardService/DeleteCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardServiceServer is the server API for CardService service.
type CardServiceServer interface {
	// CreateCard create card by information supplied from the user
	CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error)
	// CreateCardAttribute create card attribute for the card. Each Card Attribute is linked to its Card by CARD_ID
	CreateCardAttribute(context.Context, *CreateCardAttributeRequest) (*CreateCardAttributeResponse, error)
	// GetCard retrieves the detail of a card information, selected by its token.
	GetCard(context.Context, *GetCardRequest) (*Card, error)
	// GetUserCards retrieves the detail of a cards information for the specific user, selected by user_id.
	GetUserCards(context.Context, *GetUserCardsRequest) (*GetUserCardsResponse, error)
	// UpdateCardStatus update the card status.
	UpdateCardStatus(context.Context, *UpdateCardStatusRequest) (*Result, error)
	// UpdateCardAccessStatus update the card access status.
	UpdateCardAccessStatus(context.Context, *UpdateCardAccessStatusRequest) (*Result, error)
	// DeleteCard deletes a card
	DeleteCard(context.Context, *DeleteCardRequest) (*empty.Empty, error)
}

// UnimplementedCardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCardServiceServer struct {
}

func (*UnimplementedCardServiceServer) CreateCard(ctx context.Context, req *CreateCardRequest) (*CreateCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCard not implemented")
}
func (*UnimplementedCardServiceServer) CreateCardAttribute(ctx context.Context, req *CreateCardAttributeRequest) (*CreateCardAttributeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCardAttribute not implemented")
}
func (*UnimplementedCardServiceServer) GetCard(ctx context.Context, req *GetCardRequest) (*Card, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCard not implemented")
}
func (*UnimplementedCardServiceServer) GetUserCards(ctx context.Context, req *GetUserCardsRequest) (*GetUserCardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCards not implemented")
}
func (*UnimplementedCardServiceServer) UpdateCardStatus(ctx context.Context, req *UpdateCardStatusRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCardStatus not implemented")
}
func (*UnimplementedCardServiceServer) UpdateCardAccessStatus(ctx context.Context, req *UpdateCardAccessStatusRequest) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCardAccessStatus not implemented")
}
func (*UnimplementedCardServiceServer) DeleteCard(ctx context.Context, req *DeleteCardRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCard not implemented")
}

func RegisterCardServiceServer(s *grpc.Server, srv CardServiceServer) {
	s.RegisterService(&_CardService_serviceDesc, srv)
}

func _CardService_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/CreateCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).CreateCard(ctx, req.(*CreateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_CreateCardAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).CreateCardAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/CreateCardAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).CreateCardAttribute(ctx, req.(*CreateCardAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/GetCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_GetUserCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).GetUserCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/GetUserCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).GetUserCards(ctx, req.(*GetUserCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_UpdateCardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).UpdateCardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/UpdateCardStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).UpdateCardStatus(ctx, req.(*UpdateCardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_UpdateCardAccessStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardAccessStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).UpdateCardAccessStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/UpdateCardAccessStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).UpdateCardAccessStatus(ctx, req.(*UpdateCardAccessStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardService_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/DeleteCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).DeleteCard(ctx, req.(*DeleteCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "card.CardService",
	HandlerType: (*CardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCard",
			Handler:    _CardService_CreateCard_Handler,
		},
		{
			MethodName: "CreateCardAttribute",
			Handler:    _CardService_CreateCardAttribute_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _CardService_GetCard_Handler,
		},
		{
			MethodName: "GetUserCards",
			Handler:    _CardService_GetUserCards_Handler,
		},
		{
			MethodName: "UpdateCardStatus",
			Handler:    _CardService_UpdateCardStatus_Handler,
		},
		{
			MethodName: "UpdateCardAccessStatus",
			Handler:    _CardService_UpdateCardAccessStatus_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _CardService_DeleteCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openbank/openbank/v1/card/all.proto",
}
