// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openbank/openbank/v1/product/all.proto

package product

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttributeType int32

const (
	AttributeType_UnknownType   AttributeType = 0
	AttributeType_STRING        AttributeType = 1
	AttributeType_INTEGER       AttributeType = 2
	AttributeType_DOUBLE        AttributeType = 3
	AttributeType_DATE_WITH_DAY AttributeType = 4
)

var AttributeType_name = map[int32]string{
	0: "UnknownType",
	1: "STRING",
	2: "INTEGER",
	3: "DOUBLE",
	4: "DATE_WITH_DAY",
}

var AttributeType_value = map[string]int32{
	"UnknownType":   0,
	"STRING":        1,
	"INTEGER":       2,
	"DOUBLE":        3,
	"DATE_WITH_DAY": 4,
}

func (x AttributeType) String() string {
	return proto.EnumName(AttributeType_name, int32(x))
}

func (AttributeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{0}
}

type License struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *License) Reset()         { *m = License{} }
func (m *License) String() string { return proto.CompactTextString(m) }
func (*License) ProtoMessage()    {}
func (*License) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{0}
}

func (m *License) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_License.Unmarshal(m, b)
}
func (m *License) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_License.Marshal(b, m, deterministic)
}
func (m *License) XXX_Merge(src proto.Message) {
	xxx_messageInfo_License.Merge(m, src)
}
func (m *License) XXX_Size() int {
	return xxx_messageInfo_License.Size(m)
}
func (m *License) XXX_DiscardUnknown() {
	xxx_messageInfo_License.DiscardUnknown(m)
}

var xxx_messageInfo_License proto.InternalMessageInfo

func (m *License) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *License) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Metadata struct {
	License              string   `protobuf:"bytes,1,opt,name=License,json=license,proto3" json:"License,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

type ProductAttribute struct {
	ProductCode          string        `protobuf:"bytes,1,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	ProductAttributeID   string        `protobuf:"bytes,2,opt,name=ProductAttributeID,json=product_attribute_id,proto3" json:"ProductAttributeID,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Type                 AttributeType `protobuf:"varint,4,opt,name=Type,json=type,proto3,enum=product.AttributeType" json:"Type,omitempty"`
	Value                string        `protobuf:"bytes,5,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProductAttribute) Reset()         { *m = ProductAttribute{} }
func (m *ProductAttribute) String() string { return proto.CompactTextString(m) }
func (*ProductAttribute) ProtoMessage()    {}
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{2}
}

func (m *ProductAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAttribute.Unmarshal(m, b)
}
func (m *ProductAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAttribute.Marshal(b, m, deterministic)
}
func (m *ProductAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAttribute.Merge(m, src)
}
func (m *ProductAttribute) XXX_Size() int {
	return xxx_messageInfo_ProductAttribute.Size(m)
}
func (m *ProductAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAttribute proto.InternalMessageInfo

func (m *ProductAttribute) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *ProductAttribute) GetProductAttributeID() string {
	if m != nil {
		return m.ProductAttributeID
	}
	return ""
}

func (m *ProductAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductAttribute) GetType() AttributeType {
	if m != nil {
		return m.Type
	}
	return AttributeType_UnknownType
}

func (m *ProductAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Product struct {
	BankID               string              `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	Code                 string              `protobuf:"bytes,2,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	ParentProductCode    string              `protobuf:"bytes,3,opt,name=ParentProductCode,json=parent_product_code,proto3" json:"ParentProductCode,omitempty"`
	Name                 string              `protobuf:"bytes,4,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Category             string              `protobuf:"bytes,5,opt,name=Category,json=category,proto3" json:"Category,omitempty"`
	Family               string              `protobuf:"bytes,6,opt,name=Family,json=family,proto3" json:"Family,omitempty"`
	SuperFamily          string              `protobuf:"bytes,7,opt,name=SuperFamily,json=super_family,proto3" json:"SuperFamily,omitempty"`
	MoreInfoURL          string              `protobuf:"bytes,8,opt,name=MoreInfoURL,json=more_info_url,proto3" json:"MoreInfoURL,omitempty"`
	Details              string              `protobuf:"bytes,9,opt,name=Details,json=details,proto3" json:"Details,omitempty"`
	Description          string              `protobuf:"bytes,10,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	Meta                 *Metadata           `protobuf:"bytes,11,opt,name=Meta,json=meta,proto3" json:"Meta,omitempty"`
	ProductAttributes    []*ProductAttribute `protobuf:"bytes,12,rep,name=ProductAttributes,json=product_attributes,proto3" json:"ProductAttributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{3}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *Product) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Product) GetParentProductCode() string {
	if m != nil {
		return m.ParentProductCode
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Product) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *Product) GetSuperFamily() string {
	if m != nil {
		return m.SuperFamily
	}
	return ""
}

func (m *Product) GetMoreInfoURL() string {
	if m != nil {
		return m.MoreInfoURL
	}
	return ""
}

func (m *Product) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetMeta() *Metadata {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Product) GetProductAttributes() []*ProductAttribute {
	if m != nil {
		return m.ProductAttributes
	}
	return nil
}

type CreateProductRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	Product              *Product `protobuf:"bytes,3,opt,name=Product,json=product,proto3" json:"Product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{4}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *CreateProductRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	Product              *Product `protobuf:"bytes,3,opt,name=Product,json=product,proto3" json:"Product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{5}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *UpdateProductRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *UpdateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type DeleteProductRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{6}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *DeleteProductRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

type GetProductRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{7}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *GetProductRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

type GetProductsRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsRequest) Reset()         { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()    {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{8}
}

func (m *GetProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsRequest.Unmarshal(m, b)
}
func (m *GetProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsRequest.Merge(m, src)
}
func (m *GetProductsRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsRequest.Size(m)
}
func (m *GetProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsRequest proto.InternalMessageInfo

func (m *GetProductsRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

type GetProductsResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=Products,json=products,proto3" json:"Products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductsResponse) Reset()         { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()    {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{9}
}

func (m *GetProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResponse.Unmarshal(m, b)
}
func (m *GetProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResponse.Merge(m, src)
}
func (m *GetProductsResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsResponse.Size(m)
}
func (m *GetProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResponse proto.InternalMessageInfo

func (m *GetProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type CreateProductAttributeRequest struct {
	BankID               string            `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string            `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	ProductAttributeID   string            `protobuf:"bytes,3,opt,name=ProductAttributeID,json=product_attribute_id,proto3" json:"ProductAttributeID,omitempty"`
	ProductAttribute     *ProductAttribute `protobuf:"bytes,4,opt,name=ProductAttribute,json=product_attribute,proto3" json:"ProductAttribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateProductAttributeRequest) Reset()         { *m = CreateProductAttributeRequest{} }
func (m *CreateProductAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductAttributeRequest) ProtoMessage()    {}
func (*CreateProductAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{10}
}

func (m *CreateProductAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductAttributeRequest.Unmarshal(m, b)
}
func (m *CreateProductAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductAttributeRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductAttributeRequest.Merge(m, src)
}
func (m *CreateProductAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductAttributeRequest.Size(m)
}
func (m *CreateProductAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductAttributeRequest proto.InternalMessageInfo

func (m *CreateProductAttributeRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *CreateProductAttributeRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *CreateProductAttributeRequest) GetProductAttributeID() string {
	if m != nil {
		return m.ProductAttributeID
	}
	return ""
}

func (m *CreateProductAttributeRequest) GetProductAttribute() *ProductAttribute {
	if m != nil {
		return m.ProductAttribute
	}
	return nil
}

type UpdateProductAttributeRequest struct {
	BankID               string            `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string            `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	ProductAttributeID   string            `protobuf:"bytes,3,opt,name=ProductAttributeID,json=product_attribute_id,proto3" json:"ProductAttributeID,omitempty"`
	ProductAttribute     *ProductAttribute `protobuf:"bytes,4,opt,name=ProductAttribute,json=product_attribute,proto3" json:"ProductAttribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateProductAttributeRequest) Reset()         { *m = UpdateProductAttributeRequest{} }
func (m *UpdateProductAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductAttributeRequest) ProtoMessage()    {}
func (*UpdateProductAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{11}
}

func (m *UpdateProductAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductAttributeRequest.Unmarshal(m, b)
}
func (m *UpdateProductAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductAttributeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductAttributeRequest.Merge(m, src)
}
func (m *UpdateProductAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductAttributeRequest.Size(m)
}
func (m *UpdateProductAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductAttributeRequest proto.InternalMessageInfo

func (m *UpdateProductAttributeRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *UpdateProductAttributeRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *UpdateProductAttributeRequest) GetProductAttributeID() string {
	if m != nil {
		return m.ProductAttributeID
	}
	return ""
}

func (m *UpdateProductAttributeRequest) GetProductAttribute() *ProductAttribute {
	if m != nil {
		return m.ProductAttribute
	}
	return nil
}

type DeleteProductAttributeRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	ProductAttributeID   string   `protobuf:"bytes,3,opt,name=ProductAttributeID,json=product_attribute_id,proto3" json:"ProductAttributeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductAttributeRequest) Reset()         { *m = DeleteProductAttributeRequest{} }
func (m *DeleteProductAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductAttributeRequest) ProtoMessage()    {}
func (*DeleteProductAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{12}
}

func (m *DeleteProductAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductAttributeRequest.Unmarshal(m, b)
}
func (m *DeleteProductAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductAttributeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductAttributeRequest.Merge(m, src)
}
func (m *DeleteProductAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductAttributeRequest.Size(m)
}
func (m *DeleteProductAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductAttributeRequest proto.InternalMessageInfo

func (m *DeleteProductAttributeRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *DeleteProductAttributeRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *DeleteProductAttributeRequest) GetProductAttributeID() string {
	if m != nil {
		return m.ProductAttributeID
	}
	return ""
}

type GetProductAttributeRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	ProductCode          string   `protobuf:"bytes,2,opt,name=ProductCode,json=product_code,proto3" json:"ProductCode,omitempty"`
	ProductAttributeID   string   `protobuf:"bytes,3,opt,name=ProductAttributeID,json=product_attribute_id,proto3" json:"ProductAttributeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductAttributeRequest) Reset()         { *m = GetProductAttributeRequest{} }
func (m *GetProductAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductAttributeRequest) ProtoMessage()    {}
func (*GetProductAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15abd2347b909af4, []int{13}
}

func (m *GetProductAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductAttributeRequest.Unmarshal(m, b)
}
func (m *GetProductAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductAttributeRequest.Marshal(b, m, deterministic)
}
func (m *GetProductAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductAttributeRequest.Merge(m, src)
}
func (m *GetProductAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductAttributeRequest.Size(m)
}
func (m *GetProductAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductAttributeRequest proto.InternalMessageInfo

func (m *GetProductAttributeRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *GetProductAttributeRequest) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *GetProductAttributeRequest) GetProductAttributeID() string {
	if m != nil {
		return m.ProductAttributeID
	}
	return ""
}

func init() {
	proto.RegisterEnum("product.AttributeType", AttributeType_name, AttributeType_value)
	proto.RegisterType((*License)(nil), "product.License")
	proto.RegisterType((*Metadata)(nil), "product.Metadata")
	proto.RegisterType((*ProductAttribute)(nil), "product.ProductAttribute")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*CreateProductRequest)(nil), "product.CreateProductRequest")
	proto.RegisterType((*UpdateProductRequest)(nil), "product.UpdateProductRequest")
	proto.RegisterType((*DeleteProductRequest)(nil), "product.DeleteProductRequest")
	proto.RegisterType((*GetProductRequest)(nil), "product.GetProductRequest")
	proto.RegisterType((*GetProductsRequest)(nil), "product.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "product.GetProductsResponse")
	proto.RegisterType((*CreateProductAttributeRequest)(nil), "product.CreateProductAttributeRequest")
	proto.RegisterType((*UpdateProductAttributeRequest)(nil), "product.UpdateProductAttributeRequest")
	proto.RegisterType((*DeleteProductAttributeRequest)(nil), "product.DeleteProductAttributeRequest")
	proto.RegisterType((*GetProductAttributeRequest)(nil), "product.GetProductAttributeRequest")
}

func init() {
	proto.RegisterFile("github.com/openbank/openbank/v1/product/all.proto", fileDescriptor_15abd2347b909af4)
}

var fileDescriptor_15abd2347b909af4 = []byte{
	// 1936 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0x4f, 0x6c, 0x1b, 0x59,
	0x19, 0x9f, 0x19, 0x3b, 0x8e, 0xfb, 0xbc, 0x29, 0xce, 0x4b, 0x89, 0xbc, 0xd3, 0xa4, 0x7d, 0x4a,
	0x21, 0x4d, 0xb3, 0xed, 0xd8, 0xf1, 0x96, 0xb2, 0x8a, 0x40, 0xc8, 0x89, 0xb3, 0xa9, 0xd3, 0x36,
	0x1b, 0xb9, 0xc9, 0x2e, 0xf4, 0x62, 0x3d, 0xcf, 0x3c, 0x3b, 0xb3, 0x1d, 0xcf, 0x1b, 0xde, 0x9b,
	0x49, 0xd6, 0xac, 0x56, 0xda, 0xed, 0xa9, 0x17, 0xc4, 0xca, 0x70, 0xe3, 0x00, 0x57, 0x90, 0x40,
	0x70, 0x41, 0xc0, 0x05, 0x71, 0x47, 0x02, 0x89, 0x0b, 0x20, 0x6e, 0x80, 0xe0, 0x86, 0x38, 0x20,
	0x71, 0xe0, 0x80, 0xde, 0xcc, 0x78, 0x3c, 0xb6, 0xc7, 0x49, 0x5a, 0xd2, 0x15, 0x15, 0xa7, 0x64,
	0xde, 0xf7, 0xe7, 0x7d, 0xef, 0xf7, 0x7d, 0xdf, 0xef, 0x7b, 0xcf, 0x60, 0xad, 0x6d, 0xba, 0x87,
	0x5e, 0x53, 0xd3, 0x69, 0xa7, 0x48, 0x1d, 0x62, 0x37, 0xb1, 0xfd, 0x78, 0xf0, 0xcf, 0xd1, 0x5a,
	0xd1, 0x61, 0xd4, 0xf0, 0x74, 0xb7, 0x88, 0x2d, 0x4b, 0x73, 0x18, 0x75, 0x29, 0x9c, 0x0e, 0x97,
	0xd4, 0x85, 0x36, 0xa5, 0x6d, 0x8b, 0x14, 0xb1, 0x63, 0x16, 0xb1, 0x6d, 0x53, 0x17, 0xbb, 0x26,
	0xb5, 0x79, 0xa0, 0xa6, 0xde, 0xf4, 0xff, 0xe8, 0xb7, 0xda, 0xc4, 0xbe, 0xc5, 0x8f, 0x71, 0xbb,
	0x4d, 0x58, 0x91, 0x3a, 0xbe, 0x46, 0x82, 0xf6, 0xe5, 0xd0, 0x97, 0xff, 0xd5, 0xf4, 0x5a, 0x45,
	0xd2, 0x71, 0xdc, 0x6e, 0x20, 0x5c, 0x7a, 0x00, 0xa6, 0xef, 0x9b, 0x3a, 0xb1, 0x39, 0x81, 0x2a,
	0x50, 0x6a, 0xd5, 0x82, 0x8c, 0xe4, 0x95, 0x0b, 0x1b, 0x20, 0x2b, 0x15, 0xa4, 0x15, 0xa9, 0x24,
	0xed, 0x49, 0x75, 0xc5, 0x34, 0xe0, 0x15, 0x90, 0xde, 0xc5, 0x1d, 0x52, 0x50, 0xc6, 0xa4, 0x69,
	0x1b, 0x77, 0xc8, 0x7a, 0x26, 0x2b, 0xe5, 0xa5, 0x82, 0xb4, 0xf4, 0x06, 0xc8, 0x3e, 0x20, 0x2e,
	0x36, 0xb0, 0x8b, 0xe1, 0x67, 0x22, 0xd7, 0x09, 0x4e, 0xa7, 0xad, 0x40, 0x14, 0x59, 0x7e, 0xa4,
	0x80, 0xfc, 0x5e, 0x70, 0xfa, 0x8a, 0xeb, 0x32, 0xb3, 0xe9, 0xb9, 0x04, 0xde, 0x02, 0xb9, 0x70,
	0x6d, 0x93, 0x1a, 0x49, 0x6e, 0x5e, 0x09, 0x01, 0x6b, 0xe8, 0xd4, 0x20, 0xf0, 0x0b, 0x00, 0x8e,
	0xba, 0xa8, 0x55, 0x13, 0x62, 0xbe, 0xd4, 0xb7, 0xc2, 0x7d, 0xb5, 0x46, 0xec, 0x8c, 0xa9, 0xe4,
	0x33, 0xc2, 0x3b, 0x20, 0xbd, 0xdf, 0x75, 0x48, 0x21, 0x8d, 0xe4, 0x95, 0x8b, 0xe5, 0x79, 0x2d,
	0x74, 0xa2, 0x45, 0x7b, 0x09, 0xe9, 0xb0, 0x9d, 0xdb, 0x75, 0x08, 0x44, 0x60, 0xea, 0x6d, 0x6c,
	0x79, 0xa4, 0x30, 0x35, 0xe6, 0x78, 0xea, 0x48, 0x08, 0x22, 0x0c, 0x7e, 0x9e, 0x06, 0xd3, 0xe1,
	0x01, 0xe0, 0x35, 0x90, 0xd9, 0xc0, 0xf6, 0xe3, 0xc4, 0x8c, 0x4c, 0x8b, 0x0a, 0x0a, 0x43, 0xf6,
	0x81, 0x49, 0x48, 0x8b, 0x0f, 0xc8, 0x3a, 0x98, 0xdd, 0xc3, 0x8c, 0xd8, 0x6e, 0x1c, 0xc5, 0xf1,
	0xf3, 0xcd, 0x39, 0xbe, 0x52, 0x63, 0x08, 0xcc, 0x3e, 0x1c, 0xe9, 0x09, 0x70, 0x2c, 0x83, 0xec,
	0x26, 0x76, 0x49, 0x9b, 0xb2, 0x6e, 0xc2, 0xc9, 0xb2, 0x7a, 0x28, 0x83, 0x4b, 0x20, 0xf3, 0x26,
	0xee, 0x98, 0x56, 0xb7, 0x90, 0x19, 0xd3, 0xca, 0xb4, 0x7c, 0x89, 0xc8, 0xf3, 0x43, 0xcf, 0x21,
	0x2c, 0x54, 0x9c, 0x1e, 0xcf, 0x33, 0x17, 0xe2, 0x46, 0xa8, 0xae, 0x81, 0xdc, 0x03, 0xca, 0x48,
	0xcd, 0x6e, 0xd1, 0x83, 0xfa, 0xfd, 0x42, 0x76, 0x4c, 0x7d, 0xa6, 0x43, 0x19, 0x69, 0x98, 0x76,
	0x8b, 0x36, 0x3c, 0x66, 0x89, 0x4a, 0xac, 0x12, 0x17, 0x9b, 0x16, 0x2f, 0x5c, 0x18, 0x07, 0xd3,
	0x08, 0x44, 0xf0, 0x26, 0xc8, 0x55, 0x09, 0xd7, 0x99, 0xe9, 0x77, 0x52, 0x01, 0x8c, 0x69, 0xe6,
	0x8c, 0x81, 0x18, 0xae, 0x81, 0xb4, 0xa8, 0xf4, 0x42, 0x0e, 0xc9, 0x2b, 0xb9, 0xf2, 0x6c, 0x54,
	0x0d, 0xfd, 0xf2, 0x1f, 0x46, 0xac, 0x43, 0x5c, 0x0c, 0xf7, 0xc1, 0xec, 0x68, 0x79, 0xf2, 0xc2,
	0x2b, 0x28, 0xb5, 0x92, 0x2b, 0xbf, 0x1a, 0xd9, 0x8f, 0x6a, 0x0c, 0xf9, 0x81, 0x63, 0x85, 0xcb,
	0xa3, 0xe2, 0xf9, 0xbe, 0x0c, 0x2e, 0x6d, 0x32, 0x82, 0x5d, 0x12, 0xba, 0xa8, 0x93, 0xaf, 0x7a,
	0x84, 0x9f, 0xb1, 0x92, 0x46, 0x3a, 0x4d, 0x39, 0xa5, 0xd3, 0xee, 0x44, 0x85, 0xea, 0x97, 0x53,
	0xae, 0x9c, 0x1f, 0x3d, 0xc0, 0xf0, 0x36, 0xa1, 0x70, 0x28, 0xd8, 0x03, 0xc7, 0x78, 0x39, 0x82,
	0x65, 0xe0, 0x52, 0x95, 0x58, 0xe4, 0x93, 0x88, 0x35, 0xda, 0x93, 0x82, 0xd9, 0x6d, 0xe2, 0x7e,
	0x82, 0x1b, 0x56, 0x00, 0x1c, 0x6c, 0xc8, 0x9f, 0x65, 0xc7, 0xc8, 0xc5, 0x3b, 0x60, 0x6e, 0xc8,
	0x05, 0x77, 0xa8, 0x98, 0x2b, 0x6f, 0x80, 0x6c, 0x7f, 0xad, 0x20, 0xfb, 0xd5, 0x7e, 0x32, 0xfe,
	0xd9, 0x50, 0x38, 0x28, 0xed, 0xaf, 0x2b, 0x60, 0x71, 0xa8, 0xb4, 0xa3, 0xee, 0x78, 0x91, 0x65,
	0x93, 0x3c, 0x4d, 0x52, 0x67, 0x9c, 0x26, 0xf5, 0xf1, 0x71, 0xe6, 0x53, 0xe9, 0x99, 0x7b, 0x7d,
	0x76, 0xcc, 0xed, 0x10, 0x1e, 0x43, 0xdd, 0xf3, 0x7f, 0x8e, 0xc7, 0xcf, 0x64, 0xb0, 0x38, 0xd4,
	0xa1, 0xff, 0xfb, 0x78, 0x44, 0xb1, 0xff, 0x44, 0x06, 0xea, 0xa0, 0x6b, 0x5e, 0x9e, 0xc0, 0x57,
	0x1d, 0x30, 0x33, 0x74, 0xf3, 0x81, 0x73, 0x20, 0x77, 0x60, 0x3f, 0xb6, 0xe9, 0xb1, 0x2d, 0x3e,
	0xf3, 0x92, 0xaa, 0x64, 0x25, 0x78, 0x11, 0x64, 0x1e, 0xee, 0xd7, 0x6b, 0xbb, 0xdb, 0x79, 0xd9,
	0xff, 0xfe, 0x14, 0x98, 0xae, 0xed, 0xee, 0x6f, 0x6d, 0x6f, 0xd5, 0xf3, 0x4a, 0x5f, 0xa1, 0xfa,
	0xd6, 0xc1, 0xc6, 0xfd, 0xad, 0x7c, 0xca, 0xff, 0xfe, 0x34, 0x98, 0xa9, 0x56, 0xf6, 0xb7, 0x1a,
	0xef, 0xd4, 0xf6, 0xef, 0x36, 0xaa, 0x95, 0xaf, 0xe4, 0xd3, 0x62, 0x59, 0x55, 0x0a, 0x52, 0xf9,
	0xc9, 0xab, 0xe0, 0x62, 0x18, 0xf8, 0x43, 0xc2, 0x8e, 0x4c, 0x9d, 0xc0, 0x1f, 0x2a, 0x60, 0x66,
	0x88, 0x19, 0xe0, 0x62, 0x54, 0x4d, 0x49, 0xc3, 0x50, 0x1d, 0xa3, 0x9e, 0xa5, 0xbf, 0xca, 0xbd,
	0xca, 0xf7, 0xe4, 0xc1, 0xc5, 0x2b, 0x1f, 0xd8, 0x21, 0x8c, 0xfa, 0x97, 0xf1, 0x5b, 0xc1, 0x0a,
	0x47, 0x18, 0xd9, 0xe4, 0xb8, 0xbf, 0x8c, 0xb0, 0x6d, 0x20, 0x46, 0x5c, 0x8f, 0xd9, 0x1c, 0xb9,
	0x87, 0x04, 0xd1, 0xe6, 0xbb, 0x44, 0x77, 0xb5, 0x9d, 0xbb, 0x20, 0x55, 0x2e, 0xad, 0xc1, 0x0a,
	0x58, 0x0c, 0x5d, 0x22, 0xdd, 0xb7, 0x37, 0x10, 0xf7, 0x74, 0x9d, 0x70, 0xde, 0xf2, 0x2c, 0xab,
	0xab, 0x41, 0x04, 0xae, 0xa8, 0x0b, 0xd7, 0x8a, 0x06, 0x69, 0x99, 0xb6, 0x19, 0x5c, 0xde, 0x43,
	0xd7, 0xa1, 0x5d, 0x73, 0x0e, 0xcc, 0x82, 0xcc, 0x5b, 0x15, 0xcf, 0x3d, 0x2c, 0xc3, 0x69, 0x30,
	0x75, 0xcc, 0x4c, 0x97, 0x3c, 0xf9, 0xed, 0x9f, 0xbf, 0xa9, 0x68, 0xeb, 0xf2, 0xea, 0xd2, 0x0d,
	0xf1, 0x86, 0x10, 0x25, 0xc0, 0x8b, 0xef, 0x07, 0x35, 0xf2, 0x41, 0xdf, 0x01, 0x2f, 0xbe, 0x1f,
	0x2b, 0x88, 0x0f, 0x9e, 0x2a, 0xd2, 0xc7, 0x8a, 0x9f, 0x55, 0xf8, 0x0f, 0x05, 0x80, 0x41, 0xb9,
	0x41, 0x35, 0x82, 0x63, 0x6c, 0xda, 0x24, 0x40, 0xf5, 0x23, 0xa5, 0x57, 0xf9, 0x67, 0x0c, 0xaa,
	0x85, 0x3a, 0x71, 0x99, 0x49, 0x8e, 0x48, 0x84, 0x89, 0xb8, 0x72, 0xb1, 0x8e, 0xff, 0xfc, 0x50,
	0xd7, 0x23, 0x69, 0x6c, 0x15, 0xe1, 0x26, 0xf5, 0x5c, 0x1f, 0xaf, 0xbe, 0x0d, 0x77, 0x88, 0x6e,
	0xb6, 0x4c, 0x62, 0xa0, 0x66, 0xd7, 0x17, 0xd4, 0xaa, 0x3b, 0x35, 0x81, 0x61, 0x09, 0x6e, 0x80,
	0x2b, 0x61, 0x34, 0x88, 0xbc, 0x47, 0x74, 0xef, 0x39, 0x40, 0xdc, 0x59, 0x03, 0xa9, 0xdb, 0xa5,
	0xdb, 0x70, 0x15, 0xac, 0xd4, 0xfd, 0x64, 0x11, 0x03, 0x1d, 0x1f, 0x12, 0xdb, 0xdf, 0x89, 0x11,
	0x4e, 0x3d, 0xa6, 0x13, 0x64, 0x72, 0x64, 0x53, 0x17, 0xb5, 0xa8, 0x67, 0x1b, 0x5a, 0x13, 0x82,
	0x7c, 0x84, 0x7b, 0x06, 0xa4, 0x19, 0xc1, 0x86, 0x0f, 0xfb, 0x6b, 0xf0, 0xb9, 0x30, 0xff, 0xb7,
	0x02, 0x72, 0xb1, 0xc1, 0x08, 0x2f, 0x27, 0x80, 0xde, 0x9f, 0xb8, 0xea, 0x42, 0xb2, 0x30, 0x98,
	0xa5, 0x4b, 0x3f, 0x50, 0x7a, 0x95, 0x0f, 0x95, 0x41, 0x06, 0xae, 0x46, 0x18, 0x63, 0xcb, 0x42,
	0xf8, 0x08, 0x9b, 0x16, 0x6e, 0x5a, 0x11, 0xb6, 0x5c, 0xbd, 0x93, 0x98, 0x04, 0x46, 0xda, 0x98,
	0x19, 0xa6, 0xdd, 0x9e, 0x60, 0xa6, 0xed, 0x1c, 0x04, 0x09, 0xd8, 0x3d, 0x35, 0x01, 0x37, 0xc1,
	0xaa, 0xba, 0x92, 0x98, 0x80, 0x84, 0xf8, 0xcf, 0x33, 0x19, 0x8b, 0xf0, 0xf2, 0x09, 0xc9, 0x88,
	0xc1, 0xff, 0x5d, 0x05, 0xcc, 0x0c, 0x4d, 0xcb, 0x18, 0x47, 0x24, 0xdd, 0x41, 0x13, 0x0a, 0xff,
	0xf7, 0x72, 0xaf, 0xf2, 0xed, 0x38, 0x47, 0x04, 0x76, 0x31, 0x8e, 0xb8, 0x1a, 0xac, 0xf0, 0xc1,
	0xd2, 0x75, 0x1e, 0x87, 0x3c, 0x60, 0x85, 0xdb, 0x71, 0x56, 0x88, 0xe3, 0x88, 0x3c, 0xdf, 0xdc,
	0xf8, 0xaf, 0x59, 0x41, 0x7d, 0xbe, 0x0a, 0x95, 0xc1, 0xcc, 0xd0, 0x00, 0x8d, 0x41, 0x94, 0x74,
	0xf5, 0x55, 0xe7, 0xb5, 0xe0, 0x47, 0x05, 0xad, 0xff, 0xa3, 0x82, 0xb6, 0xd5, 0x71, 0xdc, 0xee,
	0xd2, 0x8f, 0xe5, 0x5e, 0xe5, 0x38, 0x86, 0x53, 0x60, 0x1c, 0xc3, 0x69, 0x71, 0x8f, 0xb0, 0x0e,
	0xb6, 0x89, 0xed, 0x5a, 0x5d, 0x64, 0x8c, 0x48, 0xb5, 0x9d, 0xe5, 0x00, 0xa5, 0xab, 0x13, 0x50,
	0x0a, 0x0c, 0x0c, 0x6d, 0x32, 0x06, 0xaf, 0xad, 0x3e, 0x3b, 0x00, 0xf0, 0x1b, 0x29, 0x30, 0x9f,
	0x7c, 0xbf, 0x84, 0xcb, 0xc9, 0xe3, 0x64, 0x74, 0x4e, 0xab, 0x93, 0x2f, 0x31, 0x7e, 0xcf, 0xfe,
	0x3a, 0x56, 0x3c, 0xea, 0xe8, 0x80, 0x41, 0xd1, 0x7c, 0x55, 0x3f, 0x3f, 0x61, 0xd4, 0xf4, 0x15,
	0x26, 0x0e, 0x9d, 0x47, 0xc1, 0xd0, 0x79, 0x08, 0x96, 0x47, 0xf7, 0x9f, 0x30, 0x7d, 0x6e, 0x80,
	0xeb, 0xea, 0x67, 0x4f, 0xaa, 0xb3, 0xc8, 0xc1, 0x64, 0xb0, 0x77, 0xc5, 0x18, 0xaa, 0x9d, 0x19,
	0xef, 0xe2, 0xe0, 0xd5, 0x1a, 0x09, 0x62, 0x37, 0x90, 0x78, 0x41, 0xfe, 0x22, 0x15, 0x7f, 0x4b,
	0x0c, 0xd2, 0x71, 0x2d, 0x81, 0x1d, 0x9f, 0x25, 0x17, 0x7f, 0x52, 0x7a, 0x95, 0xa7, 0x31, 0xfe,
	0x5c, 0x1e, 0x9b, 0x60, 0x03, 0xa8, 0xcf, 0x6b, 0x96, 0xd5, 0x03, 0x2a, 0xbd, 0x77, 0x2a, 0x95,
	0x9e, 0x3d, 0x25, 0xe7, 0xc9, 0xa3, 0xf7, 0xe0, 0x0b, 0xc9, 0xe0, 0x47, 0x29, 0x30, 0x9f, 0xfc,
	0x46, 0x89, 0xf5, 0xd4, 0x89, 0x8f, 0x98, 0x93, 0xf2, 0xf8, 0x1d, 0xa5, 0x57, 0xf9, 0x65, 0xbc,
	0xa7, 0x46, 0x09, 0x39, 0xd6, 0x53, 0x37, 0xc6, 0xa8, 0x79, 0x20, 0x1c, 0x21, 0xe9, 0x47, 0x01,
	0xfd, 0x24, 0x75, 0x51, 0x32, 0x5b, 0x9f, 0x57, 0x17, 0xa9, 0x2f, 0x24, 0x07, 0xbf, 0x52, 0xc0,
	0x7c, 0xf2, 0xbb, 0x28, 0x96, 0x83, 0x13, 0x1f, 0x4e, 0x13, 0x89, 0xfe, 0xef, 0x72, 0xaf, 0xf2,
	0xad, 0x78, 0x02, 0x46, 0x99, 0x3e, 0x96, 0x80, 0xeb, 0x27, 0x71, 0xfe, 0x40, 0x4f, 0xdb, 0x29,
	0x06, 0xf0, 0xaf, 0x9c, 0x06, 0xff, 0xe9, 0x63, 0xe0, 0xde, 0xea, 0xf9, 0x03, 0xaa, 0xa6, 0x9e,
	0x2a, 0xd2, 0xc6, 0x93, 0x4c, 0xaf, 0xf2, 0xc7, 0x29, 0x90, 0x2a, 0x6b, 0x25, 0xb8, 0x1d, 0xbd,
	0xbb, 0x50, 0x65, 0xaf, 0x06, 0xd7, 0xf6, 0x18, 0x3d, 0x32, 0x0d, 0xc2, 0xd1, 0x66, 0xfd, 0xa0,
	0x8a, 0xa8, 0x43, 0x58, 0xf0, 0x43, 0x3c, 0xa2, 0x41, 0x67, 0xf6, 0x95, 0xfb, 0x1d, 0xaa, 0x95,
	0xa7, 0xd6, 0xb4, 0x92, 0x56, 0x5a, 0x95, 0x95, 0x72, 0x1e, 0x3b, 0x8e, 0x65, 0xea, 0xbe, 0x41,
	0xf1, 0x5d, 0x4e, 0xed, 0xf5, 0xb1, 0x95, 0xfa, 0x9b, 0x20, 0xf5, 0xb9, 0x52, 0x09, 0x7e, 0x09,
	0x7c, 0x71, 0xb8, 0xeb, 0xb1, 0x8d, 0x3c, 0x9b, 0xbc, 0xe7, 0x10, 0x5d, 0x90, 0x0a, 0x61, 0x8c,
	0x32, 0x44, 0x75, 0xdd, 0x63, 0xc4, 0xe8, 0x6f, 0xcd, 0x09, 0x3b, 0x22, 0x0c, 0x71, 0xd3, 0x20,
	0x5a, 0xbd, 0x21, 0xd8, 0xa3, 0x04, 0xbf, 0x0c, 0xde, 0x4e, 0x62, 0x8f, 0x80, 0xa3, 0x9a, 0xd4,
	0xe8, 0x0a, 0x06, 0xe9, 0x60, 0x2b, 0xe8, 0x0f, 0xe1, 0x9a, 0x32, 0x64, 0x50, 0x12, 0xd0, 0x4a,
	0x07, 0xbb, 0xfa, 0xa1, 0x6f, 0x12, 0xed, 0x1c, 0xda, 0x6a, 0xf5, 0xfb, 0x62, 0x83, 0x35, 0xb8,
	0x05, 0x36, 0x27, 0x6f, 0x10, 0x39, 0xd2, 0xa9, 0xed, 0x62, 0x33, 0x9c, 0x67, 0x1e, 0x27, 0xec,
	0x3a, 0x17, 0x33, 0xcb, 0x20, 0xb6, 0x6b, 0x62, 0x8b, 0x6b, 0xf5, 0x3d, 0xe1, 0xed, 0x75, 0x58,
	0x03, 0xdb, 0xe3, 0xde, 0x84, 0xfe, 0xc0, 0xd5, 0x21, 0x16, 0x4c, 0x4e, 0x58, 0xc7, 0xe4, 0x5c,
	0x10, 0xb4, 0x4b, 0x11, 0xf6, 0xeb, 0x66, 0x88, 0x18, 0xb5, 0xfa, 0xb3, 0xd3, 0xe7, 0xa3, 0xbf,
	0xc9, 0xe0, 0x2f, 0x72, 0x54, 0x6c, 0x7f, 0x90, 0xb3, 0x29, 0xf8, 0x44, 0xae, 0x84, 0xce, 0x69,
	0x74, 0x73, 0x8e, 0xcc, 0xb9, 0xb0, 0x67, 0x84, 0xbb, 0xcc, 0xf4, 0xb1, 0x11, 0xa1, 0x78, 0xee,
	0xa1, 0x38, 0x94, 0xee, 0x8f, 0x63, 0x11, 0x39, 0xd7, 0xd0, 0xfe, 0x21, 0x89, 0x0b, 0x44, 0xd4,
	0x0e, 0xa3, 0xbe, 0xdb, 0x16, 0xb5, 0x2c, 0x7a, 0x1c, 0xc4, 0x2e, 0xb6, 0xa5, 0xcc, 0xfc, 0x5a,
	0xa0, 0x21, 0xea, 0x16, 0xb5, 0x2c, 0x7a, 0xac, 0xad, 0xa4, 0xcb, 0x59, 0x51, 0xe9, 0xc2, 0xc5,
	0xfa, 0x05, 0xf1, 0x9f, 0x4b, 0x1f, 0x13, 0x7b, 0x63, 0x1d, 0xa8, 0x01, 0xc7, 0x43, 0xb8, 0xcd,
	0xb0, 0xed, 0x07, 0x86, 0x8d, 0x10, 0x0d, 0xb0, 0x10, 0xf6, 0x0a, 0x9c, 0x0b, 0x85, 0xfe, 0x57,
	0x28, 0xbd, 0x2b, 0xef, 0x49, 0x8f, 0xfa, 0x3f, 0x82, 0x7e, 0x28, 0x4b, 0x4f, 0x65, 0xe9, 0x63,
	0x59, 0xfa, 0xa9, 0x2c, 0xfd, 0x4e, 0x96, 0xfe, 0x25, 0x4b, 0xbf, 0x51, 0xa4, 0x66, 0xc6, 0x67,
	0x83, 0xd7, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xd6, 0x21, 0x29, 0xe3, 0x1a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	// CreateProduct creates a new product.
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error)
	// GetProduct retrieves the details of a specific product information, selected by its ID.
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
	// GetProducts get all the available product.
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	// UpdateProduct updates the product.
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*Product, error)
	// DeleteProduct deletes a product.
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// CreateProductAttribute creates a new product attribute.
	CreateProductAttribute(ctx context.Context, in *CreateProductAttributeRequest, opts ...grpc.CallOption) (*ProductAttribute, error)
	// GetProductAttribute retrieves the details of a specific product information, selected by its ID.
	GetProductAttribute(ctx context.Context, in *GetProductAttributeRequest, opts ...grpc.CallOption) (*ProductAttribute, error)
	// UpdateProductAttribute updates the product attribute.
	UpdateProductAttribute(ctx context.Context, in *UpdateProductAttributeRequest, opts ...grpc.CallOption) (*ProductAttribute, error)
	// DeleteProductAttribute deletes a product attribute.
	DeleteProductAttribute(ctx context.Context, in *DeleteProductAttributeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateProductAttribute(ctx context.Context, in *CreateProductAttributeRequest, opts ...grpc.CallOption) (*ProductAttribute, error) {
	out := new(ProductAttribute)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateProductAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductAttribute(ctx context.Context, in *GetProductAttributeRequest, opts ...grpc.CallOption) (*ProductAttribute, error) {
	out := new(ProductAttribute)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProductAttribute(ctx context.Context, in *UpdateProductAttributeRequest, opts ...grpc.CallOption) (*ProductAttribute, error) {
	out := new(ProductAttribute)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProductAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProductAttribute(ctx context.Context, in *DeleteProductAttributeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProductAttribute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	// CreateProduct creates a new product.
	CreateProduct(context.Context, *CreateProductRequest) (*Product, error)
	// GetProduct retrieves the details of a specific product information, selected by its ID.
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	// GetProducts get all the available product.
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	// UpdateProduct updates the product.
	UpdateProduct(context.Context, *UpdateProductRequest) (*Product, error)
	// DeleteProduct deletes a product.
	DeleteProduct(context.Context, *DeleteProductRequest) (*empty.Empty, error)
	// CreateProductAttribute creates a new product attribute.
	CreateProductAttribute(context.Context, *CreateProductAttributeRequest) (*ProductAttribute, error)
	// GetProductAttribute retrieves the details of a specific product information, selected by its ID.
	GetProductAttribute(context.Context, *GetProductAttributeRequest) (*ProductAttribute, error)
	// UpdateProductAttribute updates the product attribute.
	UpdateProductAttribute(context.Context, *UpdateProductAttributeRequest) (*ProductAttribute, error)
	// DeleteProductAttribute deletes a product attribute.
	DeleteProductAttribute(context.Context, *DeleteProductAttributeRequest) (*empty.Empty, error)
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) CreateProduct(ctx context.Context, req *CreateProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetProduct(ctx context.Context, req *GetProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetProducts(ctx context.Context, req *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (*UnimplementedProductServiceServer) UpdateProduct(ctx context.Context, req *UpdateProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedProductServiceServer) CreateProductAttribute(ctx context.Context, req *CreateProductAttributeRequest) (*ProductAttribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductAttribute not implemented")
}
func (*UnimplementedProductServiceServer) GetProductAttribute(ctx context.Context, req *GetProductAttributeRequest) (*ProductAttribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductAttribute not implemented")
}
func (*UnimplementedProductServiceServer) UpdateProductAttribute(ctx context.Context, req *UpdateProductAttributeRequest) (*ProductAttribute, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductAttribute not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProductAttribute(ctx context.Context, req *DeleteProductAttributeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductAttribute not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateProductAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProductAttribute(ctx, req.(*CreateProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductAttribute(ctx, req.(*GetProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProductAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProductAttribute(ctx, req.(*UpdateProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProductAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProductAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProductAttribute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProductAttribute(ctx, req.(*DeleteProductAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "CreateProductAttribute",
			Handler:    _ProductService_CreateProductAttribute_Handler,
		},
		{
			MethodName: "GetProductAttribute",
			Handler:    _ProductService_GetProductAttribute_Handler,
		},
		{
			MethodName: "UpdateProductAttribute",
			Handler:    _ProductService_UpdateProductAttribute_Handler,
		},
		{
			MethodName: "DeleteProductAttribute",
			Handler:    _ProductService_DeleteProductAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openbank/openbank/v1/product/all.proto",
}
