// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openbank/openbank/v1/productcollection/all.proto

package productcollection

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	product "github.com/openbank/openbank/v1/product"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductCollection struct {
	CollectionCode       string             `protobuf:"bytes,1,opt,name=CollectionCode,json=collection_code,proto3" json:"CollectionCode,omitempty"`
	Products             []*product.Product `protobuf:"bytes,2,rep,name=Products,json=products,proto3" json:"Products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProductCollection) Reset()         { *m = ProductCollection{} }
func (m *ProductCollection) String() string { return proto.CompactTextString(m) }
func (*ProductCollection) ProtoMessage()    {}
func (*ProductCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_62bb3483d57949fb, []int{0}
}

func (m *ProductCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductCollection.Unmarshal(m, b)
}
func (m *ProductCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductCollection.Marshal(b, m, deterministic)
}
func (m *ProductCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductCollection.Merge(m, src)
}
func (m *ProductCollection) XXX_Size() int {
	return xxx_messageInfo_ProductCollection.Size(m)
}
func (m *ProductCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductCollection.DiscardUnknown(m)
}

var xxx_messageInfo_ProductCollection proto.InternalMessageInfo

func (m *ProductCollection) GetCollectionCode() string {
	if m != nil {
		return m.CollectionCode
	}
	return ""
}

func (m *ProductCollection) GetProducts() []*product.Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type CreateProductCollectionRequest struct {
	BankID               string             `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	CollectionCode       string             `protobuf:"bytes,2,opt,name=CollectionCode,json=collection_code,proto3" json:"CollectionCode,omitempty"`
	ProductCollection    *ProductCollection `protobuf:"bytes,3,opt,name=ProductCollection,json=product_collection,proto3" json:"ProductCollection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateProductCollectionRequest) Reset()         { *m = CreateProductCollectionRequest{} }
func (m *CreateProductCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductCollectionRequest) ProtoMessage()    {}
func (*CreateProductCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62bb3483d57949fb, []int{1}
}

func (m *CreateProductCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductCollectionRequest.Unmarshal(m, b)
}
func (m *CreateProductCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductCollectionRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductCollectionRequest.Merge(m, src)
}
func (m *CreateProductCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductCollectionRequest.Size(m)
}
func (m *CreateProductCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductCollectionRequest proto.InternalMessageInfo

func (m *CreateProductCollectionRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *CreateProductCollectionRequest) GetCollectionCode() string {
	if m != nil {
		return m.CollectionCode
	}
	return ""
}

func (m *CreateProductCollectionRequest) GetProductCollection() *ProductCollection {
	if m != nil {
		return m.ProductCollection
	}
	return nil
}

type UpdateProductCollectionRequest struct {
	BankID               string             `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	CollectionCode       string             `protobuf:"bytes,2,opt,name=CollectionCode,json=collection_code,proto3" json:"CollectionCode,omitempty"`
	ProductCollection    *ProductCollection `protobuf:"bytes,3,opt,name=ProductCollection,json=product_collection,proto3" json:"ProductCollection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateProductCollectionRequest) Reset()         { *m = UpdateProductCollectionRequest{} }
func (m *UpdateProductCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductCollectionRequest) ProtoMessage()    {}
func (*UpdateProductCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62bb3483d57949fb, []int{2}
}

func (m *UpdateProductCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductCollectionRequest.Unmarshal(m, b)
}
func (m *UpdateProductCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductCollectionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductCollectionRequest.Merge(m, src)
}
func (m *UpdateProductCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductCollectionRequest.Size(m)
}
func (m *UpdateProductCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductCollectionRequest proto.InternalMessageInfo

func (m *UpdateProductCollectionRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *UpdateProductCollectionRequest) GetCollectionCode() string {
	if m != nil {
		return m.CollectionCode
	}
	return ""
}

func (m *UpdateProductCollectionRequest) GetProductCollection() *ProductCollection {
	if m != nil {
		return m.ProductCollection
	}
	return nil
}

type DeleteProductCollectionRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	CollectionCode       string   `protobuf:"bytes,2,opt,name=CollectionCode,json=collection_code,proto3" json:"CollectionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductCollectionRequest) Reset()         { *m = DeleteProductCollectionRequest{} }
func (m *DeleteProductCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductCollectionRequest) ProtoMessage()    {}
func (*DeleteProductCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62bb3483d57949fb, []int{3}
}

func (m *DeleteProductCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductCollectionRequest.Unmarshal(m, b)
}
func (m *DeleteProductCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductCollectionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductCollectionRequest.Merge(m, src)
}
func (m *DeleteProductCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductCollectionRequest.Size(m)
}
func (m *DeleteProductCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductCollectionRequest proto.InternalMessageInfo

func (m *DeleteProductCollectionRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *DeleteProductCollectionRequest) GetCollectionCode() string {
	if m != nil {
		return m.CollectionCode
	}
	return ""
}

type GetProductCollectionRequest struct {
	BankID               string   `protobuf:"bytes,1,opt,name=BankID,json=bank_id,proto3" json:"BankID,omitempty"`
	CollectionCode       string   `protobuf:"bytes,2,opt,name=CollectionCode,json=collection_code,proto3" json:"CollectionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductCollectionRequest) Reset()         { *m = GetProductCollectionRequest{} }
func (m *GetProductCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductCollectionRequest) ProtoMessage()    {}
func (*GetProductCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62bb3483d57949fb, []int{4}
}

func (m *GetProductCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductCollectionRequest.Unmarshal(m, b)
}
func (m *GetProductCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductCollectionRequest.Marshal(b, m, deterministic)
}
func (m *GetProductCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductCollectionRequest.Merge(m, src)
}
func (m *GetProductCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductCollectionRequest.Size(m)
}
func (m *GetProductCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductCollectionRequest proto.InternalMessageInfo

func (m *GetProductCollectionRequest) GetBankID() string {
	if m != nil {
		return m.BankID
	}
	return ""
}

func (m *GetProductCollectionRequest) GetCollectionCode() string {
	if m != nil {
		return m.CollectionCode
	}
	return ""
}

func init() {
	proto.RegisterType((*ProductCollection)(nil), "productcollection.ProductCollection")
	proto.RegisterType((*CreateProductCollectionRequest)(nil), "productcollection.CreateProductCollectionRequest")
	proto.RegisterType((*UpdateProductCollectionRequest)(nil), "productcollection.UpdateProductCollectionRequest")
	proto.RegisterType((*DeleteProductCollectionRequest)(nil), "productcollection.DeleteProductCollectionRequest")
	proto.RegisterType((*GetProductCollectionRequest)(nil), "productcollection.GetProductCollectionRequest")
}

func init() {
	proto.RegisterFile("github.com/openbank/openbank/v1/productcollection/all.proto", fileDescriptor_62bb3483d57949fb)
}

var fileDescriptor_62bb3483d57949fb = []byte{
	// 1197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xcf, 0x6f, 0xdc, 0xc4,
	0x17, 0xb7, 0xbd, 0xed, 0x36, 0x9d, 0xea, 0xfb, 0x25, 0x1d, 0x50, 0x1b, 0x6d, 0x51, 0x35, 0x4a,
	0x91, 0xb2, 0x04, 0x3a, 0xf6, 0x6e, 0x83, 0x68, 0x43, 0x11, 0xda, 0x24, 0xa5, 0x24, 0x42, 0x62,
	0xb5, 0xd0, 0x82, 0x2a, 0x55, 0x91, 0xd7, 0x7e, 0x9b, 0x75, 0xe3, 0x9d, 0x31, 0x33, 0xe3, 0x6c,
	0x43, 0x55, 0x81, 0x7a, 0xaa, 0x10, 0x87, 0x2a, 0x70, 0xaf, 0xd4, 0x43, 0x4f, 0x70, 0xe3, 0xc0,
	0x9f, 0x81, 0x04, 0x07, 0x04, 0xdc, 0xe0, 0x50, 0x89, 0x7f, 0x80, 0x23, 0x1a, 0xdb, 0xfb, 0x4b,
	0xf6, 0xa6, 0x41, 0x04, 0x55, 0xe2, 0x94, 0xb5, 0xdf, 0x7b, 0x9f, 0xf7, 0xde, 0x7c, 0xe6, 0x7d,
	0x9e, 0x83, 0xde, 0xd8, 0x0a, 0x54, 0x37, 0x6e, 0x53, 0x8f, 0xf7, 0x6c, 0x1e, 0x01, 0x6b, 0xbb,
	0x6c, 0x7b, 0xf4, 0x63, 0xa7, 0x66, 0x47, 0x82, 0xfb, 0xb1, 0xa7, 0x3c, 0x1e, 0x86, 0xe0, 0xa9,
	0x80, 0x33, 0xdb, 0x0d, 0x43, 0x1a, 0x09, 0xae, 0x38, 0x3e, 0x99, 0x33, 0x56, 0x5e, 0xdc, 0xe2,
	0x7c, 0x2b, 0x04, 0xdb, 0x8d, 0x02, 0xdb, 0x65, 0x8c, 0x2b, 0x57, 0xbf, 0x96, 0x69, 0x40, 0xe5,
	0xd5, 0xe4, 0x8f, 0x77, 0x7e, 0x0b, 0xd8, 0x79, 0xd9, 0x77, 0xb7, 0xb6, 0x40, 0xd8, 0x3c, 0x4a,
	0x3c, 0x0a, 0xbc, 0xcf, 0x64, 0x58, 0xc9, 0x53, 0x3b, 0xee, 0xd8, 0xd0, 0x8b, 0xd4, 0x6e, 0x66,
	0xac, 0x1d, 0xb0, 0xf0, 0x51, 0xb9, 0xf3, 0x9f, 0x9b, 0xe8, 0x64, 0x33, 0x7d, 0xbb, 0x3a, 0xac,
	0x18, 0x5f, 0x40, 0xff, 0x1f, 0x3d, 0xad, 0x72, 0x1f, 0xe6, 0x4c, 0x62, 0x56, 0x8f, 0xaf, 0xa0,
	0x19, 0x63, 0xce, 0xa8, 0x1a, 0x8e, 0xd1, 0x34, 0x5a, 0xcf, 0x8d, 0x3a, 0xdc, 0xf4, 0xb8, 0x0f,
	0xf8, 0x22, 0x9a, 0xc9, 0x90, 0xe4, 0x9c, 0x45, 0x4a, 0xd5, 0x13, 0xf5, 0x59, 0x9a, 0x25, 0xa4,
	0x99, 0x61, 0x02, 0x60, 0x26, 0x33, 0xca, 0xe5, 0xf2, 0x8c, 0x31, 0x6b, 0xcc, 0x19, 0xf3, 0xbf,
	0x99, 0xe8, 0xec, 0xaa, 0x00, 0x57, 0x41, 0xae, 0xa4, 0x16, 0x7c, 0x1c, 0x83, 0x54, 0xf8, 0x1c,
	0x2a, 0xaf, 0xb8, 0x6c, 0x7b, 0x7d, 0xad, 0xa0, 0xa2, 0x63, 0xba, 0xcd, 0xcd, 0xc0, 0x2f, 0x28,
	0xdf, 0x7a, 0x7a, 0xf9, 0x9b, 0x05, 0x07, 0x31, 0x57, 0x22, 0x66, 0xf5, 0x44, 0xfd, 0x25, 0x9a,
	0x23, 0x95, 0xe6, 0x7c, 0x27, 0xd0, 0x71, 0x16, 0xb0, 0x39, 0x8a, 0x98, 0xe8, 0xf2, 0x5a, 0xe4,
	0xff, 0xc7, 0xbb, 0xbc, 0x67, 0xa2, 0xb3, 0x6b, 0x10, 0xc2, 0xb3, 0xe8, 0x72, 0x58, 0xc4, 0xa7,
	0xe8, 0xcc, 0x55, 0x50, 0xcf, 0xae, 0x80, 0xfa, 0xe3, 0xff, 0xa1, 0xb9, 0x5c, 0xfa, 0xf7, 0x41,
	0xec, 0x04, 0x1e, 0xe0, 0x6f, 0x4a, 0xe8, 0xf4, 0x94, 0xeb, 0x8e, 0x6b, 0x05, 0x64, 0xec, 0x3f,
	0x1a, 0x95, 0x03, 0xf1, 0x37, 0xff, 0xad, 0xb5, 0xd7, 0x78, 0x62, 0x22, 0x9c, 0x59, 0xc8, 0x58,
	0xce, 0x33, 0x69, 0x02, 0xe2, 0x92, 0x0c, 0x88, 0x8c, 0x89, 0xd8, 0xc5, 0xd4, 0x28, 0x89, 0x4b,
	0x18, 0xf4, 0x0b, 0x3c, 0x88, 0xcb, 0x7c, 0x22, 0x40, 0xc5, 0x82, 0x49, 0xa2, 0xba, 0x40, 0x78,
	0xfb, 0x16, 0x78, 0x8a, 0x6e, 0x74, 0x50, 0xa9, 0xee, 0xd4, 0xf0, 0x26, 0x5a, 0xc8, 0x55, 0x43,
	0xbc, 0x04, 0xd4, 0x27, 0x32, 0xf6, 0x3c, 0x90, 0xb2, 0x13, 0x87, 0xe1, 0x2e, 0xc5, 0x4b, 0xa8,
	0x5e, 0x71, 0xce, 0xd9, 0x3e, 0x74, 0x02, 0x16, 0xa4, 0x4a, 0x98, 0x6b, 0x2d, 0x87, 0xd5, 0x7e,
	0x1e, 0x9d, 0x44, 0xe5, 0xf7, 0x1a, 0xb1, 0xea, 0xd6, 0xf1, 0x31, 0x74, 0xf4, 0x43, 0x11, 0x28,
	0xb8, 0xf7, 0xc3, 0xef, 0x5f, 0x5a, 0x97, 0x97, 0xcd, 0xc5, 0xf9, 0xd7, 0xb5, 0xfe, 0x69, 0x4e,
	0xa5, 0x7d, 0x27, 0x25, 0xfd, 0xee, 0x00, 0xf4, 0xfc, 0x08, 0x55, 0xda, 0x77, 0x26, 0xc9, 0xbe,
	0x7b, 0xdf, 0x32, 0x1e, 0x58, 0x09, 0xcf, 0xf8, 0x97, 0x12, 0x7a, 0xa1, 0xe8, 0x3a, 0x61, 0x5a,
	0x70, 0xf2, 0xfb, 0xdc, 0xbb, 0x03, 0x32, 0xf5, 0xc4, 0xda, 0x6b, 0x3c, 0xb4, 0x0a, 0x99, 0x5a,
	0x68, 0x81, 0x12, 0x01, 0xec, 0x40, 0x11, 0x0f, 0x01, 0xeb, 0x70, 0xd1, 0x4b, 0xb6, 0x46, 0x65,
	0x79, 0xe8, 0x38, 0xf6, 0x96, 0xb8, 0x6d, 0x1e, 0xab, 0x84, 0xa3, 0x41, 0xb8, 0x8c, 0xc0, 0x0b,
	0x3a, 0x01, 0xf8, 0xa4, 0xbd, 0x9b, 0x18, 0xd6, 0xd7, 0x36, 0x6a, 0xa8, 0xb4, 0xe4, 0x2c, 0xe1,
	0x45, 0x54, 0x6d, 0x25, 0xac, 0x82, 0x4f, 0xfa, 0x5d, 0x60, 0x89, 0x59, 0x80, 0xe4, 0xb1, 0xf0,
	0x80, 0x04, 0x92, 0x30, 0xae, 0x48, 0x87, 0xc7, 0xcc, 0xa7, 0x1b, 0x37, 0x35, 0xd5, 0x0e, 0xbe,
	0x8e, 0xce, 0x66, 0xad, 0x12, 0xb8, 0x0d, 0x5e, 0x7c, 0x58, 0x0c, 0x63, 0x34, 0x3b, 0x64, 0xb8,
	0x8c, 0x8e, 0xb4, 0xc0, 0xf5, 0x13, 0x82, 0x2f, 0xe1, 0x43, 0x60, 0xf7, 0x61, 0x09, 0x9d, 0x9e,
	0x22, 0xcb, 0x85, 0xd3, 0xb8, 0xbf, 0x84, 0x1f, 0x90, 0xe3, 0xc7, 0xd6, 0x5e, 0xe3, 0xe7, 0x29,
	0xd3, 0x98, 0x26, 0x28, 0x9e, 0xc6, 0xc5, 0xd4, 0x28, 0x0b, 0xad, 0x0b, 0x72, 0x9c, 0xed, 0x74,
	0xfe, 0x96, 0x8a, 0xe7, 0x6f, 0x9c, 0x15, 0x12, 0x27, 0x98, 0xfe, 0xbf, 0x32, 0x7f, 0x95, 0x43,
	0x60, 0xe8, 0x47, 0x0b, 0x9d, 0x9e, 0xb2, 0x52, 0x0a, 0x19, 0xda, 0x7f, 0xfd, 0x54, 0x4e, 0xd1,
	0xf4, 0x5b, 0x8a, 0x0e, 0xbe, 0xa5, 0xe8, 0x15, 0xfd, 0x2d, 0x35, 0xff, 0x87, 0xb9, 0xd7, 0x78,
	0x34, 0x85, 0x93, 0x14, 0xb2, 0x98, 0x93, 0x6a, 0x13, 0x44, 0xcf, 0x65, 0xc0, 0x54, 0xb8, 0x4b,
	0xfc, 0xe9, 0x8e, 0x74, 0xc3, 0x49, 0x19, 0x79, 0xf9, 0xa9, 0x8c, 0xa4, 0x28, 0x3e, 0x9d, 0x7e,
	0xb6, 0x97, 0x16, 0xff, 0xe9, 0xc1, 0x56, 0x4a, 0xf7, 0x2d, 0x63, 0xe5, 0xd7, 0xf2, 0x5e, 0xe3,
	0xeb, 0x32, 0x2a, 0xd5, 0xa9, 0x83, 0x6f, 0xa2, 0x53, 0xf9, 0xde, 0x49, 0xa3, 0xb9, 0x8e, 0x2f,
	0x37, 0x05, 0xdf, 0x09, 0x7c, 0x90, 0x64, 0xb5, 0x75, 0x6d, 0x8d, 0xf0, 0x08, 0x44, 0xfa, 0x75,
	0x4a, 0x78, 0xaa, 0x0b, 0x05, 0x71, 0x03, 0xa9, 0xa0, 0xf5, 0xa3, 0x35, 0xea, 0x50, 0x67, 0xd1,
	0xb4, 0xea, 0xb3, 0x6e, 0x14, 0x85, 0x81, 0x97, 0xc4, 0xda, 0xb7, 0x24, 0x67, 0xcb, 0xb9, 0x37,
	0xad, 0xb7, 0x51, 0xe9, 0x35, 0xc7, 0xc1, 0x6f, 0xa1, 0x37, 0x27, 0xe5, 0xc7, 0x65, 0x24, 0x66,
	0x70, 0x3b, 0x02, 0x4f, 0xcb, 0x0a, 0x08, 0xc1, 0x05, 0xe1, 0x9e, 0x17, 0x0b, 0xf0, 0x07, 0x55,
	0x48, 0x10, 0x3b, 0x20, 0x88, 0x0c, 0x7c, 0xa0, 0xad, 0x4d, 0x2d, 0x63, 0x0e, 0xfe, 0x08, 0x5d,
	0x2f, 0x92, 0xb1, 0x54, 0xa5, 0xda, 0xdc, 0xdf, 0xd5, 0x52, 0xd6, 0x73, 0xc3, 0x74, 0x6e, 0x34,
	0x34, 0x17, 0xc4, 0xe7, 0x90, 0xea, 0x5b, 0xcf, 0x55, 0x5e, 0x37, 0x09, 0x19, 0x66, 0xce, 0x62,
	0x69, 0xeb, 0x5d, 0x9d, 0xa0, 0x86, 0xaf, 0xa0, 0xd5, 0xe9, 0x09, 0x86, 0x40, 0x1e, 0x67, 0xca,
	0x0d, 0xb2, 0x0d, 0x19, 0x4b, 0x10, 0x0b, 0x52, 0x2f, 0x41, 0x1f, 0x98, 0x0a, 0xdc, 0x50, 0xd2,
	0x56, 0x53, 0xa3, 0x5d, 0xc0, 0xeb, 0xe8, 0x6a, 0x1e, 0x4d, 0xfb, 0x8f, 0xa0, 0xba, 0xae, 0xd6,
	0x7f, 0x10, 0xbd, 0x40, 0x4a, 0x7d, 0xd0, 0x8a, 0x13, 0x37, 0xb9, 0x3b, 0x13, 0x0a, 0x4d, 0x5b,
	0x7f, 0x5f, 0xc7, 0x6f, 0x3c, 0xb2, 0xd0, 0x43, 0x6b, 0x78, 0xe1, 0xbe, 0xb2, 0x66, 0x4a, 0xf8,
	0x0b, 0xb3, 0x91, 0x81, 0xf3, 0xa2, 0xa5, 0x33, 0x00, 0x92, 0x1a, 0x49, 0x80, 0x54, 0x22, 0x48,
	0x4e, 0x49, 0x17, 0x15, 0xab, 0xae, 0x6e, 0xcf, 0x4b, 0x36, 0xbd, 0xee, 0x41, 0x52, 0xf2, 0x41,
	0x17, 0xc6, 0x0d, 0x1a, 0x22, 0x12, 0x3c, 0x49, 0xd0, 0xe1, 0x61, 0xc8, 0xfb, 0x69, 0x17, 0xba,
	0x00, 0x2e, 0x82, 0x4f, 0x52, 0x0f, 0x7d, 0x6f, 0x49, 0x27, 0xe4, 0x7d, 0x5a, 0x3d, 0x52, 0x9f,
	0xd1, 0xf7, 0x5e, 0x43, 0x2c, 0x1f, 0xd7, 0xbf, 0x14, 0xdf, 0x06, 0xb6, 0x72, 0x0b, 0xd5, 0xd3,
	0xbd, 0x80, 0x17, 0xbb, 0x4a, 0x45, 0x72, 0xd9, 0x4e, 0x5c, 0x68, 0x9b, 0x6d, 0x53, 0xc5, 0xf3,
	0x2a, 0x46, 0x05, 0xb8, 0x3e, 0x5a, 0xca, 0x26, 0x0a, 0xbf, 0x72, 0xb0, 0xa0, 0xbe, 0x76, 0x7e,
	0xc7, 0x6c, 0x1a, 0x37, 0xf2, 0xff, 0xed, 0x7d, 0x66, 0x1a, 0xf7, 0x4d, 0xe3, 0x81, 0x69, 0x7c,
	0x67, 0x1a, 0x3f, 0x99, 0xc6, 0x9f, 0xa6, 0xf1, 0xbd, 0x65, 0xb4, 0xcb, 0x89, 0xc6, 0x5c, 0xf8,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x73, 0xcf, 0xdb, 0x73, 0x5b, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductCollectionServiceClient is the client API for ProductCollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductCollectionServiceClient interface {
	// CreateProductCollection creates a new product collection.
	CreateProductCollection(ctx context.Context, in *CreateProductCollectionRequest, opts ...grpc.CallOption) (*ProductCollection, error)
	// GetProductCollection retrieves the details of a specific product information, selected by its ID.
	GetProductCollection(ctx context.Context, in *GetProductCollectionRequest, opts ...grpc.CallOption) (*ProductCollection, error)
	// UpdateProductCollection updates the product collection.
	UpdateProductCollection(ctx context.Context, in *UpdateProductCollectionRequest, opts ...grpc.CallOption) (*ProductCollection, error)
	// DeleteProductCollection deletes a product collection.
	DeleteProductCollection(ctx context.Context, in *DeleteProductCollectionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type productCollectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductCollectionServiceClient(cc *grpc.ClientConn) ProductCollectionServiceClient {
	return &productCollectionServiceClient{cc}
}

func (c *productCollectionServiceClient) CreateProductCollection(ctx context.Context, in *CreateProductCollectionRequest, opts ...grpc.CallOption) (*ProductCollection, error) {
	out := new(ProductCollection)
	err := c.cc.Invoke(ctx, "/productcollection.ProductCollectionService/CreateProductCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCollectionServiceClient) GetProductCollection(ctx context.Context, in *GetProductCollectionRequest, opts ...grpc.CallOption) (*ProductCollection, error) {
	out := new(ProductCollection)
	err := c.cc.Invoke(ctx, "/productcollection.ProductCollectionService/GetProductCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCollectionServiceClient) UpdateProductCollection(ctx context.Context, in *UpdateProductCollectionRequest, opts ...grpc.CallOption) (*ProductCollection, error) {
	out := new(ProductCollection)
	err := c.cc.Invoke(ctx, "/productcollection.ProductCollectionService/UpdateProductCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCollectionServiceClient) DeleteProductCollection(ctx context.Context, in *DeleteProductCollectionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/productcollection.ProductCollectionService/DeleteProductCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductCollectionServiceServer is the server API for ProductCollectionService service.
type ProductCollectionServiceServer interface {
	// CreateProductCollection creates a new product collection.
	CreateProductCollection(context.Context, *CreateProductCollectionRequest) (*ProductCollection, error)
	// GetProductCollection retrieves the details of a specific product information, selected by its ID.
	GetProductCollection(context.Context, *GetProductCollectionRequest) (*ProductCollection, error)
	// UpdateProductCollection updates the product collection.
	UpdateProductCollection(context.Context, *UpdateProductCollectionRequest) (*ProductCollection, error)
	// DeleteProductCollection deletes a product collection.
	DeleteProductCollection(context.Context, *DeleteProductCollectionRequest) (*empty.Empty, error)
}

// UnimplementedProductCollectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductCollectionServiceServer struct {
}

func (*UnimplementedProductCollectionServiceServer) CreateProductCollection(ctx context.Context, req *CreateProductCollectionRequest) (*ProductCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductCollection not implemented")
}
func (*UnimplementedProductCollectionServiceServer) GetProductCollection(ctx context.Context, req *GetProductCollectionRequest) (*ProductCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductCollection not implemented")
}
func (*UnimplementedProductCollectionServiceServer) UpdateProductCollection(ctx context.Context, req *UpdateProductCollectionRequest) (*ProductCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductCollection not implemented")
}
func (*UnimplementedProductCollectionServiceServer) DeleteProductCollection(ctx context.Context, req *DeleteProductCollectionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductCollection not implemented")
}

func RegisterProductCollectionServiceServer(s *grpc.Server, srv ProductCollectionServiceServer) {
	s.RegisterService(&_ProductCollectionService_serviceDesc, srv)
}

func _ProductCollectionService_CreateProductCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCollectionServiceServer).CreateProductCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productcollection.ProductCollectionService/CreateProductCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCollectionServiceServer).CreateProductCollection(ctx, req.(*CreateProductCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCollectionService_GetProductCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCollectionServiceServer).GetProductCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productcollection.ProductCollectionService/GetProductCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCollectionServiceServer).GetProductCollection(ctx, req.(*GetProductCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCollectionService_UpdateProductCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCollectionServiceServer).UpdateProductCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productcollection.ProductCollectionService/UpdateProductCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCollectionServiceServer).UpdateProductCollection(ctx, req.(*UpdateProductCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCollectionService_DeleteProductCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCollectionServiceServer).DeleteProductCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/productcollection.ProductCollectionService/DeleteProductCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCollectionServiceServer).DeleteProductCollection(ctx, req.(*DeleteProductCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductCollectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "productcollection.ProductCollectionService",
	HandlerType: (*ProductCollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProductCollection",
			Handler:    _ProductCollectionService_CreateProductCollection_Handler,
		},
		{
			MethodName: "GetProductCollection",
			Handler:    _ProductCollectionService_GetProductCollection_Handler,
		},
		{
			MethodName: "UpdateProductCollection",
			Handler:    _ProductCollectionService_UpdateProductCollection_Handler,
		},
		{
			MethodName: "DeleteProductCollection",
			Handler:    _ProductCollectionService_DeleteProductCollection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openbank/openbank/v1/productcollection/all.proto",
}
