// Code generated by "scopegen"; DO NOT EDIT.
package customer

type ServiceScope struct{}

var Scopes = map[string]string{
	"https://auth.bnk.to/customer.read": "View customer data",
	"https://auth.bnk.to/customer.write": "Manage customer data",
}

var AuthScopes = map[string][]string{
	"/customer.CustomerService/AddAddressToCustomer": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/AddSocialMediaHandle": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/CreateCreditLimitOrder": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/CreateCustomer": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/CreateUserCustomerLink": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/DeleteCustomerAddress": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/DeleteTaxResidence": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/GetCRMEvents": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCreditLimitOrder": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCreditLimitOrderByID": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCustomerAddresses": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCustomerByCustomerID": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCustomerByCustomerNumber": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCustomerSocialMediaHandles": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCustomersForCurrentUser": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetCustomersForCurrentUserAtBank": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetFirehoseCustomer": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/GetTaxResidenceOfCustomer": []string{"https://auth.bnk.to/customer.read"},
	"/customer.CustomerService/UpdateCustomerAddress": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerBranch": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerCreditLimit": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerCreditRatingAndSource": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerEmail": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerIdentity": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerMobileNumber": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerNumber": []string{"https://auth.bnk.to/customer.write"},
	"/customer.CustomerService/UpdateCustomerOtherData": []string{"https://auth.bnk.to/customer.write"},
}

// Any allows a loose challenge, for claims containing any of the method scopes.
//
// Use All method as a default for OAuth2 style scopes.  Any is useful with more complex scope definitions.
func (svcSc *ServiceScope) Any(method string, claims []string) bool {
	ch := AuthScopes[method]
	for _, s := range ch {
		for _, c := range claims {
			if string(s) == c {
				return true
			}
		}
	}
	return len(ch) == 0
}

// All is the default OAuth2 challenge method, ensuring claims contains all method scopes.
func (svcSc *ServiceScope) All(method string, claims []string) bool {
	ch := AuthScopes[method]
	if len(ch) > len(claims) {
		return false
	}
scopes:
	for _, s := range ch {
		for _, c := range claims {
			if string(s) == c {
				continue scopes
			}
		}
		return false
	}
	return true
}
